use crate::json_struct::{Base16, Colors, MShell, MatugenTheme, Palettes, color};

/// `Ayu Dark` — dark theme imported from the community palette
/// collection (noctalia format). M3 roles map from the palette's `m*`
/// keys; container/fixed shades are derived luminance blends; the base16
/// accent ramp maps from the terminal ANSI set.
pub fn ayu_dark(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#0B0E14"),
            base01: color("#090C11"),
            base02: color("#1E222A"),
            base03: color("#2C2F37"),
            base04: color("#727882"),
            base05: color("#D1D1C7"),
            base06: color("#8E959E"),
            base07: color("#60666E"),
            base08: color("#ED8274"),
            base09: color("#F4A771"),
            base0a: color("#FACC6E"),
            base0b: color("#87D96C"),
            base0c: color("#90E1C6"),
            base0d: color("#6DCBFA"),
            base0e: color("#DABAFA"),
            base0f: color("#9E5952"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#0B0E14"),
            on_surface: color("#D1D1C7"),
            surface_variant: color("#1E222A"),
            on_surface_variant: color("#8E959E"),
            surface_container_highest: color("#3E4148"),
            surface_container_high: color("#2C2F37"),
            surface_container: color("#1E222A"),
            surface_container_low: color("#090C11"),
            surface_container_lowest: color("#07090D"),
            inverse_surface: color("#D1D1C7"),
            inverse_on_surface: color("#1E222A"),
            surface_tint: color("#39BAE6"),
            primary: color("#39BAE6"),
            on_primary: color("#0B0E14"),
            primary_container: color("#183E4F"),
            on_primary_container: color("#4DC1E8"),
            secondary: color("#AAD94C"),
            on_secondary: color("#0B0E14"),
            secondary_container: color("#384724"),
            on_secondary_container: color("#B2DD5E"),
            tertiary: color("#E6B450"),
            on_tertiary: color("#0B0E14"),
            tertiary_container: color("#483C25"),
            on_tertiary_container: color("#E8BC62"),
            error: color("#D95757"),
            on_error: color("#0B0E14"),
            error_container: color("#452227"),
            on_error_container: color("#DD6868"),
            outline: color("#565B66"),
            outline_variant: color("#343841"),
            background: color("#0B0E14"),
            on_background: color("#D1D1C7"),
            inverse_primary: color("#183E4F"),
            primary_fixed: color("#39BAE6"),
            primary_fixed_dim: color("#32A4CA"),
            on_primary_fixed: color("#0B0E14"),
            on_primary_fixed_variant: color("#0B0E14"),
            secondary_fixed: color("#AAD94C"),
            secondary_fixed_dim: color("#96BF43"),
            on_secondary_fixed: color("#0B0E14"),
            on_secondary_fixed_variant: color("#0B0E14"),
            tertiary_fixed: color("#E6B450"),
            tertiary_fixed_dim: color("#CA9E46"),
            on_tertiary_fixed: color("#0B0E14"),
            on_tertiary_fixed_variant: color("#0B0E14"),
            scrim: color("#000000"),
            shadow: color("#000000"),
            source_color: color("#39BAE6"),
            surface_bright: color("#3E4148"),
            surface_dim: color("#07090D"),
        },
    }
}
