use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn bauhaus(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#101318"),
            base01: color("#161B22"),
            base02: color("#2B3040"),
            base03: color("#98A0AE"),
            base04: color("#C6CED8"),
            base05: color("#EAEFF5"),
            base06: color("#EAEFF5"),
            base07: color("#C6CED8"),
            base08: color("#CB886D"),
            base09: color("#E0A568"),
            base0a: color("#E7A46F"),
            base0b: color("#789FA2"),
            base0c: color("#809D9E"),
            base0d: color("#E37B66"),
            base0e: color("#8999AA"),
            base0f: color("#E0A568"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#101318"),
            on_surface: color("#EAEFF5"),
            surface_variant: color("#161B22"),
            on_surface_variant: color("#C6CED8"),
            surface_container_highest: color("#2B3040"),
            surface_container_high: color("#222733"),
            surface_container: color("#1B202A"),
            surface_container_low: color("#161B22"),
            surface_container_lowest: color("#101318"),
            inverse_surface: color("#EAEFF5"),
            inverse_on_surface: color("#101318"),
            surface_tint: color("#E37B66"),
            primary: color("#E37B66"),
            on_primary: color("#101318"),
            primary_container: color("#222733"),
            on_primary_container: color("#E37B66"),
            secondary: color("#E0A568"),
            on_secondary: color("#101318"),
            secondary_container: color("#222733"),
            on_secondary_container: color("#E0A568"),
            tertiary: color("#809D9E"),
            on_tertiary: color("#101318"),
            tertiary_container: color("#222733"),
            on_tertiary_container: color("#809D9E"),
            error: color("#CB886D"),
            on_error: color("#101318"),
            error_container: color("#222733"),
            on_error_container: color("#CB886D"),
            outline: color("#98A0AE"),
            outline_variant: color("#2B3040"),
            background: color("#101318"),
            on_background: color("#EAEFF5"),
            inverse_primary: color("#E37B66"),
            primary_fixed: color("#E37B66"),
            primary_fixed_dim: color("#CB886D"),
            on_primary_fixed: color("#101318"),
            on_primary_fixed_variant: color("#EAEFF5"),
            secondary_fixed: color("#E0A568"),
            secondary_fixed_dim: color("#E7A46F"),
            on_secondary_fixed: color("#101318"),
            on_secondary_fixed_variant: color("#EAEFF5"),
            tertiary_fixed: color("#809D9E"),
            tertiary_fixed_dim: color("#789FA2"),
            on_tertiary_fixed: color("#101318"),
            on_tertiary_fixed_variant: color("#EAEFF5"),
            scrim: color("#101318"),
            shadow: color("#101318"),
            source_color: color("#E37B66"),
            surface_bright: color("#2B3040"),
            surface_dim: color("#101318"),
        },
    }
}
