use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn black_turq(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#0a0a0a"),
            base01: color("#141416"),
            base02: color("#322F3B"),
            base03: color("#485362"),
            base04: color("#5a676b"),
            base05: color("#c8dcdc"),
            base06: color("#d2d9db"),
            base07: color("#c4d8e2"),
            base08: color("#D35F5F"),
            base09: color("#A9D1D7"),
            base0a: color("#c4d8e2"),
            base0b: color("#8FECD5"),
            base0c: color("#ADF0E9"),
            base0d: color("#75dddd"),
            base0e: color("#A9D1D7"),
            base0f: color("#D35F5F"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#0a0a0a"),
            on_surface: color("#c8dcdc"),
            surface_variant: color("#141416"),
            on_surface_variant: color("#A9D1D7"),
            surface_container_highest: color("#322F3B"),
            surface_container_high: color("#26242d"),
            surface_container: color("#1c1b21"),
            surface_container_low: color("#141416"),
            surface_container_lowest: color("#0a0a0a"),
            inverse_surface: color("#c8dcdc"),
            inverse_on_surface: color("#0a0a0a"),
            surface_tint: color("#ADF0E9"),
            primary: color("#ADF0E9"),
            on_primary: color("#0a0a0a"),
            primary_container: color("#141416"),
            on_primary_container: color("#ADF0E9"),
            secondary: color("#8FECD5"),
            on_secondary: color("#0a0a0a"),
            secondary_container: color("#141416"),
            on_secondary_container: color("#8FECD5"),
            tertiary: color("#A9D1D7"),
            on_tertiary: color("#0a0a0a"),
            tertiary_container: color("#141416"),
            on_tertiary_container: color("#A9D1D7"),
            error: color("#D35F5F"),
            on_error: color("#0a0a0a"),
            error_container: color("#141416"),
            on_error_container: color("#D35F5F"),
            outline: color("#485362"),
            outline_variant: color("#322F3B"),
            background: color("#0a0a0a"),
            on_background: color("#c8dcdc"),
            inverse_primary: color("#ADF0E9"),
            primary_fixed: color("#ADF0E9"),
            primary_fixed_dim: color("#75dddd"),
            on_primary_fixed: color("#0a0a0a"),
            on_primary_fixed_variant: color("#c8dcdc"),
            secondary_fixed: color("#8FECD5"),
            secondary_fixed_dim: color("#A9D1D7"),
            on_secondary_fixed: color("#0a0a0a"),
            on_secondary_fixed_variant: color("#c8dcdc"),
            tertiary_fixed: color("#A9D1D7"),
            tertiary_fixed_dim: color("#c4d8e2"),
            on_tertiary_fixed: color("#0a0a0a"),
            on_tertiary_fixed_variant: color("#c8dcdc"),
            scrim: color("#0a0a0a"),
            shadow: color("#0a0a0a"),
            source_color: color("#ADF0E9"),
            surface_bright: color("#322F3B"),
            surface_dim: color("#0a0a0a"),
        },
    }
}
