use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn blood_rust(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#1F2932"),
            base01: color("#222E38"),
            base02: color("#25323D"),
            base03: color("#293642"),
            base04: color("#2C3A47"),
            base05: color("#AFB3BD"),
            base06: color("#AFB3BD"),
            base07: color("#AFB3BD"),
            base08: color("#7C545F"),
            base09: color("#5E4D52"),
            base0a: color("#7C7C54"),
            base0b: color("#547C71"),
            base0c: color("#54737C"),
            base0d: color("#54737C"),
            base0e: color("#72547C"),
            base0f: color("#7C545F"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#1F2932"),
            on_surface: color("#AFB3BD"),
            surface_variant: color("#222E38"),
            on_surface_variant: color("#AFB3BD"),
            surface_container_highest: color("#324351"),
            surface_container_high: color("#2F3E4C"),
            surface_container: color("#2C3A47"),
            surface_container_low: color("#25323D"),
            surface_container_lowest: color("#1F2932"),
            inverse_surface: color("#AFB3BD"),
            inverse_on_surface: color("#1F2932"),
            surface_tint: color("#7C545F"),
            primary: color("#7C545F"),
            on_primary: color("#AFB3BD"),
            primary_container: color("#293642"),
            on_primary_container: color("#7C545F"),
            secondary: color("#54737C"),
            on_secondary: color("#AFB3BD"),
            secondary_container: color("#293642"),
            on_secondary_container: color("#54737C"),
            tertiary: color("#547C71"),
            on_tertiary: color("#AFB3BD"),
            tertiary_container: color("#293642"),
            on_tertiary_container: color("#547C71"),
            error: color("#7C545F"),
            on_error: color("#AFB3BD"),
            error_container: color("#293642"),
            on_error_container: color("#7C545F"),
            outline: color("#2F3E4C"),
            outline_variant: color("#2C3A47"),
            background: color("#1F2932"),
            on_background: color("#AFB3BD"),
            inverse_primary: color("#5E4D52"),
            primary_fixed: color("#7C545F"),
            primary_fixed_dim: color("#7C545F"),
            on_primary_fixed: color("#AFB3BD"),
            on_primary_fixed_variant: color("#AFB3BD"),
            secondary_fixed: color("#54737C"),
            secondary_fixed_dim: color("#54737C"),
            on_secondary_fixed: color("#AFB3BD"),
            on_secondary_fixed_variant: color("#AFB3BD"),
            tertiary_fixed: color("#547C71"),
            tertiary_fixed_dim: color("#547C71"),
            on_tertiary_fixed: color("#AFB3BD"),
            on_tertiary_fixed_variant: color("#AFB3BD"),
            scrim: color("#1F2932"),
            shadow: color("#1F2932"),
            source_color: color("#7C545F"),
            surface_bright: color("#324351"),
            surface_dim: color("#1F2932"),
        },
    }
}
