use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn catppuccin_macchiato(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#24273a"),
            base01: color("#1e2030"),
            base02: color("#363a4f"),
            base03: color("#494d64"),
            base04: color("#5b6078"),
            base05: color("#cad3f5"),
            base06: color("#f4dbd6"),
            base07: color("#b7bdf8"),
            base08: color("#ed8796"),
            base09: color("#f5a97f"),
            base0a: color("#eed49f"),
            base0b: color("#a6da95"),
            base0c: color("#8bd5ca"),
            base0d: color("#8aadf4"),
            base0e: color("#c6a0f6"),
            base0f: color("#f0c6c6"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#24273a"),
            on_surface: color("#cad3f5"),
            surface_variant: color("#363a4f"),
            on_surface_variant: color("#b8c0e0"),
            surface_container_highest: color("#5b6078"),
            surface_container_high: color("#494d64"),
            surface_container: color("#363a4f"),
            surface_container_low: color("#1e2030"),
            surface_container_lowest: color("#181926"),
            inverse_surface: color("#cad3f5"),
            inverse_on_surface: color("#363a4f"),
            surface_tint: color("#b7bdf8"),
            primary: color("#b7bdf8"),
            on_primary: color("#363a4f"),
            primary_container: color("#363a4f"),
            on_primary_container: color("#b7bdf8"),
            secondary: color("#f0c6c6"),
            on_secondary: color("#363a4f"),
            secondary_container: color("#363a4f"),
            on_secondary_container: color("#f0c6c6"),
            tertiary: color("#8bd5ca"),
            on_tertiary: color("#363a4f"),
            tertiary_container: color("#363a4f"),
            on_tertiary_container: color("#8bd5ca"),
            error: color("#ed8796"),
            on_error: color("#363a4f"),
            error_container: color("#363a4f"),
            on_error_container: color("#ed8796"),
            outline: color("#a5adcb"),
            outline_variant: color("#6e738d"),
            background: color("#24273a"),
            on_background: color("#cad3f5"),
            inverse_primary: color("#363a4f"),
            primary_fixed: color("#b7bdf8"),
            primary_fixed_dim: color("#b7bdf8"),
            on_primary_fixed: color("#363a4f"),
            on_primary_fixed_variant: color("#363a4f"),
            secondary_fixed: color("#f0c6c6"),
            secondary_fixed_dim: color("#f0c6c6"),
            on_secondary_fixed: color("#363a4f"),
            on_secondary_fixed_variant: color("#363a4f"),
            tertiary_fixed: color("#8bd5ca"),
            tertiary_fixed_dim: color("#8bd5ca"),
            on_tertiary_fixed: color("#363a4f"),
            on_tertiary_fixed_variant: color("#363a4f"),
            scrim: color("#181926"),
            shadow: color("#181926"),
            source_color: color("#b7bdf8"),
            surface_bright: color("#5b6078"),
            surface_dim: color("#181926"),
        },
    }
}
