use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn catppuccin_frappe(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#303446"),
            base01: color("#292c3c"),
            base02: color("#414559"),
            base03: color("#51576d"),
            base04: color("#626880"),
            base05: color("#c6d0f5"),
            base06: color("#f2d5cf"),
            base07: color("#babbf1"),
            base08: color("#e78284"),
            base09: color("#ef9f76"),
            base0a: color("#e5c890"),
            base0b: color("#a6d189"),
            base0c: color("#81c8be"),
            base0d: color("#8caaee"),
            base0e: color("#ca9ee6"),
            base0f: color("#eebebe"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#303446"),
            on_surface: color("#c6d0f5"),
            surface_variant: color("#414559"),
            on_surface_variant: color("#b5bfe2"),
            surface_container_highest: color("#626880"),
            surface_container_high: color("#51576d"),
            surface_container: color("#414559"),
            surface_container_low: color("#292c3c"),
            surface_container_lowest: color("#232634"),
            inverse_surface: color("#c6d0f5"),
            inverse_on_surface: color("#414559"),
            surface_tint: color("#babbf1"),
            primary: color("#babbf1"),
            on_primary: color("#414559"),
            primary_container: color("#414559"),
            on_primary_container: color("#babbf1"),
            secondary: color("#eebebe"),
            on_secondary: color("#414559"),
            secondary_container: color("#414559"),
            on_secondary_container: color("#eebebe"),
            tertiary: color("#81c8be"),
            on_tertiary: color("#414559"),
            tertiary_container: color("#414559"),
            on_tertiary_container: color("#81c8be"),
            error: color("#e78284"),
            on_error: color("#414559"),
            error_container: color("#414559"),
            on_error_container: color("#e78284"),
            outline: color("#a5adce"),
            outline_variant: color("#737994"),
            background: color("#303446"),
            on_background: color("#c6d0f5"),
            inverse_primary: color("#414559"),
            primary_fixed: color("#babbf1"),
            primary_fixed_dim: color("#babbf1"),
            on_primary_fixed: color("#414559"),
            on_primary_fixed_variant: color("#414559"),
            secondary_fixed: color("#eebebe"),
            secondary_fixed_dim: color("#eebebe"),
            on_secondary_fixed: color("#414559"),
            on_secondary_fixed_variant: color("#414559"),
            tertiary_fixed: color("#81c8be"),
            tertiary_fixed_dim: color("#81c8be"),
            on_tertiary_fixed: color("#414559"),
            on_tertiary_fixed_variant: color("#414559"),
            scrim: color("#232634"),
            shadow: color("#232634"),
            source_color: color("#babbf1"),
            surface_bright: color("#626880"),
            surface_dim: color("#232634"),
        },
    }
}
