use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn catppuccin_latte(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: false,
        mode: "light".to_string(),
        base16: Base16 {
            base00: color("#eff1f5"),
            base01: color("#e6e9ef"),
            base02: color("#ccd0da"),
            base03: color("#bcc0cc"),
            base04: color("#acb0be"),
            base05: color("#4c4f69"),
            base06: color("#dc8a78"),
            base07: color("#7287fd"),
            base08: color("#d20f39"),
            base09: color("#fe640b"),
            base0a: color("#df8e1d"),
            base0b: color("#40a02b"),
            base0c: color("#179299"),
            base0d: color("#1e66f5"),
            base0e: color("#8839ef"),
            base0f: color("#dd7878"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#eff1f5"),
            on_surface: color("#4c4f69"),
            surface_variant: color("#ccd0da"),
            on_surface_variant: color("#5c5f77"),
            surface_container_highest: color("#acb0be"),
            surface_container_high: color("#bcc0cc"),
            surface_container: color("#ccd0da"),
            surface_container_low: color("#e6e9ef"),
            surface_container_lowest: color("#dce0e8"),
            inverse_surface: color("#4c4f69"),
            inverse_on_surface: color("#ccd0da"),
            surface_tint: color("#7287fd"),
            primary: color("#7287fd"),
            on_primary: color("#ccd0da"),
            primary_container: color("#ccd0da"),
            on_primary_container: color("#7287fd"),
            secondary: color("#dd7878"),
            on_secondary: color("#ccd0da"),
            secondary_container: color("#ccd0da"),
            on_secondary_container: color("#dd7878"),
            tertiary: color("#179299"),
            on_tertiary: color("#ccd0da"),
            tertiary_container: color("#ccd0da"),
            on_tertiary_container: color("#179299"),
            error: color("#d20f39"),
            on_error: color("#ccd0da"),
            error_container: color("#ccd0da"),
            on_error_container: color("#d20f39"),
            outline: color("#6c6f85"),
            outline_variant: color("#9ca0b0"),
            background: color("#eff1f5"),
            on_background: color("#4c4f69"),
            inverse_primary: color("#ccd0da"),
            primary_fixed: color("#7287fd"),
            primary_fixed_dim: color("#7287fd"),
            on_primary_fixed: color("#ccd0da"),
            on_primary_fixed_variant: color("#ccd0da"),
            secondary_fixed: color("#dd7878"),
            secondary_fixed_dim: color("#dd7878"),
            on_secondary_fixed: color("#ccd0da"),
            on_secondary_fixed_variant: color("#ccd0da"),
            tertiary_fixed: color("#179299"),
            tertiary_fixed_dim: color("#179299"),
            on_tertiary_fixed: color("#ccd0da"),
            on_tertiary_fixed_variant: color("#ccd0da"),
            scrim: color("#dce0e8"),
            shadow: color("#dce0e8"),
            source_color: color("#7287fd"),
            surface_bright: color("#acb0be"),
            surface_dim: color("#dce0e8"),
        },
    }
}
