use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn catppuccin_mocha(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#1e1e2e"),
            base01: color("#181825"),
            base02: color("#313244"),
            base03: color("#45475a"),
            base04: color("#585b70"),
            base05: color("#cdd6f4"),
            base06: color("#f5e0dc"),
            base07: color("#b4befe"),
            base08: color("#f38ba8"),
            base09: color("#fab387"),
            base0a: color("#f9e2af"),
            base0b: color("#a6e3a1"),
            base0c: color("#94e2d5"),
            base0d: color("#89b4fa"),
            base0e: color("#cba6f7"),
            base0f: color("#f2cdcd"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#1e1e2e"),
            on_surface: color("#cdd6f4"),
            surface_variant: color("#313244"),
            on_surface_variant: color("#bac2de"),
            surface_container_highest: color("#585b70"),
            surface_container_high: color("#45475a"),
            surface_container: color("#313244"),
            surface_container_low: color("#181825"),
            surface_container_lowest: color("#11111b"),
            inverse_surface: color("#cdd6f4"),
            inverse_on_surface: color("#313244"),
            surface_tint: color("#b4befe"),
            primary: color("#b4befe"),
            on_primary: color("#313244"),
            primary_container: color("#313244"),
            on_primary_container: color("#b4befe"),
            secondary: color("#f2cdcd"),
            on_secondary: color("#313244"),
            secondary_container: color("#313244"),
            on_secondary_container: color("#f2cdcd"),
            tertiary: color("#94e2d5"),
            on_tertiary: color("#313244"),
            tertiary_container: color("#313244"),
            on_tertiary_container: color("#94e2d5"),
            error: color("#f38ba8"),
            on_error: color("#313244"),
            error_container: color("#313244"),
            on_error_container: color("#f38ba8"),
            outline: color("#a6adc8"),
            outline_variant: color("#6c7086"),
            background: color("#1e1e2e"),
            on_background: color("#cdd6f4"),
            inverse_primary: color("#313244"),
            primary_fixed: color("#b4befe"),
            primary_fixed_dim: color("#b4befe"),
            on_primary_fixed: color("#313244"),
            on_primary_fixed_variant: color("#313244"),
            secondary_fixed: color("#f2cdcd"),
            secondary_fixed_dim: color("#f2cdcd"),
            on_secondary_fixed: color("#313244"),
            on_secondary_fixed_variant: color("#313244"),
            tertiary_fixed: color("#94e2d5"),
            tertiary_fixed_dim: color("#94e2d5"),
            on_tertiary_fixed: color("#313244"),
            on_tertiary_fixed_variant: color("#313244"),
            scrim: color("#11111b"),
            shadow: color("#11111b"),
            source_color: color("#b4befe"),
            surface_bright: color("#585b70"),
            surface_dim: color("#11111b"),
        },
    }
}
