use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn cyberpunk(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#000000"),
            base01: color("#00008B"),
            base02: color("#4B0082"),
            base03: color("#008080"),
            base04: color("#87CEEB"),
            base05: color("#FFFF00"),
            base06: color("#FFFF00"),
            base07: color("#FFFF00"),
            base08: color("#FF0000"),
            base09: color("#FFA500"),
            base0a: color("#FFB6C1"),
            base0b: color("#00FF00"),
            base0c: color("#00FFFF"),
            base0d: color("#00FFFF"),
            base0e: color("#FF00FF"),
            base0f: color("#FF4500"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#000000"),
            on_surface: color("#FFFF00"),
            surface_variant: color("#00008B"),
            on_surface_variant: color("#FFFF00"),
            surface_container_highest: color("#008080"),
            surface_container_high: color("#4B0082"),
            surface_container: color("#00008B"),
            surface_container_low: color("#00008B"),
            surface_container_lowest: color("#000000"),
            inverse_surface: color("#FFFF00"),
            inverse_on_surface: color("#000000"),
            surface_tint: color("#00FFFF"),
            primary: color("#00FFFF"),
            on_primary: color("#000000"),
            primary_container: color("#4B0082"),
            on_primary_container: color("#00FFFF"),
            secondary: color("#FF00FF"),
            on_secondary: color("#000000"),
            secondary_container: color("#4B0082"),
            on_secondary_container: color("#FF00FF"),
            tertiary: color("#00FF00"),
            on_tertiary: color("#000000"),
            tertiary_container: color("#4B0082"),
            on_tertiary_container: color("#00FF00"),
            error: color("#FF0000"),
            on_error: color("#000000"),
            error_container: color("#4B0082"),
            on_error_container: color("#FF0000"),
            outline: color("#4B0082"),
            outline_variant: color("#00008B"),
            background: color("#000000"),
            on_background: color("#FFFF00"),
            inverse_primary: color("#FF1493"),
            primary_fixed: color("#00FFFF"),
            primary_fixed_dim: color("#00FFFF"),
            on_primary_fixed: color("#000000"),
            on_primary_fixed_variant: color("#000000"),
            secondary_fixed: color("#FF00FF"),
            secondary_fixed_dim: color("#FF00FF"),
            on_secondary_fixed: color("#000000"),
            on_secondary_fixed_variant: color("#000000"),
            tertiary_fixed: color("#00FF00"),
            tertiary_fixed_dim: color("#00FF00"),
            on_tertiary_fixed: color("#000000"),
            on_tertiary_fixed_variant: color("#000000"),
            scrim: color("#000000"),
            shadow: color("#000000"),
            source_color: color("#00FFFF"),
            surface_bright: color("#008080"),
            surface_dim: color("#000000"),
        },
    }
}
