use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn desert_power(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#11100F"),
            base01: color("#161413"),
            base02: color("#1A1817"),
            base03: color("#1E1C1B"),
            base04: color("#22201E"),
            base05: color("#A1A09F"),
            base06: color("#A1A09F"),
            base07: color("#A1A09F"),
            base08: color("#B5745A"),
            base09: color("#AF8F6B"),
            base0a: color("#9EA886"),
            base0b: color("#385752"),
            base0c: color("#8EBABB"),
            base0d: color("#55504D"),
            base0e: color("#55504D"),
            base0f: color("#B5745A"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#11100F"),
            on_surface: color("#A1A09F"),
            surface_variant: color("#161413"),
            on_surface_variant: color("#A1A09F"),
            surface_container_highest: color("#3C3834"),
            surface_container_high: color("#33302D"),
            surface_container: color("#22201E"),
            surface_container_low: color("#1A1817"),
            surface_container_lowest: color("#11100F"),
            inverse_surface: color("#A1A09F"),
            inverse_on_surface: color("#11100F"),
            surface_tint: color("#55504D"),
            primary: color("#55504D"),
            on_primary: color("#A1A09F"),
            primary_container: color("#1E1C1B"),
            on_primary_container: color("#55504D"),
            secondary: color("#8EBABB"),
            on_secondary: color("#11100F"),
            secondary_container: color("#1E1C1B"),
            on_secondary_container: color("#8EBABB"),
            tertiary: color("#AF8F6B"),
            on_tertiary: color("#11100F"),
            tertiary_container: color("#1E1C1B"),
            on_tertiary_container: color("#AF8F6B"),
            error: color("#B5745A"),
            on_error: color("#11100F"),
            error_container: color("#1E1C1B"),
            on_error_container: color("#B5745A"),
            outline: color("#33302D"),
            outline_variant: color("#22201E"),
            background: color("#11100F"),
            on_background: color("#A1A09F"),
            inverse_primary: color("#AF8F6B"),
            primary_fixed: color("#55504D"),
            primary_fixed_dim: color("#55504D"),
            on_primary_fixed: color("#A1A09F"),
            on_primary_fixed_variant: color("#A1A09F"),
            secondary_fixed: color("#8EBABB"),
            secondary_fixed_dim: color("#8EBABB"),
            on_secondary_fixed: color("#11100F"),
            on_secondary_fixed_variant: color("#11100F"),
            tertiary_fixed: color("#AF8F6B"),
            tertiary_fixed_dim: color("#AF8F6B"),
            on_tertiary_fixed: color("#11100F"),
            on_tertiary_fixed_variant: color("#11100F"),
            scrim: color("#11100F"),
            shadow: color("#11100F"),
            source_color: color("#55504D"),
            surface_bright: color("#3C3834"),
            surface_dim: color("#11100F"),
        },
    }
}
