use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn eldritch(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#212337"),
            base01: color("#323449"),
            base02: color("#323449"),
            base03: color("#7081d0"),
            base04: color("#a48cf2"),
            base05: color("#ebfafa"),
            base06: color("#ebfafa"),
            base07: color("#a48cf2"),
            base08: color("#f16c75"),
            base09: color("#f7c67f"),
            base0a: color("#f1fc79"),
            base0b: color("#37f499"),
            base0c: color("#04d1f9"),
            base0d: color("#a48cf2"),
            base0e: color("#f265b5"),
            base0f: color("#f7c67f"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#212337"),
            on_surface: color("#ebfafa"),
            surface_variant: color("#2a2c40"),
            on_surface_variant: color("#7081d0"),
            surface_container_highest: color("#3d4060"),
            surface_container_high: color("#373a54"),
            surface_container: color("#323449"),
            surface_container_low: color("#2a2c40"),
            surface_container_lowest: color("#212337"),
            inverse_surface: color("#ebfafa"),
            inverse_on_surface: color("#212337"),
            surface_tint: color("#37f499"),
            primary: color("#37f499"),
            on_primary: color("#212337"),
            primary_container: color("#323449"),
            on_primary_container: color("#37f499"),
            secondary: color("#04d1f9"),
            on_secondary: color("#212337"),
            secondary_container: color("#323449"),
            on_secondary_container: color("#04d1f9"),
            tertiary: color("#a48cf2"),
            on_tertiary: color("#212337"),
            tertiary_container: color("#323449"),
            on_tertiary_container: color("#a48cf2"),
            error: color("#f16c75"),
            on_error: color("#212337"),
            error_container: color("#323449"),
            on_error_container: color("#f16c75"),
            outline: color("#7081d0"),
            outline_variant: color("#3d4060"),
            background: color("#212337"),
            on_background: color("#ebfafa"),
            inverse_primary: color("#37f499"),
            primary_fixed: color("#37f499"),
            primary_fixed_dim: color("#04d1f9"),
            on_primary_fixed: color("#212337"),
            on_primary_fixed_variant: color("#ebfafa"),
            secondary_fixed: color("#04d1f9"),
            secondary_fixed_dim: color("#7081d0"),
            on_secondary_fixed: color("#212337"),
            on_secondary_fixed_variant: color("#ebfafa"),
            tertiary_fixed: color("#a48cf2"),
            tertiary_fixed_dim: color("#f265b5"),
            on_tertiary_fixed: color("#212337"),
            on_tertiary_fixed_variant: color("#ebfafa"),
            scrim: color("#212337"),
            shadow: color("#212337"),
            source_color: color("#37f499"),
            surface_bright: color("#3d4060"),
            surface_dim: color("#212337"),
        },
    }
}
