use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn ethereal(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#060B1E"),
            base01: color("#0e1530"),
            base02: color("#3C486D"),
            base03: color("#6d7db6"),
            base04: color("#a3bfd1"),
            base05: color("#ffcead"),
            base06: color("#dfeaf0"),
            base07: color("#c2c4f0"),
            base08: color("#ED5B5A"),
            base09: color("#F99957"),
            base0a: color("#E9BB4F"),
            base0b: color("#92a593"),
            base0c: color("#a3bfd1"),
            base0d: color("#7d82d9"),
            base0e: color("#c89dc1"),
            base0f: color("#faaaa9"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#060B1E"),
            on_surface: color("#ffcead"),
            surface_variant: color("#0e1530"),
            on_surface_variant: color("#a3bfd1"),
            surface_container_highest: color("#3C486D"),
            surface_container_high: color("#2c3556"),
            surface_container: color("#1c2342"),
            surface_container_low: color("#0e1530"),
            surface_container_lowest: color("#060B1E"),
            inverse_surface: color("#ffcead"),
            inverse_on_surface: color("#060B1E"),
            surface_tint: color("#7d82d9"),
            primary: color("#7d82d9"),
            on_primary: color("#060B1E"),
            primary_container: color("#1c2342"),
            on_primary_container: color("#7d82d9"),
            secondary: color("#ffcead"),
            on_secondary: color("#060B1E"),
            secondary_container: color("#1c2342"),
            on_secondary_container: color("#ffcead"),
            tertiary: color("#c89dc1"),
            on_tertiary: color("#060B1E"),
            tertiary_container: color("#1c2342"),
            on_tertiary_container: color("#c89dc1"),
            error: color("#ED5B5A"),
            on_error: color("#060B1E"),
            error_container: color("#1c2342"),
            on_error_container: color("#ED5B5A"),
            outline: color("#6d7db6"),
            outline_variant: color("#3C486D"),
            background: color("#060B1E"),
            on_background: color("#ffcead"),
            inverse_primary: color("#7d82d9"),
            primary_fixed: color("#7d82d9"),
            primary_fixed_dim: color("#c2c4f0"),
            on_primary_fixed: color("#060B1E"),
            on_primary_fixed_variant: color("#ffcead"),
            secondary_fixed: color("#ffcead"),
            secondary_fixed_dim: color("#faaaa9"),
            on_secondary_fixed: color("#060B1E"),
            on_secondary_fixed_variant: color("#060B1E"),
            tertiary_fixed: color("#c89dc1"),
            tertiary_fixed_dim: color("#ead7e7"),
            on_tertiary_fixed: color("#060B1E"),
            on_tertiary_fixed_variant: color("#060B1E"),
            scrim: color("#060B1E"),
            shadow: color("#060B1E"),
            source_color: color("#7d82d9"),
            surface_bright: color("#3C486D"),
            surface_dim: color("#060B1E"),
        },
    }
}
