use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn everforest_dark_soft(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#293136"),
            base01: color("#333C43"),
            base02: color("#3A464C"),
            base03: color("#434F55"),
            base04: color("#4D5960"),
            base05: color("#D3C6AA"),
            base06: color("#9DA9A0"),
            base07: color("#D3C6AA"),
            base08: color("#E67E80"),
            base09: color("#E69875"),
            base0a: color("#DBBC7F"),
            base0b: color("#A7C080"),
            base0c: color("#83C092"),
            base0d: color("#7FBBB3"),
            base0e: color("#D699B6"),
            base0f: color("#E67E80"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#293136"),
            on_surface: color("#D3C6AA"),
            surface_variant: color("#3A464C"),
            on_surface_variant: color("#9DA9A0"),
            surface_container_highest: color("#4D5960"),
            surface_container_high: color("#434F55"),
            surface_container: color("#3A464C"),
            surface_container_low: color("#333C43"),
            surface_container_lowest: color("#293136"),
            inverse_surface: color("#D3C6AA"),
            inverse_on_surface: color("#293136"),
            surface_tint: color("#7FBBB3"),
            primary: color("#A7C080"),
            on_primary: color("#293136"),
            primary_container: color("#48584E"),
            on_primary_container: color("#A7C080"),
            secondary: color("#7FBBB3"),
            on_secondary: color("#293136"),
            secondary_container: color("#3F5865"),
            on_secondary_container: color("#7FBBB3"),
            tertiary: color("#83C092"),
            on_tertiary: color("#293136"),
            tertiary_container: color("#48584E"),
            on_tertiary_container: color("#83C092"),
            error: color("#E67E80"),
            on_error: color("#293136"),
            error_container: color("#59464C"),
            on_error_container: color("#E67E80"),
            outline: color("#7A8478"),
            outline_variant: color("#434F55"),
            background: color("#293136"),
            on_background: color("#D3C6AA"),
            inverse_primary: color("#48584E"),
            primary_fixed: color("#A7C080"),
            primary_fixed_dim: color("#A7C080"),
            on_primary_fixed: color("#293136"),
            on_primary_fixed_variant: color("#293136"),
            secondary_fixed: color("#7FBBB3"),
            secondary_fixed_dim: color("#7FBBB3"),
            on_secondary_fixed: color("#293136"),
            on_secondary_fixed_variant: color("#293136"),
            tertiary_fixed: color("#83C092"),
            tertiary_fixed_dim: color("#83C092"),
            on_tertiary_fixed: color("#293136"),
            on_tertiary_fixed_variant: color("#293136"),
            scrim: color("#293136"),
            shadow: color("#293136"),
            source_color: color("#A7C080"),
            surface_bright: color("#4D5960"),
            surface_dim: color("#293136"),
        },
    }
}
