use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn everforest_light_medium(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: false,
        mode: "light".to_string(),
        base16: Base16 {
            base00: color("#FDF6E3"),
            base01: color("#F4F0D9"),
            base02: color("#EFEBD4"),
            base03: color("#E6E2CC"),
            base04: color("#E0DCC7"),
            base05: color("#5C6A72"),
            base06: color("#829181"),
            base07: color("#5C6A72"),
            base08: color("#F85552"),
            base09: color("#F57D26"),
            base0a: color("#DFA000"),
            base0b: color("#8DA101"),
            base0c: color("#35A77C"),
            base0d: color("#3A94C5"),
            base0e: color("#DF69BA"),
            base0f: color("#F85552"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#FDF6E3"),
            on_surface: color("#5C6A72"),
            surface_variant: color("#EFEBD4"),
            on_surface_variant: color("#829181"),
            surface_container_highest: color("#E6E2CC"),
            surface_container_high: color("#EFEBD4"),
            surface_container: color("#F4F0D9"),
            surface_container_low: color("#FDF6E3"),
            surface_container_lowest: color("#FDF6E3"),
            inverse_surface: color("#5C6A72"),
            inverse_on_surface: color("#FDF6E3"),
            surface_tint: color("#3A94C5"),
            primary: color("#8DA101"),
            on_primary: color("#FDF6E3"),
            primary_container: color("#F0F1D2"),
            on_primary_container: color("#8DA101"),
            secondary: color("#3A94C5"),
            on_secondary: color("#FDF6E3"),
            secondary_container: color("#E9F0E9"),
            on_secondary_container: color("#3A94C5"),
            tertiary: color("#35A77C"),
            on_tertiary: color("#FDF6E3"),
            tertiary_container: color("#F0F1D2"),
            on_tertiary_container: color("#35A77C"),
            error: color("#F85552"),
            on_error: color("#FDF6E3"),
            error_container: color("#FDE3DA"),
            on_error_container: color("#F85552"),
            outline: color("#A6B0A0"),
            outline_variant: color("#E6E2CC"),
            background: color("#FDF6E3"),
            on_background: color("#5C6A72"),
            inverse_primary: color("#F0F1D2"),
            primary_fixed: color("#8DA101"),
            primary_fixed_dim: color("#8DA101"),
            on_primary_fixed: color("#FDF6E3"),
            on_primary_fixed_variant: color("#FDF6E3"),
            secondary_fixed: color("#3A94C5"),
            secondary_fixed_dim: color("#3A94C5"),
            on_secondary_fixed: color("#FDF6E3"),
            on_secondary_fixed_variant: color("#FDF6E3"),
            tertiary_fixed: color("#35A77C"),
            tertiary_fixed_dim: color("#35A77C"),
            on_tertiary_fixed: color("#FDF6E3"),
            on_tertiary_fixed_variant: color("#FDF6E3"),
            scrim: color("#5C6A72"),
            shadow: color("#5C6A72"),
            source_color: color("#8DA101"),
            surface_bright: color("#FDF6E3"),
            surface_dim: color("#EFEBD4"),
        },
    }
}
