use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn everforest_light_hard(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: false,
        mode: "light".to_string(),
        base16: Base16 {
            base00: color("#FFFBEF"),
            base01: color("#F8F5E4"),
            base02: color("#F2EFDF"),
            base03: color("#EDEADA"),
            base04: color("#E8E5D5"),
            base05: color("#5C6A72"),
            base06: color("#829181"),
            base07: color("#5C6A72"),
            base08: color("#F85552"),
            base09: color("#F57D26"),
            base0a: color("#DFA000"),
            base0b: color("#8DA101"),
            base0c: color("#35A77C"),
            base0d: color("#3A94C5"),
            base0e: color("#DF69BA"),
            base0f: color("#F85552"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#FFFBEF"),
            on_surface: color("#5C6A72"),
            surface_variant: color("#F2EFDF"),
            on_surface_variant: color("#829181"),
            surface_container_highest: color("#EDEADA"),
            surface_container_high: color("#F2EFDF"),
            surface_container: color("#F8F5E4"),
            surface_container_low: color("#FFFBEF"),
            surface_container_lowest: color("#FFFBEF"),
            inverse_surface: color("#5C6A72"),
            inverse_on_surface: color("#FFFBEF"),
            surface_tint: color("#3A94C5"),
            primary: color("#8DA101"),
            on_primary: color("#FFFBEF"),
            primary_container: color("#F3F5D9"),
            on_primary_container: color("#8DA101"),
            secondary: color("#3A94C5"),
            on_secondary: color("#FFFBEF"),
            secondary_container: color("#ECF5ED"),
            on_secondary_container: color("#3A94C5"),
            tertiary: color("#35A77C"),
            on_tertiary: color("#FFFBEF"),
            tertiary_container: color("#F3F5D9"),
            on_tertiary_container: color("#35A77C"),
            error: color("#F85552"),
            on_error: color("#FFFBEF"),
            error_container: color("#FFE7DE"),
            on_error_container: color("#F85552"),
            outline: color("#A6B0A0"),
            outline_variant: color("#EDEADA"),
            background: color("#FFFBEF"),
            on_background: color("#5C6A72"),
            inverse_primary: color("#F3F5D9"),
            primary_fixed: color("#8DA101"),
            primary_fixed_dim: color("#8DA101"),
            on_primary_fixed: color("#FFFBEF"),
            on_primary_fixed_variant: color("#FFFBEF"),
            secondary_fixed: color("#3A94C5"),
            secondary_fixed_dim: color("#3A94C5"),
            on_secondary_fixed: color("#FFFBEF"),
            on_secondary_fixed_variant: color("#FFFBEF"),
            tertiary_fixed: color("#35A77C"),
            tertiary_fixed_dim: color("#35A77C"),
            on_tertiary_fixed: color("#FFFBEF"),
            on_tertiary_fixed_variant: color("#FFFBEF"),
            scrim: color("#5C6A72"),
            shadow: color("#5C6A72"),
            source_color: color("#8DA101"),
            surface_bright: color("#FFFBEF"),
            surface_dim: color("#F2EFDF"),
        },
    }
}
