use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn everforest_light_soft(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: false,
        mode: "light".to_string(),
        base16: Base16 {
            base00: color("#F3EAD3"),
            base01: color("#EAE4CA"),
            base02: color("#E5DFC5"),
            base03: color("#DDD8BE"),
            base04: color("#D8D3BA"),
            base05: color("#5C6A72"),
            base06: color("#829181"),
            base07: color("#5C6A72"),
            base08: color("#F85552"),
            base09: color("#F57D26"),
            base0a: color("#DFA000"),
            base0b: color("#8DA101"),
            base0c: color("#35A77C"),
            base0d: color("#3A94C5"),
            base0e: color("#DF69BA"),
            base0f: color("#F85552"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#F3EAD3"),
            on_surface: color("#5C6A72"),
            surface_variant: color("#E5DFC5"),
            on_surface_variant: color("#829181"),
            surface_container_highest: color("#DDD8BE"),
            surface_container_high: color("#E5DFC5"),
            surface_container: color("#EAE4CA"),
            surface_container_low: color("#F3EAD3"),
            surface_container_lowest: color("#F3EAD3"),
            inverse_surface: color("#5C6A72"),
            inverse_on_surface: color("#F3EAD3"),
            surface_tint: color("#3A94C5"),
            primary: color("#8DA101"),
            on_primary: color("#F3EAD3"),
            primary_container: color("#E5E6C5"),
            on_primary_container: color("#8DA101"),
            secondary: color("#3A94C5"),
            on_secondary: color("#F3EAD3"),
            secondary_container: color("#E1E7DD"),
            on_secondary_container: color("#3A94C5"),
            tertiary: color("#35A77C"),
            on_tertiary: color("#F3EAD3"),
            tertiary_container: color("#E5E6C5"),
            on_tertiary_container: color("#35A77C"),
            error: color("#F85552"),
            on_error: color("#F3EAD3"),
            error_container: color("#FADBD0"),
            on_error_container: color("#F85552"),
            outline: color("#A6B0A0"),
            outline_variant: color("#DDD8BE"),
            background: color("#F3EAD3"),
            on_background: color("#5C6A72"),
            inverse_primary: color("#E5E6C5"),
            primary_fixed: color("#8DA101"),
            primary_fixed_dim: color("#8DA101"),
            on_primary_fixed: color("#F3EAD3"),
            on_primary_fixed_variant: color("#F3EAD3"),
            secondary_fixed: color("#3A94C5"),
            secondary_fixed_dim: color("#3A94C5"),
            on_secondary_fixed: color("#F3EAD3"),
            on_secondary_fixed_variant: color("#F3EAD3"),
            tertiary_fixed: color("#35A77C"),
            tertiary_fixed_dim: color("#35A77C"),
            on_tertiary_fixed: color("#F3EAD3"),
            on_tertiary_fixed_variant: color("#F3EAD3"),
            scrim: color("#5C6A72"),
            shadow: color("#5C6A72"),
            source_color: color("#8DA101"),
            surface_bright: color("#F3EAD3"),
            surface_dim: color("#E5DFC5"),
        },
    }
}
