use crate::json_struct::{Base16, Colors, MShell, MatugenTheme, Palettes, color};

/// `Flexoki` — dark theme imported from the community palette
/// collection (noctalia format). M3 roles map from the palette's `m*`
/// keys; container/fixed shades are derived luminance blends; the base16
/// accent ramp maps from the terminal ANSI set.
pub fn flexoki(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#100F0F"),
            base01: color("#0E0D0D"),
            base02: color("#1C1B1A"),
            base03: color("#2A2928"),
            base04: color("#585653"),
            base05: color("#CECDC3"),
            base06: color("#878580"),
            base07: color("#5D5C58"),
            base08: color("#D14D41"),
            base09: color("#D0782B"),
            base0a: color("#D0A215"),
            base0b: color("#879A39"),
            base0c: color("#3AA99F"),
            base0d: color("#4385BE"),
            base0e: color("#8B7EC8"),
            base0f: color("#8D3730"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#100F0F"),
            on_surface: color("#CECDC3"),
            surface_variant: color("#1C1B1A"),
            on_surface_variant: color("#878580"),
            surface_container_highest: color("#3C3B3A"),
            surface_container_high: color("#2A2928"),
            surface_container: color("#1C1B1A"),
            surface_container_low: color("#0E0D0D"),
            surface_container_lowest: color("#0A0A0A"),
            inverse_surface: color("#CECDC3"),
            inverse_on_surface: color("#1C1B1A"),
            surface_tint: color("#879A39"),
            primary: color("#879A39"),
            on_primary: color("#1A1E0C"),
            primary_container: color("#31361B"),
            on_primary_container: color("#93A44D"),
            secondary: color("#4385BE"),
            on_secondary: color("#101A24"),
            secondary_container: color("#1E3040"),
            on_secondary_container: color("#5691C4"),
            tertiary: color("#8B7EC8"),
            on_tertiary: color("#1A1623"),
            tertiary_container: color("#322E43"),
            on_tertiary_container: color("#978BCE"),
            error: color("#D14D41"),
            on_error: color("#261312"),
            error_container: color("#46201D"),
            on_error_container: color("#D65F54"),
            outline: color("#282726"),
            outline_variant: color("#1D1C1C"),
            background: color("#100F0F"),
            on_background: color("#CECDC3"),
            inverse_primary: color("#31361B"),
            primary_fixed: color("#879A39"),
            primary_fixed_dim: color("#778832"),
            on_primary_fixed: color("#1A1E0C"),
            on_primary_fixed_variant: color("#1A1E0C"),
            secondary_fixed: color("#4385BE"),
            secondary_fixed_dim: color("#3B75A7"),
            on_secondary_fixed: color("#101A24"),
            on_secondary_fixed_variant: color("#101A24"),
            tertiary_fixed: color("#8B7EC8"),
            tertiary_fixed_dim: color("#7A6FB0"),
            on_tertiary_fixed: color("#1A1623"),
            on_tertiary_fixed_variant: color("#1A1623"),
            scrim: color("#100F0F"),
            shadow: color("#100F0F"),
            source_color: color("#879A39"),
            surface_bright: color("#3C3B3A"),
            surface_dim: color("#0A0A0A"),
        },
    }
}
