use crate::json_struct::{Base16, Colors, MShell, MatugenTheme, Palettes, color};

/// `GitHub Dark` — dark theme imported from the community palette
/// collection (noctalia format). M3 roles map from the palette's `m*`
/// keys; container/fixed shades are derived luminance blends; the base16
/// accent ramp maps from the terminal ANSI set.
pub fn github_dark(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#010409"),
            base01: color("#010308"),
            base02: color("#161B22"),
            base03: color("#24292F"),
            base04: color("#5E656E"),
            base05: color("#C9D1D9"),
            base06: color("#8B949E"),
            base07: color("#5B626A"),
            base08: color("#FF7B72"),
            base09: color("#E88A4A"),
            base0a: color("#D29922"),
            base0b: color("#3FB950"),
            base0c: color("#39C5CF"),
            base0d: color("#58A6FF"),
            base0e: color("#BC8CFF"),
            base0f: color("#A6514D"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#010409"),
            on_surface: color("#C9D1D9"),
            surface_variant: color("#161B22"),
            on_surface_variant: color("#8B949E"),
            surface_container_highest: color("#373B41"),
            surface_container_high: color("#24292F"),
            surface_container: color("#161B22"),
            surface_container_low: color("#010308"),
            surface_container_lowest: color("#010306"),
            inverse_surface: color("#C9D1D9"),
            inverse_on_surface: color("#161B22"),
            surface_tint: color("#58A6FF"),
            primary: color("#58A6FF"),
            on_primary: color("#010409"),
            primary_container: color("#19314E"),
            on_primary_container: color("#69AFFF"),
            secondary: color("#BC8CFF"),
            on_secondary: color("#010409"),
            secondary_container: color("#352A4E"),
            on_secondary_container: color("#C398FF"),
            tertiary: color("#BC8CFF"),
            on_tertiary: color("#010409"),
            tertiary_container: color("#352A4E"),
            on_tertiary_container: color("#C398FF"),
            error: color("#F85149"),
            on_error: color("#010409"),
            error_container: color("#461A1B"),
            on_error_container: color("#F9625B"),
            outline: color("#30363D"),
            outline_variant: color("#1B2026"),
            background: color("#010409"),
            on_background: color("#C9D1D9"),
            inverse_primary: color("#19314E"),
            primary_fixed: color("#58A6FF"),
            primary_fixed_dim: color("#4D92E0"),
            on_primary_fixed: color("#010409"),
            on_primary_fixed_variant: color("#010409"),
            secondary_fixed: color("#BC8CFF"),
            secondary_fixed_dim: color("#A57BE0"),
            on_secondary_fixed: color("#010409"),
            on_secondary_fixed_variant: color("#010409"),
            tertiary_fixed: color("#BC8CFF"),
            tertiary_fixed_dim: color("#A57BE0"),
            on_tertiary_fixed: color("#010409"),
            on_tertiary_fixed_variant: color("#010409"),
            scrim: color("#010409"),
            shadow: color("#010409"),
            source_color: color("#58A6FF"),
            surface_bright: color("#373B41"),
            surface_dim: color("#010306"),
        },
    }
}
