use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn gruvbox_light_hard(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: false,
        mode: "light".to_string(),
        base16: Base16 {
            base00: color("#F9F5D7"),
            base01: color("#EBDBB2"),
            base02: color("#D5C4A1"),
            base03: color("#BDAE93"),
            base04: color("#A89984"),
            base05: color("#3C3836"),
            base06: color("#504945"),
            base07: color("#282828"),
            base08: color("#9D0006"),
            base09: color("#AF3A03"),
            base0a: color("#B57614"),
            base0b: color("#79740E"),
            base0c: color("#427B58"),
            base0d: color("#076678"),
            base0e: color("#8F3F71"),
            base0f: color("#9D0006"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#F9F5D7"),
            on_surface: color("#3C3836"),
            surface_variant: color("#EBDBB2"),
            on_surface_variant: color("#504945"),
            surface_container_highest: color("#BDAE93"),
            surface_container_high: color("#D5C4A1"),
            surface_container: color("#EBDBB2"),
            surface_container_low: color("#F9F5D7"),
            surface_container_lowest: color("#F9F5D7"),
            inverse_surface: color("#3C3836"),
            inverse_on_surface: color("#F9F5D7"),
            surface_tint: color("#076678"),
            primary: color("#076678"),
            on_primary: color("#F9F5D7"),
            primary_container: color("#EBDBB2"),
            on_primary_container: color("#076678"),
            secondary: color("#79740E"),
            on_secondary: color("#F9F5D7"),
            secondary_container: color("#EBDBB2"),
            on_secondary_container: color("#79740E"),
            tertiary: color("#427B58"),
            on_tertiary: color("#F9F5D7"),
            tertiary_container: color("#EBDBB2"),
            on_tertiary_container: color("#427B58"),
            error: color("#9D0006"),
            on_error: color("#F9F5D7"),
            error_container: color("#EBDBB2"),
            on_error_container: color("#9D0006"),
            outline: color("#928374"),
            outline_variant: color("#D5C4A1"),
            background: color("#F9F5D7"),
            on_background: color("#3C3836"),
            inverse_primary: color("#EBDBB2"),
            primary_fixed: color("#076678"),
            primary_fixed_dim: color("#076678"),
            on_primary_fixed: color("#F9F5D7"),
            on_primary_fixed_variant: color("#F9F5D7"),
            secondary_fixed: color("#79740E"),
            secondary_fixed_dim: color("#79740E"),
            on_secondary_fixed: color("#F9F5D7"),
            on_secondary_fixed_variant: color("#F9F5D7"),
            tertiary_fixed: color("#427B58"),
            tertiary_fixed_dim: color("#427B58"),
            on_tertiary_fixed: color("#F9F5D7"),
            on_tertiary_fixed_variant: color("#F9F5D7"),
            scrim: color("#3C3836"),
            shadow: color("#3C3836"),
            source_color: color("#076678"),
            surface_bright: color("#F9F5D7"),
            surface_dim: color("#EBDBB2"),
        },
    }
}
