use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn gruvbox_dark_hard(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#1D2021"),
            base01: color("#3C3836"),
            base02: color("#504945"),
            base03: color("#665C54"),
            base04: color("#7C6F64"),
            base05: color("#EBDBB2"),
            base06: color("#D5C4A1"),
            base07: color("#FBF1C7"),
            base08: color("#FB4934"),
            base09: color("#FE8019"),
            base0a: color("#FABD2F"),
            base0b: color("#B8BB26"),
            base0c: color("#8EC07C"),
            base0d: color("#83A598"),
            base0e: color("#D3869B"),
            base0f: color("#FB4934"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#1D2021"),
            on_surface: color("#EBDBB2"),
            surface_variant: color("#3C3836"),
            on_surface_variant: color("#D5C4A1"),
            surface_container_highest: color("#7C6F64"),
            surface_container_high: color("#665C54"),
            surface_container: color("#504945"),
            surface_container_low: color("#3C3836"),
            surface_container_lowest: color("#1D2021"),
            inverse_surface: color("#EBDBB2"),
            inverse_on_surface: color("#1D2021"),
            surface_tint: color("#83A598"),
            primary: color("#83A598"),
            on_primary: color("#1D2021"),
            primary_container: color("#504945"),
            on_primary_container: color("#83A598"),
            secondary: color("#B8BB26"),
            on_secondary: color("#1D2021"),
            secondary_container: color("#504945"),
            on_secondary_container: color("#B8BB26"),
            tertiary: color("#8EC07C"),
            on_tertiary: color("#1D2021"),
            tertiary_container: color("#504945"),
            on_tertiary_container: color("#8EC07C"),
            error: color("#FB4934"),
            on_error: color("#1D2021"),
            error_container: color("#504945"),
            on_error_container: color("#FB4934"),
            outline: color("#928374"),
            outline_variant: color("#504945"),
            background: color("#1D2021"),
            on_background: color("#EBDBB2"),
            inverse_primary: color("#504945"),
            primary_fixed: color("#83A598"),
            primary_fixed_dim: color("#83A598"),
            on_primary_fixed: color("#1D2021"),
            on_primary_fixed_variant: color("#1D2021"),
            secondary_fixed: color("#B8BB26"),
            secondary_fixed_dim: color("#B8BB26"),
            on_secondary_fixed: color("#1D2021"),
            on_secondary_fixed_variant: color("#1D2021"),
            tertiary_fixed: color("#8EC07C"),
            tertiary_fixed_dim: color("#8EC07C"),
            on_tertiary_fixed: color("#1D2021"),
            on_tertiary_fixed_variant: color("#1D2021"),
            scrim: color("#1D2021"),
            shadow: color("#1D2021"),
            source_color: color("#83A598"),
            surface_bright: color("#7C6F64"),
            surface_dim: color("#1D2021"),
        },
    }
}
