use crate::json_struct::{Base16, Colors, MShell, MatugenTheme, Palettes, color};

/// `Gruvbox Material` — dark theme imported from the community palette
/// collection (noctalia format). M3 roles map from the palette's `m*`
/// keys; container/fixed shades are derived luminance blends; the base16
/// accent ramp maps from the terminal ANSI set.
pub fn gruvbox_material(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#32302F"),
            base01: color("#2A2928"),
            base02: color("#3C3836"),
            base03: color("#484442"),
            base04: color("#92846E"),
            base05: color("#DDC7A1"),
            base06: color("#D4BE98"),
            base07: color("#9B8C73"),
            base08: color("#EA6962"),
            base09: color("#E1885C"),
            base0a: color("#D8A657"),
            base0b: color("#A9B665"),
            base0c: color("#89B482"),
            base0d: color("#7DAEA3"),
            base0e: color("#D3869B"),
            base0f: color("#AA5550"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#32302F"),
            on_surface: color("#DDC7A1"),
            surface_variant: color("#3C3836"),
            on_surface_variant: color("#D4BE98"),
            surface_container_highest: color("#575452"),
            surface_container_high: color("#484442"),
            surface_container: color("#3C3836"),
            surface_container_low: color("#2A2928"),
            surface_container_lowest: color("#201F1F"),
            inverse_surface: color("#DDC7A1"),
            inverse_on_surface: color("#3C3836"),
            surface_tint: color("#A9B665"),
            primary: color("#A9B665"),
            on_primary: color("#32302F"),
            primary_container: color("#53563E"),
            on_primary_container: color("#B2BD74"),
            secondary: color("#E78A4E"),
            on_secondary: color("#32302F"),
            secondary_container: color("#654938"),
            on_secondary_container: color("#E99660"),
            tertiary: color("#89B482"),
            on_tertiary: color("#32302F"),
            tertiary_container: color("#4A5546"),
            on_tertiary_container: color("#95BC8E"),
            error: color("#EA6962"),
            on_error: color("#32302F"),
            error_container: color("#66403D"),
            on_error_container: color("#EC7872"),
            outline: color("#504945"),
            outline_variant: color("#423E3B"),
            background: color("#32302F"),
            on_background: color("#DDC7A1"),
            inverse_primary: color("#53563E"),
            primary_fixed: color("#A9B665"),
            primary_fixed_dim: color("#95A059"),
            on_primary_fixed: color("#32302F"),
            on_primary_fixed_variant: color("#32302F"),
            secondary_fixed: color("#E78A4E"),
            secondary_fixed_dim: color("#CB7945"),
            on_secondary_fixed: color("#32302F"),
            on_secondary_fixed_variant: color("#32302F"),
            tertiary_fixed: color("#89B482"),
            tertiary_fixed_dim: color("#799E72"),
            on_tertiary_fixed: color("#32302F"),
            on_tertiary_fixed_variant: color("#32302F"),
            scrim: color("#282828"),
            shadow: color("#282828"),
            source_color: color("#A9B665"),
            surface_bright: color("#575452"),
            surface_dim: color("#201F1F"),
        },
    }
}
