use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn hackerman(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#0B0C16"),
            base01: color("#6a6e95"),
            base02: color("#0B0C16"),
            base03: color("#6a6e95"),
            base04: color("#85E1FB"),
            base05: color("#ddf7ff"),
            base06: color("#ddf7ff"),
            base07: color("#85E1FB"),
            base08: color("#50f872"),
            base09: color("#85ff9d"),
            base0a: color("#50f7d4"),
            base0b: color("#4fe88f"),
            base0c: color("#7cf8f7"),
            base0d: color("#829dd4"),
            base0e: color("#86a7df"),
            base0f: color("#a4ffec"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#0B0C16"),
            on_surface: color("#ddf7ff"),
            surface_variant: color("#13152a"),
            on_surface_variant: color("#85E1FB"),
            surface_container_highest: color("#1f2245"),
            surface_container_high: color("#1a1c39"),
            surface_container: color("#16182f"),
            surface_container_low: color("#13152a"),
            surface_container_lowest: color("#0B0C16"),
            inverse_surface: color("#ddf7ff"),
            inverse_on_surface: color("#0B0C16"),
            surface_tint: color("#4fe88f"),
            primary: color("#4fe88f"),
            on_primary: color("#0B0C16"),
            primary_container: color("#1a1c39"),
            on_primary_container: color("#4fe88f"),
            secondary: color("#7cf8f7"),
            on_secondary: color("#0B0C16"),
            secondary_container: color("#1a1c39"),
            on_secondary_container: color("#7cf8f7"),
            tertiary: color("#829dd4"),
            on_tertiary: color("#0B0C16"),
            tertiary_container: color("#1a1c39"),
            on_tertiary_container: color("#829dd4"),
            error: color("#50f872"),
            on_error: color("#0B0C16"),
            error_container: color("#1a1c39"),
            on_error_container: color("#50f872"),
            outline: color("#6a6e95"),
            outline_variant: color("#1f2245"),
            background: color("#0B0C16"),
            on_background: color("#ddf7ff"),
            inverse_primary: color("#4fe88f"),
            primary_fixed: color("#4fe88f"),
            primary_fixed_dim: color("#85ff9d"),
            on_primary_fixed: color("#0B0C16"),
            on_primary_fixed_variant: color("#ddf7ff"),
            secondary_fixed: color("#7cf8f7"),
            secondary_fixed_dim: color("#a4ffec"),
            on_secondary_fixed: color("#0B0C16"),
            on_secondary_fixed_variant: color("#ddf7ff"),
            tertiary_fixed: color("#829dd4"),
            tertiary_fixed_dim: color("#86a7df"),
            on_tertiary_fixed: color("#0B0C16"),
            on_tertiary_fixed_variant: color("#ddf7ff"),
            scrim: color("#0B0C16"),
            shadow: color("#0B0C16"),
            source_color: color("#4fe88f"),
            surface_bright: color("#1f2245"),
            surface_dim: color("#0B0C16"),
        },
    }
}
