use crate::json_struct::{Base16, Colors, MShell, MatugenTheme, Palettes, color};

/// `Horizon` — dark theme imported from the community palette
/// collection (noctalia format). M3 roles map from the palette's `m*`
/// keys; container/fixed shades are derived luminance blends; the base16
/// accent ramp maps from the terminal ANSI set.
pub fn horizon(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#1A1C23"),
            base01: color("#16181E"),
            base02: color("#232530"),
            base03: color("#30323C"),
            base04: color("#4D5068"),
            base05: color("#FDF0ED"),
            base06: color("#6C6F93"),
            base07: color("#4F526C"),
            base08: color("#E95678"),
            base09: color("#F28686"),
            base0a: color("#FAB795"),
            base0b: color("#29D398"),
            base0c: color("#59E1E3"),
            base0d: color("#26BBD9"),
            base0e: color("#EE64AC"),
            base0f: color("#A1425A"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#1A1C23"),
            on_surface: color("#FDF0ED"),
            surface_variant: color("#232530"),
            on_surface_variant: color("#6C6F93"),
            surface_container_highest: color("#42444D"),
            surface_container_high: color("#30323C"),
            surface_container: color("#232530"),
            surface_container_low: color("#16181E"),
            surface_container_lowest: color("#111217"),
            inverse_surface: color("#FDF0ED"),
            inverse_on_surface: color("#232530"),
            surface_tint: color("#25B2BC"),
            primary: color("#25B2BC"),
            on_primary: color("#16161C"),
            primary_container: color("#1D464E"),
            on_primary_container: color("#3BBAC3"),
            secondary: color("#B877DB"),
            on_secondary: color("#16161C"),
            secondary_container: color("#463557"),
            on_secondary_container: color("#BF85DF"),
            tertiary: color("#FAB795"),
            on_tertiary: color("#16161C"),
            tertiary_container: color("#594743"),
            on_tertiary_container: color("#FABEA0"),
            error: color("#E95678"),
            on_error: color("#FDF0ED"),
            error_container: color("#542C3B"),
            on_error_container: color("#EB6786"),
            outline: color("#2E303E"),
            outline_variant: color("#252732"),
            background: color("#1A1C23"),
            on_background: color("#FDF0ED"),
            inverse_primary: color("#1D464E"),
            primary_fixed: color("#25B2BC"),
            primary_fixed_dim: color("#219DA5"),
            on_primary_fixed: color("#16161C"),
            on_primary_fixed_variant: color("#16161C"),
            secondary_fixed: color("#B877DB"),
            secondary_fixed_dim: color("#A269C1"),
            on_secondary_fixed: color("#16161C"),
            on_secondary_fixed_variant: color("#16161C"),
            tertiary_fixed: color("#FAB795"),
            tertiary_fixed_dim: color("#DCA183"),
            on_tertiary_fixed: color("#16161C"),
            on_tertiary_fixed_variant: color("#16161C"),
            scrim: color("#16161C"),
            shadow: color("#16161C"),
            source_color: color("#25B2BC"),
            surface_bright: color("#42444D"),
            surface_dim: color("#111217"),
        },
    }
}
