use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn inky_pinky(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#13131D"),
            base01: color("#1d1d2a"),
            base02: color("#434353"),
            base03: color("#7c7ca8"),
            base04: color("#a1a2a7"),
            base05: color("#c8c8c8"),
            base06: color("#c8c8c8"),
            base07: color("#bcbcd4"),
            base08: color("#EA90A8"),
            base09: color("#D18BA2"),
            base0a: color("#f6bfce"),
            base0b: color("#a6b2c7"),
            base0c: color("#919ab7"),
            base0d: color("#7c7ca8"),
            base0e: color("#9f859f"),
            base0f: color("#bfadbf"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#13131D"),
            on_surface: color("#c8c8c8"),
            surface_variant: color("#1d1d2a"),
            on_surface_variant: color("#a1a2a7"),
            surface_container_highest: color("#434353"),
            surface_container_high: color("#363645"),
            surface_container: color("#2a2a38"),
            surface_container_low: color("#1d1d2a"),
            surface_container_lowest: color("#13131D"),
            inverse_surface: color("#c8c8c8"),
            inverse_on_surface: color("#13131D"),
            surface_tint: color("#EA90A8"),
            primary: color("#EA90A8"),
            on_primary: color("#13131D"),
            primary_container: color("#2a2a38"),
            on_primary_container: color("#EA90A8"),
            secondary: color("#7c7ca8"),
            on_secondary: color("#13131D"),
            secondary_container: color("#2a2a38"),
            on_secondary_container: color("#7c7ca8"),
            tertiary: color("#9f859f"),
            on_tertiary: color("#13131D"),
            tertiary_container: color("#2a2a38"),
            on_tertiary_container: color("#9f859f"),
            error: color("#EA90A8"),
            on_error: color("#13131D"),
            error_container: color("#2a2a38"),
            on_error_container: color("#EA90A8"),
            outline: color("#7c7ca8"),
            outline_variant: color("#434353"),
            background: color("#13131D"),
            on_background: color("#c8c8c8"),
            inverse_primary: color("#EA90A8"),
            primary_fixed: color("#EA90A8"),
            primary_fixed_dim: color("#f6bfce"),
            on_primary_fixed: color("#13131D"),
            on_primary_fixed_variant: color("#c8c8c8"),
            secondary_fixed: color("#7c7ca8"),
            secondary_fixed_dim: color("#bcbcd4"),
            on_secondary_fixed: color("#13131D"),
            on_secondary_fixed_variant: color("#c8c8c8"),
            tertiary_fixed: color("#9f859f"),
            tertiary_fixed_dim: color("#bfadbf"),
            on_tertiary_fixed: color("#13131D"),
            on_tertiary_fixed_variant: color("#c8c8c8"),
            scrim: color("#13131D"),
            shadow: color("#13131D"),
            source_color: color("#EA90A8"),
            surface_bright: color("#434353"),
            surface_dim: color("#13131D"),
        },
    }
}
