use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn kanagawa_wave(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#1F1F28"),
            base01: color("#16161D"),
            base02: color("#2A2A37"),
            base03: color("#363646"),
            base04: color("#54546D"),
            base05: color("#DCD7BA"),
            base06: color("#C8C093"),
            base07: color("#727169"),
            base08: color("#C34043"),
            base09: color("#FFA066"),
            base0a: color("#E6C384"),
            base0b: color("#98BB6C"),
            base0c: color("#7AA89F"),
            base0d: color("#7E9CD8"),
            base0e: color("#957FB8"),
            base0f: color("#D27E99"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#1F1F28"),
            on_surface: color("#DCD7BA"),
            surface_variant: color("#2A2A37"),
            on_surface_variant: color("#C8C093"),
            surface_container_highest: color("#54546D"),
            surface_container_high: color("#363646"),
            surface_container: color("#2A2A37"),
            surface_container_low: color("#181820"),
            surface_container_lowest: color("#16161D"),
            inverse_surface: color("#DCD7BA"),
            inverse_on_surface: color("#2A2A37"),
            surface_tint: color("#7E9CD8"),
            primary: color("#7E9CD8"),
            on_primary: color("#2A2A37"),
            primary_container: color("#223249"),
            on_primary_container: color("#7FB4CA"),
            secondary: color("#957FB8"),
            on_secondary: color("#2A2A37"),
            secondary_container: color("#2A2A37"),
            on_secondary_container: color("#938AA9"),
            tertiary: color("#7AA89F"),
            on_tertiary: color("#2A2A37"),
            tertiary_container: color("#2A2A37"),
            on_tertiary_container: color("#6A9589"),
            error: color("#E82424"),
            on_error: color("#2A2A37"),
            error_container: color("#43242B"),
            on_error_container: color("#E46876"),
            outline: color("#938AA9"),
            outline_variant: color("#54546D"),
            background: color("#1F1F28"),
            on_background: color("#DCD7BA"),
            inverse_primary: color("#223249"),
            primary_fixed: color("#7E9CD8"),
            primary_fixed_dim: color("#7FB4CA"),
            on_primary_fixed: color("#1F1F28"),
            on_primary_fixed_variant: color("#223249"),
            secondary_fixed: color("#957FB8"),
            secondary_fixed_dim: color("#938AA9"),
            on_secondary_fixed: color("#1F1F28"),
            on_secondary_fixed_variant: color("#223249"),
            tertiary_fixed: color("#7AA89F"),
            tertiary_fixed_dim: color("#6A9589"),
            on_tertiary_fixed: color("#1F1F28"),
            on_tertiary_fixed_variant: color("#223249"),
            scrim: color("#16161D"),
            shadow: color("#16161D"),
            source_color: color("#7E9CD8"),
            surface_bright: color("#54546D"),
            surface_dim: color("#16161D"),
        },
    }
}
