use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn kanagawa_dragon(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#181616"),
            base01: color("#0d0c0c"),
            base02: color("#1D1C19"),
            base03: color("#282727"),
            base04: color("#393836"),
            base05: color("#c5c9c5"),
            base06: color("#C8C093"),
            base07: color("#737c73"),
            base08: color("#c4746e"),
            base09: color("#b6927b"),
            base0a: color("#c4b28a"),
            base0b: color("#8a9a7b"),
            base0c: color("#8ea4a2"),
            base0d: color("#8ba4b0"),
            base0e: color("#8992a7"),
            base0f: color("#a292a3"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#181616"),
            on_surface: color("#c5c9c5"),
            surface_variant: color("#1D1C19"),
            on_surface_variant: color("#C8C093"),
            surface_container_highest: color("#625e5a"),
            surface_container_high: color("#393836"),
            surface_container: color("#282727"),
            surface_container_low: color("#12120f"),
            surface_container_lowest: color("#0d0c0c"),
            inverse_surface: color("#c5c9c5"),
            inverse_on_surface: color("#1D1C19"),
            surface_tint: color("#8ba4b0"),
            primary: color("#8ba4b0"),
            on_primary: color("#1D1C19"),
            primary_container: color("#223249"),
            on_primary_container: color("#7FB4CA"),
            secondary: color("#8992a7"),
            on_secondary: color("#1D1C19"),
            secondary_container: color("#1D1C19"),
            on_secondary_container: color("#949fb5"),
            tertiary: color("#8ea4a2"),
            on_tertiary: color("#1D1C19"),
            tertiary_container: color("#1D1C19"),
            on_tertiary_container: color("#8ea4a2"),
            error: color("#E82424"),
            on_error: color("#1D1C19"),
            error_container: color("#43242B"),
            on_error_container: color("#E46876"),
            outline: color("#7a8382"),
            outline_variant: color("#625e5a"),
            background: color("#181616"),
            on_background: color("#c5c9c5"),
            inverse_primary: color("#223249"),
            primary_fixed: color("#8ba4b0"),
            primary_fixed_dim: color("#7FB4CA"),
            on_primary_fixed: color("#181616"),
            on_primary_fixed_variant: color("#223249"),
            secondary_fixed: color("#8992a7"),
            secondary_fixed_dim: color("#7a8382"),
            on_secondary_fixed: color("#181616"),
            on_secondary_fixed_variant: color("#223249"),
            tertiary_fixed: color("#8ea4a2"),
            tertiary_fixed_dim: color("#6A9589"),
            on_tertiary_fixed: color("#181616"),
            on_tertiary_fixed_variant: color("#223249"),
            scrim: color("#0d0c0c"),
            shadow: color("#0d0c0c"),
            source_color: color("#8ba4b0"),
            surface_bright: color("#625e5a"),
            surface_dim: color("#0d0c0c"),
        },
    }
}
