use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn kanagawa_lotus(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: false,
        mode: "light".to_string(),
        base16: Base16 {
            base00: color("#f2ecbc"),
            base01: color("#e5ddb0"),
            base02: color("#e7dba0"),
            base03: color("#e4d794"),
            base04: color("#8a8980"),
            base05: color("#545464"),
            base06: color("#43436c"),
            base07: color("#716e61"),
            base08: color("#c84053"),
            base09: color("#cc6d00"),
            base0a: color("#77713f"),
            base0b: color("#6f894e"),
            base0c: color("#597b75"),
            base0d: color("#4d699b"),
            base0e: color("#624c83"),
            base0f: color("#b35b79"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#f2ecbc"),
            on_surface: color("#545464"),
            surface_variant: color("#e5ddb0"),
            on_surface_variant: color("#43436c"),
            surface_container_highest: color("#c9cbd1"),
            surface_container_high: color("#e4d794"),
            surface_container: color("#e7dba0"),
            surface_container_low: color("#dcd5ac"),
            surface_container_lowest: color("#d5cea3"),
            inverse_surface: color("#545464"),
            inverse_on_surface: color("#e5ddb0"),
            surface_tint: color("#4d699b"),
            primary: color("#4d699b"),
            on_primary: color("#f2ecbc"),
            primary_container: color("#c7d7e0"),
            on_primary_container: color("#4d699b"),
            secondary: color("#624c83"),
            on_secondary: color("#f2ecbc"),
            secondary_container: color("#c9cbd1"),
            on_secondary_container: color("#624c83"),
            tertiary: color("#597b75"),
            on_tertiary: color("#f2ecbc"),
            tertiary_container: color("#d7e3d8"),
            on_tertiary_container: color("#597b75"),
            error: color("#e82424"),
            on_error: color("#f2ecbc"),
            error_container: color("#d9a594"),
            on_error_container: color("#c84053"),
            outline: color("#716e61"),
            outline_variant: color("#a09cac"),
            background: color("#f2ecbc"),
            on_background: color("#545464"),
            inverse_primary: color("#9fb5c9"),
            primary_fixed: color("#4d699b"),
            primary_fixed_dim: color("#6693bf"),
            on_primary_fixed: color("#f2ecbc"),
            on_primary_fixed_variant: color("#c7d7e0"),
            secondary_fixed: color("#624c83"),
            secondary_fixed_dim: color("#766b90"),
            on_secondary_fixed: color("#f2ecbc"),
            on_secondary_fixed_variant: color("#c9cbd1"),
            tertiary_fixed: color("#597b75"),
            tertiary_fixed_dim: color("#5e857a"),
            on_tertiary_fixed: color("#f2ecbc"),
            on_tertiary_fixed_variant: color("#d7e3d8"),
            scrim: color("#545464"),
            shadow: color("#545464"),
            source_color: color("#4d699b"),
            surface_bright: color("#f2ecbc"),
            surface_dim: color("#d5cea3"),
        },
    }
}
