use crate::json_struct::{Base16, Colors, MShell, MatugenTheme, Palettes, color};

/// Kenp — a high-contrast electric palette: warm butter-yellow primary,
/// periwinkle secondary and mint tertiary over a near-black indigo surface,
/// with a hot-pink/red error+magenta. The light variant inverts to a soft
/// lavender paper with an indigo primary. Author-supplied house theme.
///
/// | Slot       | Dark      | Light     |
/// |------------|-----------|-----------|
/// | surface    | `#070722` | `#e6e8fa` |
/// | on-surface | `#f3edf7` | `#0e0e43` |
/// | primary    | `#fff59b` | `#5d65f5` |
/// | secondary  | `#a9aefe` | `#8E93D8` |
/// | tertiary   | `#9BFECE` | `#0e0e43` |
/// | error      | `#FD4663` | `#FD4663` |
pub fn kenp(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#070722"),
            base01: color("#11112d"),
            base02: color("#21215F"),
            base03: color("#7c80b4"),
            base04: color("#7c80b4"),
            base05: color("#f3edf7"),
            base06: color("#f3edf7"),
            base07: color("#ffffff"),
            base08: color("#FD4663"),
            base09: color("#fff59b"),
            base0a: color("#fff59b"),
            base0b: color("#9BFECE"),
            base0c: color("#9BFECE"),
            base0d: color("#a9aefe"),
            base0e: color("#FD4663"),
            base0f: color("#FD4663"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#070722"),
            on_surface: color("#f3edf7"),
            surface_variant: color("#11112d"),
            on_surface_variant: color("#7c80b4"),
            surface_container_highest: color("#21215F"),
            surface_container_high: color("#11112d"),
            surface_container: color("#11112d"),
            surface_container_low: color("#070722"),
            surface_container_lowest: color("#070722"),
            inverse_surface: color("#f3edf7"),
            inverse_on_surface: color("#070722"),
            surface_tint: color("#fff59b"),
            primary: color("#fff59b"),
            on_primary: color("#0e0e43"),
            primary_container: color("#11112d"),
            on_primary_container: color("#fff59b"),
            secondary: color("#a9aefe"),
            on_secondary: color("#0e0e43"),
            secondary_container: color("#11112d"),
            on_secondary_container: color("#a9aefe"),
            tertiary: color("#9BFECE"),
            on_tertiary: color("#0e0e43"),
            tertiary_container: color("#11112d"),
            on_tertiary_container: color("#9BFECE"),
            error: color("#FD4663"),
            on_error: color("#0e0e43"),
            error_container: color("#11112d"),
            on_error_container: color("#FD4663"),
            outline: color("#21215F"),
            outline_variant: color("#11112d"),
            background: color("#070722"),
            on_background: color("#f3edf7"),
            inverse_primary: color("#5d65f5"),
            primary_fixed: color("#fff59b"),
            primary_fixed_dim: color("#fff59b"),
            on_primary_fixed: color("#0e0e43"),
            on_primary_fixed_variant: color("#0e0e43"),
            secondary_fixed: color("#a9aefe"),
            secondary_fixed_dim: color("#a9aefe"),
            on_secondary_fixed: color("#0e0e43"),
            on_secondary_fixed_variant: color("#0e0e43"),
            tertiary_fixed: color("#9BFECE"),
            tertiary_fixed_dim: color("#9BFECE"),
            on_tertiary_fixed: color("#0e0e43"),
            on_tertiary_fixed_variant: color("#0e0e43"),
            scrim: color("#070722"),
            shadow: color("#070722"),
            source_color: color("#fff59b"),
            surface_bright: color("#21215F"),
            surface_dim: color("#070722"),
        },
    }
}

/// Kenp Light — the light counterpart of [`kenp`].
pub fn kenp_light(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: false,
        mode: "light".to_string(),
        base16: Base16 {
            base00: color("#e6e8fa"),
            base01: color("#eff0ff"),
            base02: color("#8288fc"),
            base03: color("#4b55c8"),
            base04: color("#4b55c8"),
            base05: color("#4b55c8"),
            base06: color("#0e0e43"),
            base07: color("#0e0e43"),
            base08: color("#FD4663"),
            base09: color("#5d65f5"),
            base0a: color("#5d65f5"),
            base0b: color("#0e0e43"),
            base0c: color("#0e0e43"),
            base0d: color("#8E93D8"),
            base0e: color("#FD4663"),
            base0f: color("#FD4663"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#e6e8fa"),
            on_surface: color("#0e0e43"),
            surface_variant: color("#eff0ff"),
            on_surface_variant: color("#4b55c8"),
            surface_container_highest: color("#dadcff"),
            surface_container_high: color("#dadcff"),
            surface_container: color("#eff0ff"),
            surface_container_low: color("#e6e8fa"),
            surface_container_lowest: color("#e6e8fa"),
            inverse_surface: color("#0e0e43"),
            inverse_on_surface: color("#e6e8fa"),
            surface_tint: color("#5d65f5"),
            primary: color("#5d65f5"),
            on_primary: color("#dadcff"),
            primary_container: color("#dadcff"),
            on_primary_container: color("#4b55c8"),
            secondary: color("#8E93D8"),
            on_secondary: color("#dadcff"),
            secondary_container: color("#eff0ff"),
            on_secondary_container: color("#4b55c8"),
            tertiary: color("#0e0e43"),
            on_tertiary: color("#fef29a"),
            tertiary_container: color("#dadcff"),
            on_tertiary_container: color("#0e0e43"),
            error: color("#FD4663"),
            on_error: color("#0e0e43"),
            error_container: color("#dadcff"),
            on_error_container: color("#FD4663"),
            outline: color("#8288fc"),
            outline_variant: color("#dadcff"),
            background: color("#e6e8fa"),
            on_background: color("#0e0e43"),
            inverse_primary: color("#fff59b"),
            primary_fixed: color("#5d65f5"),
            primary_fixed_dim: color("#5d65f5"),
            on_primary_fixed: color("#dadcff"),
            on_primary_fixed_variant: color("#dadcff"),
            secondary_fixed: color("#8E93D8"),
            secondary_fixed_dim: color("#8E93D8"),
            on_secondary_fixed: color("#dadcff"),
            on_secondary_fixed_variant: color("#dadcff"),
            tertiary_fixed: color("#0e0e43"),
            tertiary_fixed_dim: color("#0e0e43"),
            on_tertiary_fixed: color("#fef29a"),
            on_tertiary_fixed_variant: color("#fef29a"),
            scrim: color("#e6e8fa"),
            shadow: color("#f3edf7"),
            source_color: color("#5d65f5"),
            surface_bright: color("#eff0ff"),
            surface_dim: color("#dadcff"),
        },
    }
}
