use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn miasma(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#222222"),
            base01: color("#2c2c2c"),
            base02: color("#3a3a3a"),
            base03: color("#666666"),
            base04: color("#a8a895"),
            base05: color("#c2c2b0"),
            base06: color("#d7c483"),
            base07: color("#d7c483"),
            base08: color("#685742"),
            base09: color("#b36d43"),
            base0a: color("#c9a554"),
            base0b: color("#5f875f"),
            base0c: color("#78824b"),
            base0d: color("#bb7744"),
            base0e: color("#bb7744"),
            base0f: color("#685742"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#222222"),
            on_surface: color("#c2c2b0"),
            surface_variant: color("#2c2c2c"),
            on_surface_variant: color("#a8a895"),
            surface_container_highest: color("#3a3a3a"),
            surface_container_high: color("#333333"),
            surface_container: color("#2c2c2c"),
            surface_container_low: color("#272727"),
            surface_container_lowest: color("#222222"),
            inverse_surface: color("#c2c2b0"),
            inverse_on_surface: color("#222222"),
            surface_tint: color("#5f875f"),
            primary: color("#5f875f"),
            on_primary: color("#222222"),
            primary_container: color("#2c2c2c"),
            on_primary_container: color("#5f875f"),
            secondary: color("#c9a554"),
            on_secondary: color("#222222"),
            secondary_container: color("#2c2c2c"),
            on_secondary_container: color("#c9a554"),
            tertiary: color("#bb7744"),
            on_tertiary: color("#222222"),
            tertiary_container: color("#2c2c2c"),
            on_tertiary_container: color("#bb7744"),
            error: color("#685742"),
            on_error: color("#c2c2b0"),
            error_container: color("#2c2c2c"),
            on_error_container: color("#685742"),
            outline: color("#666666"),
            outline_variant: color("#3a3a3a"),
            background: color("#222222"),
            on_background: color("#c2c2b0"),
            inverse_primary: color("#5f875f"),
            primary_fixed: color("#5f875f"),
            primary_fixed_dim: color("#78824b"),
            on_primary_fixed: color("#222222"),
            on_primary_fixed_variant: color("#c2c2b0"),
            secondary_fixed: color("#c9a554"),
            secondary_fixed_dim: color("#d7c483"),
            on_secondary_fixed: color("#222222"),
            on_secondary_fixed_variant: color("#c2c2b0"),
            tertiary_fixed: color("#bb7744"),
            tertiary_fixed_dim: color("#b36d43"),
            on_tertiary_fixed: color("#222222"),
            on_tertiary_fixed_variant: color("#c2c2b0"),
            scrim: color("#222222"),
            shadow: color("#222222"),
            source_color: color("#5f875f"),
            surface_bright: color("#3a3a3a"),
            surface_dim: color("#222222"),
        },
    }
}
