use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn monokai_classic(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#221F22"),
            base01: color("#2D2A2E"),
            base02: color("#403E41"),
            base03: color("#727072"),
            base04: color("#939293"),
            base05: color("#FCFCFA"),
            base06: color("#FCFCFA"),
            base07: color("#C1C0C0"),
            base08: color("#FF6188"),
            base09: color("#FC9867"),
            base0a: color("#FFD866"),
            base0b: color("#A9DC76"),
            base0c: color("#78DCE8"),
            base0d: color("#A9DC76"),
            base0e: color("#AB9DF2"),
            base0f: color("#FC9867"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#221F22"),
            on_surface: color("#FCFCFA"),
            surface_variant: color("#2D2A2E"),
            on_surface_variant: color("#939293"),
            surface_container_highest: color("#5B595C"),
            surface_container_high: color("#403E41"),
            surface_container: color("#363437"),
            surface_container_low: color("#2D2A2E"),
            surface_container_lowest: color("#221F22"),
            inverse_surface: color("#FCFCFA"),
            inverse_on_surface: color("#221F22"),
            surface_tint: color("#A9DC76"),
            primary: color("#A9DC76"),
            on_primary: color("#221F22"),
            primary_container: color("#403E41"),
            on_primary_container: color("#A9DC76"),
            secondary: color("#FFD866"),
            on_secondary: color("#221F22"),
            secondary_container: color("#403E41"),
            on_secondary_container: color("#FFD866"),
            tertiary: color("#FF6188"),
            on_tertiary: color("#221F22"),
            tertiary_container: color("#403E41"),
            on_tertiary_container: color("#FF6188"),
            error: color("#FF6188"),
            on_error: color("#221F22"),
            error_container: color("#403E41"),
            on_error_container: color("#FF6188"),
            outline: color("#727072"),
            outline_variant: color("#5B595C"),
            background: color("#221F22"),
            on_background: color("#FCFCFA"),
            inverse_primary: color("#A9DC76"),
            primary_fixed: color("#A9DC76"),
            primary_fixed_dim: color("#78DCE8"),
            on_primary_fixed: color("#221F22"),
            on_primary_fixed_variant: color("#FCFCFA"),
            secondary_fixed: color("#FFD866"),
            secondary_fixed_dim: color("#FC9867"),
            on_secondary_fixed: color("#221F22"),
            on_secondary_fixed_variant: color("#FCFCFA"),
            tertiary_fixed: color("#FF6188"),
            tertiary_fixed_dim: color("#AB9DF2"),
            on_tertiary_fixed: color("#221F22"),
            on_tertiary_fixed_variant: color("#FCFCFA"),
            scrim: color("#221F22"),
            shadow: color("#221F22"),
            source_color: color("#A9DC76"),
            surface_bright: color("#5B595C"),
            surface_dim: color("#221F22"),
        },
    }
}
