use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn nord_dark(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#2E3440"),
            base01: color("#3B4252"),
            base02: color("#434C5E"),
            base03: color("#4C566A"),
            base04: color("#D8DEE9"),
            base05: color("#E5E9F0"),
            base06: color("#ECEFF4"),
            base07: color("#ECEFF4"),
            base08: color("#BF616A"),
            base09: color("#D08770"),
            base0a: color("#EBCB8B"),
            base0b: color("#A3BE8C"),
            base0c: color("#8FBCBB"),
            base0d: color("#81A1C1"),
            base0e: color("#B48EAD"),
            base0f: color("#BF616A"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#2E3440"),
            on_surface: color("#ECEFF4"),
            surface_variant: color("#3B4252"),
            on_surface_variant: color("#D8DEE9"),
            surface_container_highest: color("#4C566A"),
            surface_container_high: color("#434C5E"),
            surface_container: color("#3B4252"),
            surface_container_low: color("#2E3440"),
            surface_container_lowest: color("#2E3440"),
            inverse_surface: color("#ECEFF4"),
            inverse_on_surface: color("#2E3440"),
            surface_tint: color("#88C0D0"),
            primary: color("#88C0D0"),
            on_primary: color("#2E3440"),
            primary_container: color("#3B4252"),
            on_primary_container: color("#88C0D0"),
            secondary: color("#81A1C1"),
            on_secondary: color("#2E3440"),
            secondary_container: color("#3B4252"),
            on_secondary_container: color("#81A1C1"),
            tertiary: color("#8FBCBB"),
            on_tertiary: color("#2E3440"),
            tertiary_container: color("#3B4252"),
            on_tertiary_container: color("#8FBCBB"),
            error: color("#BF616A"),
            on_error: color("#2E3440"),
            error_container: color("#3B4252"),
            on_error_container: color("#BF616A"),
            outline: color("#4C566A"),
            outline_variant: color("#434C5E"),
            background: color("#2E3440"),
            on_background: color("#ECEFF4"),
            inverse_primary: color("#5E81AC"),
            primary_fixed: color("#88C0D0"),
            primary_fixed_dim: color("#88C0D0"),
            on_primary_fixed: color("#2E3440"),
            on_primary_fixed_variant: color("#2E3440"),
            secondary_fixed: color("#81A1C1"),
            secondary_fixed_dim: color("#81A1C1"),
            on_secondary_fixed: color("#2E3440"),
            on_secondary_fixed_variant: color("#2E3440"),
            tertiary_fixed: color("#8FBCBB"),
            tertiary_fixed_dim: color("#8FBCBB"),
            on_tertiary_fixed: color("#2E3440"),
            on_tertiary_fixed_variant: color("#2E3440"),
            scrim: color("#2E3440"),
            shadow: color("#2E3440"),
            source_color: color("#88C0D0"),
            surface_bright: color("#4C566A"),
            surface_dim: color("#2E3440"),
        },
    }
}
