use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn oceanic_next(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#1B2B34"),
            base01: color("#343D46"),
            base02: color("#4F5B66"),
            base03: color("#65737E"),
            base04: color("#A7ADBA"),
            base05: color("#C0C5CE"),
            base06: color("#CDD3DE"),
            base07: color("#D8DEE9"),
            base08: color("#EC5F67"),
            base09: color("#F99157"),
            base0a: color("#FAC863"),
            base0b: color("#99C794"),
            base0c: color("#5FB3B3"),
            base0d: color("#6699CC"),
            base0e: color("#C594C5"),
            base0f: color("#AB7967"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#1B2B34"),
            on_surface: color("#D8DEE9"),
            surface_variant: color("#343D46"),
            on_surface_variant: color("#D8DEE9"),
            surface_container_highest: color("#65737E"),
            surface_container_high: color("#4F5B66"),
            surface_container: color("#343D46"),
            surface_container_low: color("#343D46"),
            surface_container_lowest: color("#1B2B34"),
            inverse_surface: color("#D8DEE9"),
            inverse_on_surface: color("#1B2B34"),
            surface_tint: color("#6699CC"),
            primary: color("#6699CC"),
            on_primary: color("#D8DEE9"),
            primary_container: color("#343D46"),
            on_primary_container: color("#6699CC"),
            secondary: color("#5FB3B3"),
            on_secondary: color("#D8DEE9"),
            secondary_container: color("#343D46"),
            on_secondary_container: color("#5FB3B3"),
            tertiary: color("#99C794"),
            on_tertiary: color("#D8DEE9"),
            tertiary_container: color("#343D46"),
            on_tertiary_container: color("#99C794"),
            error: color("#EC5F67"),
            on_error: color("#D8DEE9"),
            error_container: color("#343D46"),
            on_error_container: color("#EC5F67"),
            outline: color("#4F5B66"),
            outline_variant: color("#343D46"),
            background: color("#1B2B34"),
            on_background: color("#D8DEE9"),
            inverse_primary: color("#C594C5"),
            primary_fixed: color("#6699CC"),
            primary_fixed_dim: color("#6699CC"),
            on_primary_fixed: color("#D8DEE9"),
            on_primary_fixed_variant: color("#D8DEE9"),
            secondary_fixed: color("#5FB3B3"),
            secondary_fixed_dim: color("#5FB3B3"),
            on_secondary_fixed: color("#D8DEE9"),
            on_secondary_fixed_variant: color("#D8DEE9"),
            tertiary_fixed: color("#99C794"),
            tertiary_fixed_dim: color("#99C794"),
            on_tertiary_fixed: color("#D8DEE9"),
            on_tertiary_fixed_variant: color("#D8DEE9"),
            scrim: color("#1B2B34"),
            shadow: color("#1B2B34"),
            source_color: color("#6699CC"),
            surface_bright: color("#65737E"),
            surface_dim: color("#1B2B34"),
        },
    }
}
