use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn one_dark(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#282C34"),
            base01: color("#1F2228"),
            base02: color("#31363F"),
            base03: color("#3A3F4B"),
            base04: color("#5C6370"),
            base05: color("#ABB2BF"),
            base06: color("#828997"),
            base07: color("#636D83"),
            base08: color("#E06C75"),
            base09: color("#D19A66"),
            base0a: color("#E5C07B"),
            base0b: color("#98C379"),
            base0c: color("#56B6C2"),
            base0d: color("#61AFEF"),
            base0e: color("#C678DD"),
            base0f: color("#BE5046"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#282C34"),
            on_surface: color("#ABB2BF"),
            surface_variant: color("#31363F"),
            on_surface_variant: color("#828997"),
            surface_container_highest: color("#434956"),
            surface_container_high: color("#3A3F4B"),
            surface_container: color("#31363F"),
            surface_container_low: color("#1F2228"),
            surface_container_lowest: color("#16181D"),
            inverse_surface: color("#ABB2BF"),
            inverse_on_surface: color("#31363F"),
            surface_tint: color("#61AFEF"),
            primary: color("#61AFEF"),
            on_primary: color("#31363F"),
            primary_container: color("#31363F"),
            on_primary_container: color("#61AFEF"),
            secondary: color("#C678DD"),
            on_secondary: color("#31363F"),
            secondary_container: color("#31363F"),
            on_secondary_container: color("#C678DD"),
            tertiary: color("#56B6C2"),
            on_tertiary: color("#31363F"),
            tertiary_container: color("#31363F"),
            on_tertiary_container: color("#56B6C2"),
            error: color("#E06C75"),
            on_error: color("#31363F"),
            error_container: color("#31363F"),
            on_error_container: color("#E06C75"),
            outline: color("#636D83"),
            outline_variant: color("#5C6370"),
            background: color("#282C34"),
            on_background: color("#ABB2BF"),
            inverse_primary: color("#31363F"),
            primary_fixed: color("#61AFEF"),
            primary_fixed_dim: color("#528BFF"),
            on_primary_fixed: color("#31363F"),
            on_primary_fixed_variant: color("#31363F"),
            secondary_fixed: color("#C678DD"),
            secondary_fixed_dim: color("#C678DD"),
            on_secondary_fixed: color("#31363F"),
            on_secondary_fixed_variant: color("#31363F"),
            tertiary_fixed: color("#56B6C2"),
            tertiary_fixed_dim: color("#56B6C2"),
            on_tertiary_fixed: color("#31363F"),
            on_tertiary_fixed_variant: color("#31363F"),
            scrim: color("#16181D"),
            shadow: color("#16181D"),
            source_color: color("#61AFEF"),
            surface_bright: color("#434956"),
            surface_dim: color("#16181D"),
        },
    }
}
