use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn osaka_jade(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#111c18"),
            base01: color("#192722"),
            base02: color("#23372B"),
            base03: color("#53685B"),
            base04: color("#75bbb3"),
            base05: color("#C1C497"),
            base06: color("#F6F5DD"),
            base07: color("#ACD4CF"),
            base08: color("#FF5345"),
            base09: color("#E5C736"),
            base0a: color("#D7C995"),
            base0b: color("#549e6a"),
            base0c: color("#2DD5B7"),
            base0d: color("#509475"),
            base0e: color("#D2689C"),
            base0f: color("#db9f9c"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#111c18"),
            on_surface: color("#C1C497"),
            surface_variant: color("#192722"),
            on_surface_variant: color("#ACD4CF"),
            surface_container_highest: color("#2e453a"),
            surface_container_high: color("#293e33"),
            surface_container: color("#23372B"),
            surface_container_low: color("#192722"),
            surface_container_lowest: color("#111c18"),
            inverse_surface: color("#F6F5DD"),
            inverse_on_surface: color("#111c18"),
            surface_tint: color("#509475"),
            primary: color("#509475"),
            on_primary: color("#111c18"),
            primary_container: color("#23372B"),
            on_primary_container: color("#509475"),
            secondary: color("#2DD5B7"),
            on_secondary: color("#111c18"),
            secondary_container: color("#23372B"),
            on_secondary_container: color("#2DD5B7"),
            tertiary: color("#D2689C"),
            on_tertiary: color("#111c18"),
            tertiary_container: color("#23372B"),
            on_tertiary_container: color("#D2689C"),
            error: color("#FF5345"),
            on_error: color("#111c18"),
            error_container: color("#23372B"),
            on_error_container: color("#FF5345"),
            outline: color("#53685B"),
            outline_variant: color("#2e453a"),
            background: color("#111c18"),
            on_background: color("#C1C497"),
            inverse_primary: color("#509475"),
            primary_fixed: color("#509475"),
            primary_fixed_dim: color("#549e6a"),
            on_primary_fixed: color("#111c18"),
            on_primary_fixed_variant: color("#C1C497"),
            secondary_fixed: color("#2DD5B7"),
            secondary_fixed_dim: color("#75bbb3"),
            on_secondary_fixed: color("#111c18"),
            on_secondary_fixed_variant: color("#C1C497"),
            tertiary_fixed: color("#D2689C"),
            tertiary_fixed_dim: color("#db9f9c"),
            on_tertiary_fixed: color("#111c18"),
            on_tertiary_fixed_variant: color("#C1C497"),
            scrim: color("#111c18"),
            shadow: color("#111c18"),
            source_color: color("#509475"),
            surface_bright: color("#2e453a"),
            surface_dim: color("#111c18"),
        },
    }
}
