use crate::json_struct::{Base16, Colors, MShell, MatugenTheme, Palettes, color};

/// `Oxocarbon` — dark theme imported from the community palette
/// collection (noctalia format). M3 roles map from the palette's `m*`
/// keys; container/fixed shades are derived luminance blends; the base16
/// accent ramp maps from the terminal ANSI set.
pub fn oxocarbon(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#161616"),
            base01: color("#131313"),
            base02: color("#262626"),
            base03: color("#333333"),
            base04: color("#989A9C"),
            base05: color("#F2F4F8"),
            base06: color("#DDE1E6"),
            base07: color("#979A9D"),
            base08: color("#EE5396"),
            base09: color("#B891CA"),
            base0a: color("#82CFFF"),
            base0b: color("#42BE65"),
            base0c: color("#3DDBD9"),
            base0d: color("#33B1FF"),
            base0e: color("#FF7EB6"),
            base0f: color("#A23E69"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#161616"),
            on_surface: color("#F2F4F8"),
            surface_variant: color("#262626"),
            on_surface_variant: color("#DDE1E6"),
            surface_container_highest: color("#444444"),
            surface_container_high: color("#333333"),
            surface_container: color("#262626"),
            surface_container_low: color("#131313"),
            surface_container_lowest: color("#0E0E0E"),
            inverse_surface: color("#F2F4F8"),
            inverse_on_surface: color("#262626"),
            surface_tint: color("#33B1FF"),
            primary: color("#33B1FF"),
            on_primary: color("#161616"),
            primary_container: color("#1E4157"),
            on_primary_container: color("#47B9FF"),
            secondary: color("#42BE65"),
            on_secondary: color("#161616"),
            secondary_container: color("#22452C"),
            on_secondary_container: color("#55C474"),
            tertiary: color("#BE95FF"),
            on_tertiary: color("#161616"),
            tertiary_container: color("#453A57"),
            on_tertiary_container: color("#C4A0FF"),
            error: color("#EE5396"),
            on_error: color("#161616"),
            error_container: color("#52273A"),
            on_error_container: color("#F064A0"),
            outline: color("#525252"),
            outline_variant: color("#373737"),
            background: color("#161616"),
            on_background: color("#F2F4F8"),
            inverse_primary: color("#1E4157"),
            primary_fixed: color("#33B1FF"),
            primary_fixed_dim: color("#2D9CE0"),
            on_primary_fixed: color("#161616"),
            on_primary_fixed_variant: color("#161616"),
            secondary_fixed: color("#42BE65"),
            secondary_fixed_dim: color("#3AA759"),
            on_secondary_fixed: color("#161616"),
            on_secondary_fixed_variant: color("#161616"),
            tertiary_fixed: color("#BE95FF"),
            tertiary_fixed_dim: color("#A783E0"),
            on_tertiary_fixed: color("#161616"),
            on_tertiary_fixed_variant: color("#161616"),
            scrim: color("#000000"),
            shadow: color("#000000"),
            source_color: color("#33B1FF"),
            surface_bright: color("#444444"),
            surface_dim: color("#0E0E0E"),
        },
    }
}
