use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn poimandres(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#1B1E28"),
            base01: color("#171922"),
            base02: color("#303340"),
            base03: color("#506477"),
            base04: color("#767C9D"),
            base05: color("#E4F0FB"),
            base06: color("#A6ACCD"),
            base07: color("#7390AA"),
            base08: color("#D0679D"),
            base09: color("#FAE4FC"),
            base0a: color("#FFFAC2"),
            base0b: color("#5DE4C7"),
            base0c: color("#89DDFF"),
            base0d: color("#ADD7FF"),
            base0e: color("#FCC5E9"),
            base0f: color("#5FB3A1"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#1B1E28"),
            on_surface: color("#E4F0FB"),
            surface_variant: color("#303340"),
            on_surface_variant: color("#A6ACCD"),
            surface_container_highest: color("#506477"),
            surface_container_high: color("#303340"),
            surface_container: color("#252837"),
            surface_container_low: color("#171922"),
            surface_container_lowest: color("#13151C"),
            inverse_surface: color("#E4F0FB"),
            inverse_on_surface: color("#303340"),
            surface_tint: color("#ADD7FF"),
            primary: color("#ADD7FF"),
            on_primary: color("#303340"),
            primary_container: color("#303340"),
            on_primary_container: color("#ADD7FF"),
            secondary: color("#5DE4C7"),
            on_secondary: color("#303340"),
            secondary_container: color("#303340"),
            on_secondary_container: color("#5DE4C7"),
            tertiary: color("#FCC5E9"),
            on_tertiary: color("#303340"),
            tertiary_container: color("#303340"),
            on_tertiary_container: color("#FCC5E9"),
            error: color("#D0679D"),
            on_error: color("#303340"),
            error_container: color("#303340"),
            on_error_container: color("#D0679D"),
            outline: color("#767C9D"),
            outline_variant: color("#506477"),
            background: color("#1B1E28"),
            on_background: color("#E4F0FB"),
            inverse_primary: color("#303340"),
            primary_fixed: color("#ADD7FF"),
            primary_fixed_dim: color("#91B4D5"),
            on_primary_fixed: color("#1B1E28"),
            on_primary_fixed_variant: color("#303340"),
            secondary_fixed: color("#5DE4C7"),
            secondary_fixed_dim: color("#5FB3A1"),
            on_secondary_fixed: color("#1B1E28"),
            on_secondary_fixed_variant: color("#303340"),
            tertiary_fixed: color("#FCC5E9"),
            tertiary_fixed_dim: color("#FAE4FC"),
            on_tertiary_fixed: color("#1B1E28"),
            on_tertiary_fixed_variant: color("#303340"),
            scrim: color("#171922"),
            shadow: color("#171922"),
            source_color: color("#ADD7FF"),
            surface_bright: color("#506477"),
            surface_dim: color("#171922"),
        },
    }
}
