use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn retro_82(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#00172e"),
            base01: color("#0a2540"),
            base02: color("#134e5a"),
            base03: color("#3f8f8a"),
            base04: color("#a7c9c6"),
            base05: color("#f6dcac"),
            base06: color("#f6dcac"),
            base07: color("#8cbfb8"),
            base08: color("#f85525"),
            base09: color("#e97b3c"),
            base0a: color("#faa968"),
            base0b: color("#028391"),
            base0c: color("#8cbfb8"),
            base0d: color("#3f8f8a"),
            base0e: color("#faa968"),
            base0f: color("#f85525"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#00172e"),
            on_surface: color("#f6dcac"),
            surface_variant: color("#0a2540"),
            on_surface_variant: color("#a7c9c6"),
            surface_container_highest: color("#134e5a"),
            surface_container_high: color("#0f3a4d"),
            surface_container: color("#0a2c40"),
            surface_container_low: color("#0a2540"),
            surface_container_lowest: color("#00172e"),
            inverse_surface: color("#f6dcac"),
            inverse_on_surface: color("#00172e"),
            surface_tint: color("#faa968"),
            primary: color("#faa968"),
            on_primary: color("#00172e"),
            primary_container: color("#0a2540"),
            on_primary_container: color("#faa968"),
            secondary: color("#028391"),
            on_secondary: color("#00172e"),
            secondary_container: color("#0a2540"),
            on_secondary_container: color("#028391"),
            tertiary: color("#f85525"),
            on_tertiary: color("#00172e"),
            tertiary_container: color("#0a2540"),
            on_tertiary_container: color("#f85525"),
            error: color("#f85525"),
            on_error: color("#00172e"),
            error_container: color("#0a2540"),
            on_error_container: color("#f85525"),
            outline: color("#3f8f8a"),
            outline_variant: color("#134e5a"),
            background: color("#00172e"),
            on_background: color("#f6dcac"),
            inverse_primary: color("#faa968"),
            primary_fixed: color("#faa968"),
            primary_fixed_dim: color("#e97b3c"),
            on_primary_fixed: color("#00172e"),
            on_primary_fixed_variant: color("#f6dcac"),
            secondary_fixed: color("#028391"),
            secondary_fixed_dim: color("#3f8f8a"),
            on_secondary_fixed: color("#00172e"),
            on_secondary_fixed_variant: color("#f6dcac"),
            tertiary_fixed: color("#f85525"),
            tertiary_fixed_dim: color("#e97b3c"),
            on_tertiary_fixed: color("#00172e"),
            on_tertiary_fixed_variant: color("#f6dcac"),
            scrim: color("#00172e"),
            shadow: color("#00172e"),
            source_color: color("#faa968"),
            surface_bright: color("#134e5a"),
            surface_dim: color("#00172e"),
        },
    }
}
