use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn rose_pine_moon(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#232136"),
            base01: color("#2A273F"),
            base02: color("#393552"),
            base03: color("#6E6A86"),
            base04: color("#908CAA"),
            base05: color("#E0DEF4"),
            base06: color("#E0DEF4"),
            base07: color("#E0DEF4"),
            base08: color("#EB6F92"),
            base09: color("#F6C177"),
            base0a: color("#EA9A97"),
            base0b: color("#3E8FB0"),
            base0c: color("#9CCFD8"),
            base0d: color("#C4A7E7"),
            base0e: color("#C4A7E7"),
            base0f: color("#EB6F92"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#232136"),
            on_surface: color("#E0DEF4"),
            surface_variant: color("#2A273F"),
            on_surface_variant: color("#908CAA"),
            surface_container_highest: color("#56526E"),
            surface_container_high: color("#44415A"),
            surface_container: color("#393552"),
            surface_container_low: color("#2A273F"),
            surface_container_lowest: color("#232136"),
            inverse_surface: color("#E0DEF4"),
            inverse_on_surface: color("#232136"),
            surface_tint: color("#C4A7E7"),
            primary: color("#C4A7E7"),
            on_primary: color("#232136"),
            primary_container: color("#393552"),
            on_primary_container: color("#C4A7E7"),
            secondary: color("#9CCFD8"),
            on_secondary: color("#232136"),
            secondary_container: color("#393552"),
            on_secondary_container: color("#9CCFD8"),
            tertiary: color("#EA9A97"),
            on_tertiary: color("#232136"),
            tertiary_container: color("#393552"),
            on_tertiary_container: color("#EA9A97"),
            error: color("#EB6F92"),
            on_error: color("#232136"),
            error_container: color("#393552"),
            on_error_container: color("#EB6F92"),
            outline: color("#6E6A86"),
            outline_variant: color("#44415A"),
            background: color("#232136"),
            on_background: color("#E0DEF4"),
            inverse_primary: color("#3E8FB0"),
            primary_fixed: color("#C4A7E7"),
            primary_fixed_dim: color("#C4A7E7"),
            on_primary_fixed: color("#232136"),
            on_primary_fixed_variant: color("#232136"),
            secondary_fixed: color("#9CCFD8"),
            secondary_fixed_dim: color("#9CCFD8"),
            on_secondary_fixed: color("#232136"),
            on_secondary_fixed_variant: color("#232136"),
            tertiary_fixed: color("#EA9A97"),
            tertiary_fixed_dim: color("#EA9A97"),
            on_tertiary_fixed: color("#232136"),
            on_tertiary_fixed_variant: color("#232136"),
            scrim: color("#232136"),
            shadow: color("#232136"),
            source_color: color("#C4A7E7"),
            surface_bright: color("#56526E"),
            surface_dim: color("#232136"),
        },
    }
}
