use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn rose_pine_dawn(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: false,
        mode: "light".to_string(),
        base16: Base16 {
            base00: color("#FAF4ED"),
            base01: color("#FFFAF3"),
            base02: color("#F2E9E1"),
            base03: color("#9893A5"),
            base04: color("#797593"),
            base05: color("#575279"),
            base06: color("#575279"),
            base07: color("#575279"),
            base08: color("#B4637A"),
            base09: color("#EA9D34"),
            base0a: color("#D7827E"),
            base0b: color("#286983"),
            base0c: color("#56949F"),
            base0d: color("#907AA9"),
            base0e: color("#907AA9"),
            base0f: color("#B4637A"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#FAF4ED"),
            on_surface: color("#575279"),
            surface_variant: color("#F2E9E1"),
            on_surface_variant: color("#797593"),
            surface_container_highest: color("#CECACD"),
            surface_container_high: color("#DFDAD9"),
            surface_container: color("#F2E9E1"),
            surface_container_low: color("#FFFAF3"),
            surface_container_lowest: color("#FAF4ED"),
            inverse_surface: color("#575279"),
            inverse_on_surface: color("#FAF4ED"),
            surface_tint: color("#907AA9"),
            primary: color("#907AA9"),
            on_primary: color("#FAF4ED"),
            primary_container: color("#F2E9E1"),
            on_primary_container: color("#907AA9"),
            secondary: color("#56949F"),
            on_secondary: color("#FAF4ED"),
            secondary_container: color("#F2E9E1"),
            on_secondary_container: color("#56949F"),
            tertiary: color("#D7827E"),
            on_tertiary: color("#FAF4ED"),
            tertiary_container: color("#F2E9E1"),
            on_tertiary_container: color("#D7827E"),
            error: color("#B4637A"),
            on_error: color("#FAF4ED"),
            error_container: color("#F2E9E1"),
            on_error_container: color("#B4637A"),
            outline: color("#9893A5"),
            outline_variant: color("#DFDAD9"),
            background: color("#FAF4ED"),
            on_background: color("#575279"),
            inverse_primary: color("#286983"),
            primary_fixed: color("#907AA9"),
            primary_fixed_dim: color("#907AA9"),
            on_primary_fixed: color("#FAF4ED"),
            on_primary_fixed_variant: color("#FAF4ED"),
            secondary_fixed: color("#56949F"),
            secondary_fixed_dim: color("#56949F"),
            on_secondary_fixed: color("#FAF4ED"),
            on_secondary_fixed_variant: color("#FAF4ED"),
            tertiary_fixed: color("#D7827E"),
            tertiary_fixed_dim: color("#D7827E"),
            on_tertiary_fixed: color("#FAF4ED"),
            on_tertiary_fixed_variant: color("#FAF4ED"),
            scrim: color("#575279"),
            shadow: color("#575279"),
            source_color: color("#907AA9"),
            surface_bright: color("#FAF4ED"),
            surface_dim: color("#F2E9E1"),
        },
    }
}
