use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn rose_pine(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#191724"),
            base01: color("#1F1D2E"),
            base02: color("#26233A"),
            base03: color("#6E6A86"),
            base04: color("#908CAA"),
            base05: color("#E0DEF4"),
            base06: color("#E0DEF4"),
            base07: color("#E0DEF4"),
            base08: color("#EB6F92"),
            base09: color("#F6C177"),
            base0a: color("#EBBCBA"),
            base0b: color("#31748F"),
            base0c: color("#9CCFD8"),
            base0d: color("#C4A7E7"),
            base0e: color("#C4A7E7"),
            base0f: color("#EB6F92"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#191724"),
            on_surface: color("#E0DEF4"),
            surface_variant: color("#1F1D2E"),
            on_surface_variant: color("#908CAA"),
            surface_container_highest: color("#524F67"),
            surface_container_high: color("#403D52"),
            surface_container: color("#26233A"),
            surface_container_low: color("#1F1D2E"),
            surface_container_lowest: color("#191724"),
            inverse_surface: color("#E0DEF4"),
            inverse_on_surface: color("#191724"),
            surface_tint: color("#C4A7E7"),
            primary: color("#C4A7E7"),
            on_primary: color("#191724"),
            primary_container: color("#26233A"),
            on_primary_container: color("#C4A7E7"),
            secondary: color("#9CCFD8"),
            on_secondary: color("#191724"),
            secondary_container: color("#26233A"),
            on_secondary_container: color("#9CCFD8"),
            tertiary: color("#EBBCBA"),
            on_tertiary: color("#191724"),
            tertiary_container: color("#26233A"),
            on_tertiary_container: color("#EBBCBA"),
            error: color("#EB6F92"),
            on_error: color("#191724"),
            error_container: color("#26233A"),
            on_error_container: color("#EB6F92"),
            outline: color("#6E6A86"),
            outline_variant: color("#403D52"),
            background: color("#191724"),
            on_background: color("#E0DEF4"),
            inverse_primary: color("#31748F"),
            primary_fixed: color("#C4A7E7"),
            primary_fixed_dim: color("#C4A7E7"),
            on_primary_fixed: color("#191724"),
            on_primary_fixed_variant: color("#191724"),
            secondary_fixed: color("#9CCFD8"),
            secondary_fixed_dim: color("#9CCFD8"),
            on_secondary_fixed: color("#191724"),
            on_secondary_fixed_variant: color("#191724"),
            tertiary_fixed: color("#EBBCBA"),
            tertiary_fixed_dim: color("#EBBCBA"),
            on_tertiary_fixed: color("#191724"),
            on_tertiary_fixed_variant: color("#191724"),
            scrim: color("#191724"),
            shadow: color("#191724"),
            source_color: color("#C4A7E7"),
            surface_bright: color("#524F67"),
            surface_dim: color("#191724"),
        },
    }
}
