use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn saga(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#05080a"),
            base01: color("#0e1216"),
            base02: color("#1a1e22"),
            base03: color("#4b4c4d"),
            base04: color("#ffc2df"),
            base05: color("#fff6ff"),
            base06: color("#fff6ff"),
            base07: color("#f3ceff"),
            base08: color("#ff9fbc"),
            base09: color("#ffc79b"),
            base0a: color("#fff6c3"),
            base0b: color("#baf7b5"),
            base0c: color("#b2fff3"),
            base0d: color("#dfbaff"),
            base0e: color("#f3ceff"),
            base0f: color("#ffaecb"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#05080a"),
            on_surface: color("#fff6ff"),
            surface_variant: color("#0e1216"),
            on_surface_variant: color("#f3ceff"),
            surface_container_highest: color("#2a2e34"),
            surface_container_high: color("#22262b"),
            surface_container: color("#1a1e22"),
            surface_container_low: color("#0e1216"),
            surface_container_lowest: color("#05080a"),
            inverse_surface: color("#fff6ff"),
            inverse_on_surface: color("#05080a"),
            surface_tint: color("#b2fff3"),
            primary: color("#b2fff3"),
            on_primary: color("#05080a"),
            primary_container: color("#1a1e22"),
            on_primary_container: color("#b2fff3"),
            secondary: color("#dfbaff"),
            on_secondary: color("#05080a"),
            secondary_container: color("#1a1e22"),
            on_secondary_container: color("#dfbaff"),
            tertiary: color("#ff9fbc"),
            on_tertiary: color("#05080a"),
            tertiary_container: color("#1a1e22"),
            on_tertiary_container: color("#ff9fbc"),
            error: color("#ff9fbc"),
            on_error: color("#05080a"),
            error_container: color("#1a1e22"),
            on_error_container: color("#ff9fbc"),
            outline: color("#4b4c4d"),
            outline_variant: color("#2a2e34"),
            background: color("#05080a"),
            on_background: color("#fff6ff"),
            inverse_primary: color("#b2fff3"),
            primary_fixed: color("#b2fff3"),
            primary_fixed_dim: color("#baf7b5"),
            on_primary_fixed: color("#05080a"),
            on_primary_fixed_variant: color("#fff6ff"),
            secondary_fixed: color("#dfbaff"),
            secondary_fixed_dim: color("#f3ceff"),
            on_secondary_fixed: color("#05080a"),
            on_secondary_fixed_variant: color("#fff6ff"),
            tertiary_fixed: color("#ff9fbc"),
            tertiary_fixed_dim: color("#ffaecb"),
            on_tertiary_fixed: color("#05080a"),
            on_tertiary_fixed_variant: color("#fff6ff"),
            scrim: color("#05080a"),
            shadow: color("#05080a"),
            source_color: color("#b2fff3"),
            surface_bright: color("#2a2e34"),
            surface_dim: color("#05080a"),
        },
    }
}
