use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn seoul(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#333233"),
            base01: color("#3F3F3F"),
            base02: color("#4B4B4B"),
            base03: color("#565656"),
            base04: color("#999872"),
            base05: color("#DFDEBD"),
            base06: color("#DFDEBD"),
            base07: color("#DFDEBD"),
            base08: color("#BE7572"),
            base09: color("#E19972"),
            base0a: color("#DFBC72"),
            base0b: color("#98BC99"),
            base0c: color("#98BCBD"),
            base0d: color("#9A7372"),
            base0e: color("#E17899"),
            base0f: color("#BE7572"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#333233"),
            on_surface: color("#DFDEBD"),
            surface_variant: color("#3F3F3F"),
            on_surface_variant: color("#DFDEBD"),
            surface_container_highest: color("#6B6B6B"),
            surface_container_high: color("#565656"),
            surface_container: color("#4B4B4B"),
            surface_container_low: color("#3F3F3F"),
            surface_container_lowest: color("#333233"),
            inverse_surface: color("#DFDEBD"),
            inverse_on_surface: color("#333233"),
            surface_tint: color("#9A7372"),
            primary: color("#9A7372"),
            on_primary: color("#DFDEBD"),
            primary_container: color("#3F3F3F"),
            on_primary_container: color("#9A7372"),
            secondary: color("#98BC99"),
            on_secondary: color("#DFDEBD"),
            secondary_container: color("#3F3F3F"),
            on_secondary_container: color("#98BC99"),
            tertiary: color("#98BCBD"),
            on_tertiary: color("#DFDEBD"),
            tertiary_container: color("#3F3F3F"),
            on_tertiary_container: color("#98BCBD"),
            error: color("#BE7572"),
            on_error: color("#DFDEBD"),
            error_container: color("#3F3F3F"),
            on_error_container: color("#BE7572"),
            outline: color("#565656"),
            outline_variant: color("#4B4B4B"),
            background: color("#333233"),
            on_background: color("#DFDEBD"),
            inverse_primary: color("#E17899"),
            primary_fixed: color("#9A7372"),
            primary_fixed_dim: color("#9A7372"),
            on_primary_fixed: color("#DFDEBD"),
            on_primary_fixed_variant: color("#DFDEBD"),
            secondary_fixed: color("#98BC99"),
            secondary_fixed_dim: color("#98BC99"),
            on_secondary_fixed: color("#DFDEBD"),
            on_secondary_fixed_variant: color("#DFDEBD"),
            tertiary_fixed: color("#98BCBD"),
            tertiary_fixed_dim: color("#98BCBD"),
            on_tertiary_fixed: color("#DFDEBD"),
            on_tertiary_fixed_variant: color("#DFDEBD"),
            scrim: color("#333233"),
            shadow: color("#333233"),
            source_color: color("#9A7372"),
            surface_bright: color("#6B6B6B"),
            surface_dim: color("#333233"),
        },
    }
}
