use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn solarized_light(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: false,
        mode: "light".to_string(),
        base16: Base16 {
            base00: color("#fdf6e3"),
            base01: color("#eee8d5"),
            base02: color("#93a1a1"),
            base03: color("#839496"),
            base04: color("#657b83"),
            base05: color("#586e75"),
            base06: color("#073642"),
            base07: color("#002b36"),
            base08: color("#dc322f"),
            base09: color("#cb4b16"),
            base0a: color("#b58900"),
            base0b: color("#859900"),
            base0c: color("#2aa198"),
            base0d: color("#268bd2"),
            base0e: color("#6c71c4"),
            base0f: color("#d33682"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#fdf6e3"),
            on_surface: color("#586e75"),
            surface_variant: color("#eee8d5"),
            on_surface_variant: color("#657b83"),
            surface_container_highest: color("#839496"),
            surface_container_high: color("#93a1a1"),
            surface_container: color("#eee8d5"),
            surface_container_low: color("#f5efdc"),
            surface_container_lowest: color("#ffffff"),
            inverse_surface: color("#073642"),
            inverse_on_surface: color("#eee8d5"),
            surface_tint: color("#268bd2"),
            primary: color("#268bd2"),
            on_primary: color("#fdf6e3"),
            primary_container: color("#eee8d5"),
            on_primary_container: color("#268bd2"),
            secondary: color("#2aa198"),
            on_secondary: color("#fdf6e3"),
            secondary_container: color("#eee8d5"),
            on_secondary_container: color("#2aa198"),
            tertiary: color("#b58900"),
            on_tertiary: color("#fdf6e3"),
            tertiary_container: color("#eee8d5"),
            on_tertiary_container: color("#b58900"),
            error: color("#dc322f"),
            on_error: color("#fdf6e3"),
            error_container: color("#eee8d5"),
            on_error_container: color("#dc322f"),
            outline: color("#657b83"),
            outline_variant: color("#93a1a1"),
            background: color("#fdf6e3"),
            on_background: color("#586e75"),
            inverse_primary: color("#eee8d5"),
            primary_fixed: color("#268bd2"),
            primary_fixed_dim: color("#268bd2"),
            on_primary_fixed: color("#fdf6e3"),
            on_primary_fixed_variant: color("#fdf6e3"),
            secondary_fixed: color("#2aa198"),
            secondary_fixed_dim: color("#2aa198"),
            on_secondary_fixed: color("#fdf6e3"),
            on_secondary_fixed_variant: color("#fdf6e3"),
            tertiary_fixed: color("#b58900"),
            tertiary_fixed_dim: color("#b58900"),
            on_tertiary_fixed: color("#fdf6e3"),
            on_tertiary_fixed_variant: color("#fdf6e3"),
            scrim: color("#002b36"),
            shadow: color("#002b36"),
            source_color: color("#268bd2"),
            surface_bright: color("#ffffff"),
            surface_dim: color("#eee8d5"),
        },
    }
}
