use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn solitude(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#101315"),
            base01: color("#1a1d1f"),
            base02: color("#343d41"),
            base03: color("#565d60"),
            base04: color("#798186"),
            base05: color("#cacccc"),
            base06: color("#d9dbdc"),
            base07: color("#a8adb0"),
            base08: color("#de6145"),
            base09: color("#c9c2b4"),
            base0a: color("#d9dbdc"),
            base0b: color("#9fa5a9"),
            base0c: color("#a5aeb4"),
            base0d: color("#798186"),
            base0e: color("#aeaeae"),
            base0f: color("#cbc2be"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#101315"),
            on_surface: color("#cacccc"),
            surface_variant: color("#1a1d1f"),
            on_surface_variant: color("#a8adb0"),
            surface_container_highest: color("#4b4e55"),
            surface_container_high: color("#3d4144"),
            surface_container: color("#2c2f32"),
            surface_container_low: color("#1a1d1f"),
            surface_container_lowest: color("#101315"),
            inverse_surface: color("#cacccc"),
            inverse_on_surface: color("#101315"),
            surface_tint: color("#798186"),
            primary: color("#798186"),
            on_primary: color("#101315"),
            primary_container: color("#1a1d1f"),
            on_primary_container: color("#a8adb0"),
            secondary: color("#a8adb0"),
            on_secondary: color("#101315"),
            secondary_container: color("#1a1d1f"),
            on_secondary_container: color("#a8adb0"),
            tertiary: color("#de6145"),
            on_tertiary: color("#101315"),
            tertiary_container: color("#1a1d1f"),
            on_tertiary_container: color("#de6145"),
            error: color("#de6145"),
            on_error: color("#101315"),
            error_container: color("#1a1d1f"),
            on_error_container: color("#de6145"),
            outline: color("#565d60"),
            outline_variant: color("#343d41"),
            background: color("#101315"),
            on_background: color("#cacccc"),
            inverse_primary: color("#798186"),
            primary_fixed: color("#798186"),
            primary_fixed_dim: color("#a8adb0"),
            on_primary_fixed: color("#101315"),
            on_primary_fixed_variant: color("#cacccc"),
            secondary_fixed: color("#a8adb0"),
            secondary_fixed_dim: color("#cacccc"),
            on_secondary_fixed: color("#101315"),
            on_secondary_fixed_variant: color("#cacccc"),
            tertiary_fixed: color("#de6145"),
            tertiary_fixed_dim: color("#de6145"),
            on_tertiary_fixed: color("#101315"),
            on_tertiary_fixed_variant: color("#cacccc"),
            scrim: color("#101315"),
            shadow: color("#101315"),
            source_color: color("#798186"),
            surface_bright: color("#4b4e55"),
            surface_dim: color("#101315"),
        },
    }
}
