use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn synthwave84(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#18191F"),
            base01: color("#2A2B32"),
            base02: color("#343640"),
            base03: color("#484953"),
            base04: color("#6C6C83"),
            base05: color("#8B8BAC"),
            base06: color("#A1A1BF"),
            base07: color("#C4C4D6"),
            base08: color("#FF536C"),
            base09: color("#FF8189"),
            base0a: color("#C080FF"),
            base0b: color("#7F9FFF"),
            base0c: color("#FFC346"),
            base0d: color("#FFFF99"),
            base0e: color("#FFA367"),
            base0f: color("#BFBFDE"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#18191F"),
            on_surface: color("#C4C4D6"),
            surface_variant: color("#2A2B32"),
            on_surface_variant: color("#C4C4D6"),
            surface_container_highest: color("#484953"),
            surface_container_high: color("#343640"),
            surface_container: color("#2A2B32"),
            surface_container_low: color("#2A2B32"),
            surface_container_lowest: color("#18191F"),
            inverse_surface: color("#C4C4D6"),
            inverse_on_surface: color("#18191F"),
            surface_tint: color("#FF536C"),
            primary: color("#FF536C"),
            on_primary: color("#C4C4D6"),
            primary_container: color("#343640"),
            on_primary_container: color("#FF536C"),
            secondary: color("#7F9FFF"),
            on_secondary: color("#C4C4D6"),
            secondary_container: color("#343640"),
            on_secondary_container: color("#7F9FFF"),
            tertiary: color("#C080FF"),
            on_tertiary: color("#C4C4D6"),
            tertiary_container: color("#343640"),
            on_tertiary_container: color("#C080FF"),
            error: color("#FF536C"),
            on_error: color("#C4C4D6"),
            error_container: color("#343640"),
            on_error_container: color("#FF536C"),
            outline: color("#484953"),
            outline_variant: color("#343640"),
            background: color("#18191F"),
            on_background: color("#C4C4D6"),
            inverse_primary: color("#FF8189"),
            primary_fixed: color("#FF536C"),
            primary_fixed_dim: color("#FF536C"),
            on_primary_fixed: color("#C4C4D6"),
            on_primary_fixed_variant: color("#C4C4D6"),
            secondary_fixed: color("#7F9FFF"),
            secondary_fixed_dim: color("#7F9FFF"),
            on_secondary_fixed: color("#C4C4D6"),
            on_secondary_fixed_variant: color("#C4C4D6"),
            tertiary_fixed: color("#C080FF"),
            tertiary_fixed_dim: color("#C080FF"),
            on_tertiary_fixed: color("#C4C4D6"),
            on_tertiary_fixed_variant: color("#C4C4D6"),
            scrim: color("#18191F"),
            shadow: color("#18191F"),
            source_color: color("#FF536C"),
            surface_bright: color("#484953"),
            surface_dim: color("#18191F"),
        },
    }
}
