use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn tokyo_night_light(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: false,
        mode: "light".to_string(),
        base16: Base16 {
            base00: color("#e6e7ed"),
            base01: color("#d5d6db"),
            base02: color("#c4c5ca"),
            base03: color("#6c6e75"),
            base04: color("#40434f"),
            base05: color("#343b58"),
            base06: color("#343b58"),
            base07: color("#343b58"),
            base08: color("#8c4351"),
            base09: color("#965027"),
            base0a: color("#8f5e15"),
            base0b: color("#385f0d"),
            base0c: color("#33635c"),
            base0d: color("#2959aa"),
            base0e: color("#5a3e8e"),
            base0f: color("#8c4351"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#e6e7ed"),
            on_surface: color("#343b58"),
            surface_variant: color("#d5d6db"),
            on_surface_variant: color("#40434f"),
            surface_container_highest: color("#c4c5ca"),
            surface_container_high: color("#cbccd2"),
            surface_container: color("#d5d6db"),
            surface_container_low: color("#dfe0e6"),
            surface_container_lowest: color("#f0f0f5"),
            inverse_surface: color("#343b58"),
            inverse_on_surface: color("#d5d6db"),
            surface_tint: color("#2959aa"),
            primary: color("#2959aa"),
            on_primary: color("#e6e7ed"),
            primary_container: color("#d5d6db"),
            on_primary_container: color("#2959aa"),
            secondary: color("#5a3e8e"),
            on_secondary: color("#e6e7ed"),
            secondary_container: color("#d5d6db"),
            on_secondary_container: color("#5a3e8e"),
            tertiary: color("#33635c"),
            on_tertiary: color("#e6e7ed"),
            tertiary_container: color("#d5d6db"),
            on_tertiary_container: color("#33635c"),
            error: color("#8c4351"),
            on_error: color("#e6e7ed"),
            error_container: color("#d5d6db"),
            on_error_container: color("#8c4351"),
            outline: color("#6c6e75"),
            outline_variant: color("#c4c5ca"),
            background: color("#e6e7ed"),
            on_background: color("#343b58"),
            inverse_primary: color("#d5d6db"),
            primary_fixed: color("#2959aa"),
            primary_fixed_dim: color("#2959aa"),
            on_primary_fixed: color("#e6e7ed"),
            on_primary_fixed_variant: color("#e6e7ed"),
            secondary_fixed: color("#5a3e8e"),
            secondary_fixed_dim: color("#5a3e8e"),
            on_secondary_fixed: color("#e6e7ed"),
            on_secondary_fixed_variant: color("#e6e7ed"),
            tertiary_fixed: color("#33635c"),
            tertiary_fixed_dim: color("#33635c"),
            on_tertiary_fixed: color("#e6e7ed"),
            on_tertiary_fixed_variant: color("#e6e7ed"),
            scrim: color("#343b58"),
            shadow: color("#343b58"),
            source_color: color("#2959aa"),
            surface_bright: color("#f0f0f5"),
            surface_dim: color("#c4c5ca"),
        },
    }
}
