use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn tokyo_night(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#1a1b26"),
            base01: color("#16161e"),
            base02: color("#2f3549"),
            base03: color("#414868"),
            base04: color("#565f89"),
            base05: color("#a9b1d6"),
            base06: color("#c0caf5"),
            base07: color("#c0caf5"),
            base08: color("#f7768e"),
            base09: color("#ff9e64"),
            base0a: color("#e0af68"),
            base0b: color("#9ece6a"),
            base0c: color("#73daca"),
            base0d: color("#7aa2f7"),
            base0e: color("#bb9af7"),
            base0f: color("#f7768e"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#1a1b26"),
            on_surface: color("#a9b1d6"),
            surface_variant: color("#2f3549"),
            on_surface_variant: color("#9aa5ce"),
            surface_container_highest: color("#565f89"),
            surface_container_high: color("#414868"),
            surface_container: color("#2f3549"),
            surface_container_low: color("#16161e"),
            surface_container_lowest: color("#101014"),
            inverse_surface: color("#c0caf5"),
            inverse_on_surface: color("#2f3549"),
            surface_tint: color("#7aa2f7"),
            primary: color("#7aa2f7"),
            on_primary: color("#2f3549"),
            primary_container: color("#2f3549"),
            on_primary_container: color("#7aa2f7"),
            secondary: color("#bb9af7"),
            on_secondary: color("#2f3549"),
            secondary_container: color("#2f3549"),
            on_secondary_container: color("#bb9af7"),
            tertiary: color("#73daca"),
            on_tertiary: color("#2f3549"),
            tertiary_container: color("#2f3549"),
            on_tertiary_container: color("#73daca"),
            error: color("#f7768e"),
            on_error: color("#2f3549"),
            error_container: color("#2f3549"),
            on_error_container: color("#f7768e"),
            outline: color("#9aa5ce"),
            outline_variant: color("#565f89"),
            background: color("#1a1b26"),
            on_background: color("#a9b1d6"),
            inverse_primary: color("#2f3549"),
            primary_fixed: color("#7aa2f7"),
            primary_fixed_dim: color("#7aa2f7"),
            on_primary_fixed: color("#2f3549"),
            on_primary_fixed_variant: color("#2f3549"),
            secondary_fixed: color("#bb9af7"),
            secondary_fixed_dim: color("#bb9af7"),
            on_secondary_fixed: color("#2f3549"),
            on_secondary_fixed_variant: color("#2f3549"),
            tertiary_fixed: color("#73daca"),
            tertiary_fixed_dim: color("#73daca"),
            on_tertiary_fixed: color("#2f3549"),
            on_tertiary_fixed_variant: color("#2f3549"),
            scrim: color("#101014"),
            shadow: color("#101014"),
            source_color: color("#7aa2f7"),
            surface_bright: color("#565f89"),
            surface_dim: color("#101014"),
        },
    }
}
