use crate::json_struct::{Base16, Colors, MatugenTheme, MShell, Palettes, color};

pub fn varda(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#0C0E11"),
            base01: color("#121519"),
            base02: color("#1C2128"),
            base03: color("#38414F"),
            base04: color("#52677C"),
            base05: color("#8295A9"),
            base06: color("#D0EBEE"),
            base07: color("#D0EBEE"),
            base08: color("#733447"),
            base09: color("#C78C56"),
            base0a: color("#C78C56"),
            base0b: color("#257B76"),
            base0c: color("#257B76"),
            base0d: color("#52677C"),
            base0e: color("#665276"),
            base0f: color("#733447"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#0C0E11"),
            on_surface: color("#D0EBEE"),
            surface_variant: color("#1C2128"),
            on_surface_variant: color("#D0EBEE"),
            surface_container_highest: color("#38414F"),
            surface_container_high: color("#272E38"),
            surface_container: color("#222830"),
            surface_container_low: color("#171B21"),
            surface_container_lowest: color("#121519"),
            inverse_surface: color("#D0EBEE"),
            inverse_on_surface: color("#0C0E11"),
            surface_tint: color("#52677C"),
            primary: color("#52677C"),
            on_primary: color("#D0EBEE"),
            primary_container: color("#38414F"),
            on_primary_container: color("#52677C"),
            secondary: color("#665276"),
            on_secondary: color("#D0EBEE"),
            secondary_container: color("#38414F"),
            on_secondary_container: color("#665276"),
            tertiary: color("#257B76"),
            on_tertiary: color("#D0EBEE"),
            tertiary_container: color("#38414F"),
            on_tertiary_container: color("#257B76"),
            error: color("#733447"),
            on_error: color("#D0EBEE"),
            error_container: color("#38414F"),
            on_error_container: color("#733447"),
            outline: color("#8295A9"),
            outline_variant: color("#38414F"),
            background: color("#0C0E11"),
            on_background: color("#D0EBEE"),
            inverse_primary: color("#38414F"),
            primary_fixed: color("#52677C"),
            primary_fixed_dim: color("#52677C"),
            on_primary_fixed: color("#D0EBEE"),
            on_primary_fixed_variant: color("#D0EBEE"),
            secondary_fixed: color("#665276"),
            secondary_fixed_dim: color("#665276"),
            on_secondary_fixed: color("#D0EBEE"),
            on_secondary_fixed_variant: color("#D0EBEE"),
            tertiary_fixed: color("#257B76"),
            tertiary_fixed_dim: color("#257B76"),
            on_tertiary_fixed: color("#D0EBEE"),
            on_tertiary_fixed_variant: color("#D0EBEE"),
            scrim: color("#121519"),
            shadow: color("#121519"),
            source_color: color("#52677C"),
            surface_bright: color("#38414F"),
            surface_dim: color("#0C0E11"),
        },
    }
}
