use crate::json_struct::{Base16, Colors, MShell, MatugenTheme, Palettes, color};

/// `Vesper` — dark theme imported from the community palette
/// collection (noctalia format). M3 roles map from the palette's `m*`
/// keys; container/fixed shades are derived luminance blends; the base16
/// accent ramp maps from the terminal ANSI set.
pub fn vesper(mshell: MShell) -> MatugenTheme {
    MatugenTheme {
        mshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#0C0C0C"),
            base01: color("#0A0A0A"),
            base02: color("#1C1C1C"),
            base03: color("#2A2A2A"),
            base04: color("#787878"),
            base05: color("#FFFFFF"),
            base06: color("#A0A0A0"),
            base07: color("#6C6C6C"),
            base08: color("#FF8080"),
            base09: color("#FFA48C"),
            base0a: color("#FFC799"),
            base0b: color("#99FFE4"),
            base0c: color("#99FFE4"),
            base0d: color("#80B3FF"),
            base0e: color("#FBADFF"),
            base0f: color("#AA5757"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#0C0C0C"),
            on_surface: color("#FFFFFF"),
            surface_variant: color("#1C1C1C"),
            on_surface_variant: color("#A0A0A0"),
            surface_container_highest: color("#3C3C3C"),
            surface_container_high: color("#2A2A2A"),
            surface_container: color("#1C1C1C"),
            surface_container_low: color("#0A0A0A"),
            surface_container_lowest: color("#080808"),
            inverse_surface: color("#FFFFFF"),
            inverse_on_surface: color("#1C1C1C"),
            surface_tint: color("#FFC799"),
            primary: color("#FFC799"),
            on_primary: color("#000000"),
            primary_container: color("#504033"),
            on_primary_container: color("#FFCDA3"),
            secondary: color("#99FFE4"),
            on_secondary: color("#000000"),
            secondary_container: color("#335048"),
            on_secondary_container: color("#A3FFE7"),
            tertiary: color("#FBADFF"),
            on_tertiary: color("#000000"),
            tertiary_container: color("#4F3950"),
            on_tertiary_container: color("#FBB5FF"),
            error: color("#FF8080"),
            on_error: color("#000000"),
            error_container: color("#502C2C"),
            on_error_container: color("#FF8D8D"),
            outline: color("#505050"),
            outline_variant: color("#313131"),
            background: color("#0C0C0C"),
            on_background: color("#FFFFFF"),
            inverse_primary: color("#504033"),
            primary_fixed: color("#FFC799"),
            primary_fixed_dim: color("#E0AF87"),
            on_primary_fixed: color("#000000"),
            on_primary_fixed_variant: color("#000000"),
            secondary_fixed: color("#99FFE4"),
            secondary_fixed_dim: color("#87E0C9"),
            on_secondary_fixed: color("#000000"),
            on_secondary_fixed_variant: color("#000000"),
            tertiary_fixed: color("#FBADFF"),
            tertiary_fixed_dim: color("#DD98E0"),
            on_tertiary_fixed: color("#000000"),
            on_tertiary_fixed_variant: color("#000000"),
            scrim: color("#000000"),
            shadow: color("#000000"),
            source_color: color("#FFC799"),
            surface_bright: color("#3C3C3C"),
            surface_dim: color("#080808"),
        },
    }
}
