//! Plugin-keybind registry + binds file writer.
//!
//! Each plugin's manifest can ship one or more `[[keybind]]` entries. We
//! resolve conflicts deterministically (alphabetical plugin id wins) so the
//! same plugin set always produces the same active bindings — load order
//! never matters. Losers are logged and surfaced via [`Resolution::conflict`].
//!
//! The shell writes the survivors to `~/.config/margo/binds.d/mshell-plugins.conf`
//! as `bind = <combo>, spawn, mshellctl plugin keybind <plugin-key> <id>` lines.
//! The user adds `source=binds.d/mshell-plugins.conf` to their `config.conf`
//! once; mshell calls `mctl reload` whenever the file changes.

use crate::{Keybind, PluginStore};
use std::collections::BTreeMap;
use std::io::Write;
use std::path::{Path, PathBuf};

/// One plugin's bind plus how it fared against conflicts.
#[derive(Debug, Clone)]
pub struct Resolution {
    /// Composite plugin key (`"mullvad"`, `"a1b2:my-plugin"`, …).
    pub plugin_key: String,
    /// The plugin's declared binding.
    pub keybind: Keybind,
    /// `Some(winner_key)` if this binding lost to another plugin claiming
    /// the same combo first; `None` when this is the active binding.
    pub conflict: Option<String>,
}

impl Resolution {
    pub fn is_active(&self) -> bool {
        self.conflict.is_none()
    }
}

/// Resolve every installed-and-enabled plugin's keybinds. Stable order:
/// plugins by composite key alphabetically, then bindings in manifest order.
pub fn resolve_all(store: &PluginStore) -> Vec<Resolution> {
    let state = store.load_state();
    // Alphabetical plugin order makes the resolution deterministic regardless
    // of install order on disk.
    let mut plugins = store.installed();
    plugins.sort_by(|a, b| a.key.cmp(&b.key));

    let mut owner: BTreeMap<String, String> = BTreeMap::new();
    let mut out: Vec<Resolution> = Vec::new();
    for plugin in plugins {
        if !state.is_enabled(&plugin.key) {
            continue;
        }
        for keybind in &plugin.manifest.keybinds {
            let combo = normalize_combo(&keybind.combo);
            if combo.is_empty() || keybind.id.trim().is_empty() {
                continue;
            }
            let conflict = if let Some(winner) = owner.get(&combo) {
                Some(winner.clone())
            } else {
                owner.insert(combo.clone(), plugin.key.clone());
                None
            };
            out.push(Resolution {
                plugin_key: plugin.key.clone(),
                keybind: Keybind {
                    combo,
                    id: keybind.id.clone(),
                    description: keybind.description.clone(),
                },
                conflict,
            });
        }
    }
    out
}

/// Lower-case the modifier part of a margo combo (`Super+a` → `super+a`) so
/// `Super+A` and `super+a` collide. Margo itself is case-insensitive on
/// modifiers; this just normalises the registry's view.
fn normalize_combo(combo: &str) -> String {
    let trimmed = combo.trim();
    if trimmed.is_empty() {
        return String::new();
    }
    // Split on the comma that margo uses between modifier-chord and key —
    // keep the keysym case as is (margo cares about case for some keysyms).
    if let Some((mods, key)) = trimmed.rsplit_once(',') {
        format!("{},{}", mods.to_ascii_lowercase(), key)
    } else {
        // Single segment (just modifiers, no key) — uncommon but normalise.
        trimmed.to_ascii_lowercase()
    }
}

/// Path of the file mshell writes its plugin binds to. The user opts in by
/// adding `source=binds.d/mshell-plugins.conf` to their `config.conf` once.
pub fn binds_path() -> PathBuf {
    dirs::config_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join("margo")
        .join("binds.d")
        .join("mshell-plugins.conf")
}

/// Write the active resolutions to [`binds_path`]. Returns `Ok(true)` if the
/// file's contents actually changed (so the caller knows to ask margo for a
/// reload). Creates the parent directory if missing.
pub fn write_binds_file(resolved: &[Resolution]) -> std::io::Result<bool> {
    let path = binds_path();
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let mut body = String::new();
    body.push_str(
        "# Generated by mshell. Do not edit — re-rendered on every plugin\n\
         # enable / disable / install / uninstall.\n\
         #\n\
         # To activate, add this line to ~/.config/margo/config.conf:\n\
         #     source=binds.d/mshell-plugins.conf\n\
         # then run: mctl reload\n\n",
    );
    for r in resolved.iter().filter(|r| r.is_active()) {
        body.push_str(&format!(
            "bind = {}, spawn, mshellctl plugin keybind {} {}\n",
            r.keybind.combo, r.plugin_key, r.keybind.id
        ));
    }
    // Trailing notes on conflicts so a curious user grepping the file sees
    // why a binding they expected isn't there.
    let conflicts: Vec<&Resolution> = resolved.iter().filter(|r| !r.is_active()).collect();
    if !conflicts.is_empty() {
        body.push_str("\n# Conflicts (combo already claimed by an earlier plugin):\n");
        for r in conflicts {
            let winner = r.conflict.as_deref().unwrap_or("?");
            body.push_str(&format!(
                "#   {} wanted {} -> {} but {} got it first\n",
                r.plugin_key, r.keybind.combo, r.keybind.id, winner
            ));
        }
    }

    let previous = std::fs::read_to_string(&path).unwrap_or_default();
    if previous == body {
        return Ok(false);
    }
    let mut f = std::fs::File::create(&path)?;
    f.write_all(body.as_bytes())?;
    Ok(true)
}

/// `true` if the user's `config.conf` already pulls in our binds file.
/// Lets the shell log a one-shot hint when it doesn't.
pub fn user_sources_us(config_conf: &Path) -> bool {
    let Ok(text) = std::fs::read_to_string(config_conf) else {
        return false;
    };
    text.lines()
        .map(|l| l.trim())
        .any(|l| l.starts_with("source=") && l.contains("binds.d/mshell-plugins.conf"))
}
