//! Generate configuration files

use anyhow::{anyhow, Context, Result};
use colored::*;
use std::fs;
use std::io::{self, Write};

use crate::config::ConfigPaths;

/// Check if Lua support is available (either config.lua or host.lua files exist)
fn check_lua_support(paths: &ConfigPaths) -> Result<()> {
    let config_lua = paths.config_dir.join("config.lua");

    // Check for config.lua
    if config_lua.exists() {
        return Ok(());
    }

    // Check for any .lua files in hosts directory
    let hosts_dir = paths.config_dir.join("hosts");
    if hosts_dir.exists() {
        if let Ok(entries) = fs::read_dir(&hosts_dir) {
            for entry in entries.filter_map(|e| e.ok()) {
                let path = entry.path();
                if path.extension().and_then(|s| s.to_str()) == Some("lua") {
                    return Ok(());
                }
            }
        }
    }

    // No Lua files found - provide helpful error
    Err(anyhow!(
        "{}\n\n\
            Lua modules require Lua configuration support to be set up first.\n\n\
            You have two options:\n\
            1. Convert your config to Lua:\n\
               - Move {} to {}\n\
               - Update the syntax to Lua format (see LUA-HOSTS.md for examples)\n\n\
            2. Use the advanced init to set up a new Lua-based config:\n\
               - {}\n\n\
            For more information, see:\n\
               - LUA-MODULES.md for Lua module format\n\
               - LUA-HOSTS.md for Lua host configuration\n\
               - MDOTS-LUA-API.md for available APIs",
        "Lua support not detected!".red().bold(),
        "config.yaml".cyan(),
        "config.lua".cyan(),
        "mdots init --adv".cyan()
    ))
}

/// Generate hardware.lua module with auto-detection
pub fn hardware(paths: &ConfigPaths, force: bool) -> Result<()> {
    // Check for Lua support first
    check_lua_support(paths)?;

    println!("{}", "=== Generate hardware.lua ===".blue());
    println!();

    let modules_dir = paths.modules_dir();
    let hardware_file = modules_dir.join("hardware.lua");

    // Check if file already exists
    if hardware_file.exists() && !force {
        println!(
            "{} hardware.lua already exists at: {}",
            "!".yellow(),
            hardware_file.display()
        );
        print!("Overwrite? [y/N] ");
        io::stdout().flush()?;

        let mut input = String::new();
        io::stdin().read_line(&mut input)?;

        if !input.trim().eq_ignore_ascii_case("y") {
            println!("{}", "Cancelled".yellow());
            return Ok(());
        }
    }

    // Ensure modules directory exists
    fs::create_dir_all(&modules_dir).context("Failed to create modules directory")?;

    // Generate the hardware.lua content
    let content = generate_hardware_lua_content();

    // Write the file
    fs::write(&hardware_file, &content).context("Failed to write hardware.lua")?;

    println!("{} Created: {}", "✓".green(), hardware_file.display());
    println!();
    println!("{}", "Hardware Detection Module Generated!".green());
    println!();
    println!("This module will automatically detect:");
    println!(
        "  {} CPU vendor (Intel/AMD) and install appropriate microcode",
        "•".cyan()
    );
    println!(
        "  {} GPU vendor(s) and install appropriate drivers",
        "•".cyan()
    );
    println!(
        "  {} Laptop vs Desktop and install power management tools",
        "•".cyan()
    );
    println!();
    println!("Next steps:");
    println!(
        "  1. Review the module: {}",
        "cat ~/.config/arch-config/modules/hardware.lua".cyan()
    );
    println!(
        "  2. Enable the module: {}",
        "mdots module enable hardware".cyan()
    );
    println!("  3. Preview changes:   {}", "mdots sync --dry-run".cyan());
    println!();

    Ok(())
}

/// Generate the content for hardware.lua
fn generate_hardware_lua_content() -> String {
    r#"-- Hardware Detection Module for mdots
-- This module automatically detects your hardware and selects appropriate packages
-- Generated by: mdots generate hardware

local hardware = {}

-- Get CPU vendor
function hardware.get_cpu_packages()
    local packages = {}
    local cpu = mdots.hardware.cpu_vendor()

    if cpu == "intel" then
        table.insert(packages, "intel-ucode")
    elseif cpu == "amd" then
        table.insert(packages, "amd-ucode")
    end

    return packages
end

-- Get GPU packages based on detected hardware
function hardware.get_gpu_packages()
    local packages = {}
    local is_laptop = mdots.hardware.is_laptop()

    -- Always include base mesa for OpenGL
    table.insert(packages, "mesa")

    if mdots.hardware.has_nvidia() then
        if is_laptop then
            -- Laptop: Use DKMS driver for hybrid graphics
            table.insert(packages, "nvidia-dkms")
            table.insert(packages, "nvidia-utils")
            table.insert(packages, "nvidia-settings")
            table.insert(packages, "nvidia-prime")  -- For GPU switching
            -- Also need Intel/AMD integrated graphics packages
        else
            -- Desktop: Use standard driver
            table.insert(packages, "nvidia")
            table.insert(packages, "nvidia-utils")
            table.insert(packages, "nvidia-settings")
        end
        table.insert(packages, "lib32-nvidia-utils")  -- 32-bit support for games
    end

    if mdots.hardware.has_amd_gpu() then
        table.insert(packages, "vulkan-radeon")
        table.insert(packages, "lib32-vulkan-radeon")
        table.insert(packages, "libva-mesa-driver")  -- Hardware video acceleration
        table.insert(packages, "lib32-mesa")
    end

    if mdots.hardware.has_intel_gpu() then
        table.insert(packages, "vulkan-intel")
        table.insert(packages, "lib32-vulkan-intel")
        table.insert(packages, "intel-media-driver")  -- Hardware video acceleration
        table.insert(packages, "lib32-mesa")
    end

    return packages
end

-- Get laptop-specific packages
function hardware.get_laptop_packages()
    local packages = {}

    if mdots.hardware.is_laptop() then
        table.insert(packages, "tlp")           -- Power management
        table.insert(packages, "tlp-rdw")       -- Radio device wizard
        table.insert(packages, "powertop")      -- Power consumption analyzer
        -- Uncomment if you want brightness control
        -- table.insert(packages, "brightnessctl")
    end

    return packages
end

-- Get services to enable/disable based on hardware
function hardware.get_services()
    local services = {
        enabled = {},
        disabled = {}
    }

    if mdots.hardware.is_laptop() then
        table.insert(services.enabled, "tlp")
    end

    return services
end

-- Combine all packages
function hardware.get_all_packages()
    local packages = {}

    -- Add CPU packages
    for _, pkg in ipairs(hardware.get_cpu_packages()) do
        table.insert(packages, pkg)
    end

    -- Add GPU packages
    for _, pkg in ipairs(hardware.get_gpu_packages()) do
        table.insert(packages, pkg)
    end

    -- Add laptop packages
    for _, pkg in ipairs(hardware.get_laptop_packages()) do
        table.insert(packages, pkg)
    end

    -- Always include firmware
    table.insert(packages, "linux-firmware")

    return packages
end

-- Build metadata for display
function hardware.get_metadata()
    return {
        cpu = mdots.hardware.cpu_vendor(),
        gpus = mdots.hardware.gpu_vendors(),
        is_laptop = mdots.hardware.is_laptop(),
        has_battery = mdots.hardware.has_battery(),
        chassis = mdots.hardware.chassis_type(),
        hostname = mdots.system.hostname(),
    }
end

-- Export module configuration
return {
    description = "Auto-detected hardware configuration for " .. mdots.system.hostname(),
    packages = hardware.get_all_packages(),
    services = hardware.get_services(),
    metadata = hardware.get_metadata(),

    -- Optional: Add hooks for hardware-specific setup
    -- pre_install_hook = "scripts/hardware-pre.sh",
    -- post_install_hook = "scripts/hardware-post.sh",
}
"#
    .to_string()
}

/// Generate service.lua module with auto-detection
pub fn service(paths: &ConfigPaths, force: bool) -> Result<()> {
    // Check for Lua support first
    check_lua_support(paths)?;

    println!("{}", "=== Generate service.lua ===".blue());
    println!();

    let modules_dir = paths.modules_dir();
    let service_file = modules_dir.join("service.lua");

    // Check if file already exists
    if service_file.exists() && !force {
        println!(
            "{} service.lua already exists at: {}",
            "!".yellow(),
            service_file.display()
        );
        print!("Overwrite? [y/N] ");
        io::stdout().flush()?;

        let mut input = String::new();
        io::stdin().read_line(&mut input)?;

        if !input.trim().eq_ignore_ascii_case("y") {
            println!("{}", "Cancelled".yellow());
            return Ok(());
        }
    }

    // Ensure modules directory exists
    fs::create_dir_all(&modules_dir).context("Failed to create modules directory")?;

    // Generate the service.lua content
    let content = generate_service_lua_content();

    // Write the file
    fs::write(&service_file, &content).context("Failed to write service.lua")?;

    println!("{} Created: {}", "✓".green(), service_file.display());
    println!();
    println!("{}", "Service Detection Module Generated!".green());
    println!();
    println!("This module will automatically detect:");
    println!(
        "  {} Active and enabled services on your system",
        "•".cyan()
    );
    println!(
        "  {} Desktop environment services (NetworkManager, bluetooth, etc.)",
        "•".cyan()
    );
    println!(
        "  {} Audio server services (PulseAudio, PipeWire)",
        "•".cyan()
    );
    println!();
    println!("Next steps:");
    println!(
        "  1. Review the module: {}",
        "cat ~/.config/arch-config/modules/service.lua".cyan()
    );
    println!(
        "  2. Enable the module: {}",
        "mdots module enable service".cyan()
    );
    println!("  3. Preview changes:   {}", "mdots sync --dry-run".cyan());
    println!();

    Ok(())
}

/// Generate the content for service.lua
fn generate_service_lua_content() -> String {
    r#"-- Service Detection Module for mdots
-- This module automatically detects running services and configures them
-- Generated by: mdots generate service

local service = {}

-- Get desktop environment services
function service.get_desktop_services()
    local services = {
        enabled = {},
        disabled = {}
    }

    -- Network Manager
    if mdots.service.is_active("NetworkManager") then
        table.insert(services.enabled, "NetworkManager.service")
    end

    -- Bluetooth
    if mdots.service.is_active("bluetooth") then
        table.insert(services.enabled, "bluetooth.service")
    end

    -- Display Manager detection
    if mdots.service.is_active("sddm") then
        table.insert(services.enabled, "sddm.service")
    elseif mdots.service.is_active("gdm") then
        table.insert(services.enabled, "gdm.service")
    elseif mdots.service.is_active("lightdm") then
        table.insert(services.enabled, "lightdm.service")
    end

    return services
end

-- Get audio services
function service.get_audio_services()
    local services = {
        enabled = {},
        disabled = {}
    }

    -- PulseAudio (user service)
    if mdots.service.is_user_service("pulseaudio") then
        -- PulseAudio is socket-activated, ensure it's available
        mdots.log.info("PulseAudio user service detected")
    end

    -- PipeWire (user services)
    if mdots.service.is_user_service("pipewire") then
        mdots.log.info("PipeWire detected")
    end

    return services
end

-- Get system services
function service.get_system_services()
    local services = {
        enabled = {},
        disabled = {}
    }

    -- SSH
    if mdots.service.is_enabled("sshd") then
        table.insert(services.enabled, "sshd.service")
    end

    -- Docker
    if mdots.service.is_enabled("docker") then
        table.insert(services.enabled, "docker.service")
    end

    -- Firewall
    if mdots.service.is_active("ufw") then
        table.insert(services.enabled, "ufw.service")
    elseif mdots.service.is_active("firewalld") then
        table.insert(services.enabled, "firewalld.service")
    end

    -- Power management for laptops
    if mdots.hardware.is_laptop() then
        if mdots.service.is_active("tlp") then
            table.insert(services.enabled, "tlp.service")
        end
    end

    return services
end

-- Combine all services
function service.get_all_services()
    local all_services = {
        enabled = {},
        disabled = {}
    }

    -- Merge desktop services
    local desktop = service.get_desktop_services()
    for _, svc in ipairs(desktop.enabled) do
        table.insert(all_services.enabled, svc)
    end

    -- Merge system services
    local system = service.get_system_services()
    for _, svc in ipairs(system.enabled) do
        table.insert(all_services.enabled, svc)
    end

    return all_services
end

-- Export module configuration
return {
    description = "Auto-detected service configuration for " .. mdots.system.hostname(),
    services = service.get_all_services(),

    -- Metadata for display
    metadata = {
        hostname = mdots.system.hostname(),
        detected_at = "auto-generated",
    }
}
"#
    .to_string()
}

/// Generate storage.lua module with auto-detection
pub fn storage(paths: &ConfigPaths, force: bool) -> Result<()> {
    // Check for Lua support first
    check_lua_support(paths)?;

    println!("{}", "=== Generate storage.lua ===".blue());
    println!();

    let modules_dir = paths.modules_dir();
    let storage_file = modules_dir.join("storage.lua");

    // Check if file already exists
    if storage_file.exists() && !force {
        println!(
            "{} storage.lua already exists at: {}",
            "!".yellow(),
            storage_file.display()
        );
        print!("Overwrite? [y/N] ");
        io::stdout().flush()?;

        let mut input = String::new();
        io::stdin().read_line(&mut input)?;

        if !input.trim().eq_ignore_ascii_case("y") {
            println!("{}", "Cancelled".yellow());
            return Ok(());
        }
    }

    // Ensure modules directory exists
    fs::create_dir_all(&modules_dir).context("Failed to create modules directory")?;

    // Generate the storage.lua content
    let content = generate_storage_lua_content();

    // Write the file
    fs::write(&storage_file, &content).context("Failed to write storage.lua")?;

    println!("{} Created: {}", "✓".green(), storage_file.display());
    println!();
    println!("{}", "Storage Detection Module Generated!".green());
    println!();
    println!("This module will automatically detect:");
    println!("  {} SSD vs HDD and install appropriate tools", "•".cyan());
    println!("  {} NVMe drives and install nvme-cli", "•".cyan());
    println!(
        "  {} Filesystem types (btrfs, ext4, xfs) and install tools",
        "•".cyan()
    );
    println!("  {} TRIM support for SSDs (fstrim timer)", "•".cyan());
    println!();
    println!("Next steps:");
    println!(
        "  1. Review the module: {}",
        "cat ~/.config/arch-config/modules/storage.lua".cyan()
    );
    println!(
        "  2. Enable the module: {}",
        "mdots module enable storage".cyan()
    );
    println!("  3. Preview changes:   {}", "mdots sync --dry-run".cyan());
    println!();

    Ok(())
}

/// Generate the content for storage.lua
fn generate_storage_lua_content() -> String {
    r#"-- Storage Detection Module for mdots
-- This module automatically detects storage devices and filesystems
-- Generated by: mdots generate storage

local storage = {}

-- Get packages for SSD optimization
function storage.get_ssd_packages()
    local packages = {}

    if mdots.storage.has_ssd() then
        table.insert(packages, "util-linux")  -- For fstrim
    end

    return packages
end

-- Get packages for NVMe drives
function storage.get_nvme_packages()
    local packages = {}

    if mdots.storage.has_nvme() then
        table.insert(packages, "nvme-cli")  -- NVMe management tools
    end

    return packages
end

-- Get filesystem-specific packages
function storage.get_filesystem_packages()
    local packages = {}

    -- Check root filesystem
    local root_fs = mdots.storage.filesystem("/")

    if root_fs == "btrfs" then
        table.insert(packages, "btrfs-progs")
        table.insert(packages, "snapper")  -- Snapshot management
        table.insert(packages, "snap-pac") -- Pacman hooks for snapshots
    elseif root_fs == "ext4" then
        table.insert(packages, "e2fsprogs")
    elseif root_fs == "xfs" then
        table.insert(packages, "xfsprogs")
    elseif root_fs == "f2fs" then
        table.insert(packages, "f2fs-tools")
    end

    -- Check if home is on different filesystem
    local home_fs = mdots.storage.filesystem("/home")
    if home_fs and home_fs ~= root_fs then
        if home_fs == "btrfs" then
            table.insert(packages, "btrfs-progs")
        elseif home_fs == "ext4" then
            table.insert(packages, "e2fsprogs")
        elseif home_fs == "xfs" then
            table.insert(packages, "xfsprogs")
        end
    end

    return packages
end

-- Get services based on storage configuration
function storage.get_services()
    local services = {
        enabled = {},
        disabled = {}
    }

    -- Enable fstrim timer for SSDs
    if mdots.storage.has_ssd() then
        table.insert(services.enabled, "fstrim.timer")
    end

    return services
end

-- Combine all packages
function storage.get_all_packages()
    local packages = {}

    -- Add SSD packages
    for _, pkg in ipairs(storage.get_ssd_packages()) do
        table.insert(packages, pkg)
    end

    -- Add NVMe packages
    for _, pkg in ipairs(storage.get_nvme_packages()) do
        table.insert(packages, pkg)
    end

    -- Add filesystem packages
    for _, pkg in ipairs(storage.get_filesystem_packages()) do
        table.insert(packages, pkg)
    end

    return packages
end

-- Get storage metadata
function storage.get_metadata()
    local disks = mdots.storage.list_disks()
    local disk_info = {}

    for _, disk in ipairs(disks) do
        local dtype = mdots.storage.disk_type(disk)
        local size = mdots.storage.disk_size(disk)

        table.insert(disk_info, {
            name = disk,
            type = dtype,
            size_gb = size and string.format("%.2f", size / (1024*1024*1024)) or "unknown"
        })
    end

    return {
        hostname = mdots.system.hostname(),
        root_filesystem = mdots.storage.filesystem("/"),
        has_ssd = mdots.storage.has_ssd(),
        has_hdd = mdots.storage.has_hdd(),
        has_nvme = mdots.storage.has_nvme(),
        has_swap = mdots.storage.has_swap(),
        disks = disk_info,
    }
end

-- Export module configuration
return {
    description = "Auto-detected storage configuration for " .. mdots.system.hostname(),
    packages = storage.get_all_packages(),
    services = storage.get_services(),
    metadata = storage.get_metadata(),
}
"#
    .to_string()
}

/// Generate util.lua module with system utilities
pub fn util(paths: &ConfigPaths, force: bool) -> Result<()> {
    // Check for Lua support first
    check_lua_support(paths)?;

    println!("{}", "=== Generate util.lua ===".blue());
    println!();

    let modules_dir = paths.modules_dir();
    let util_file = modules_dir.join("util.lua");

    // Check if file already exists
    if util_file.exists() && !force {
        println!(
            "{} util.lua already exists at: {}",
            "!".yellow(),
            util_file.display()
        );
        print!("Overwrite? [y/N] ");
        io::stdout().flush()?;

        let mut input = String::new();
        io::stdin().read_line(&mut input)?;

        if !input.trim().eq_ignore_ascii_case("y") {
            println!("{}", "Cancelled".yellow());
            return Ok(());
        }
    }

    // Ensure modules directory exists
    fs::create_dir_all(&modules_dir).context("Failed to create modules directory")?;

    // Generate the util.lua content
    let content = generate_util_lua_content();

    // Write the file
    fs::write(&util_file, &content).context("Failed to write util.lua")?;

    println!("{} Created: {}", "✓".green(), util_file.display());
    println!();
    println!("{}", "Utility Module Generated!".green());
    println!();
    println!("This module will automatically install:");
    println!(
        "  {} Network tools based on detected connectivity",
        "•".cyan()
    );
    println!(
        "  {} Audio tools based on detected audio server",
        "•".cyan()
    );
    println!("  {} Desktop environment specific utilities", "•".cyan());
    println!(
        "  {} Boot and security tools based on system configuration",
        "•".cyan()
    );
    println!();
    println!("Next steps:");
    println!(
        "  1. Review the module: {}",
        "cat ~/.config/arch-config/modules/util.lua".cyan()
    );
    println!(
        "  2. Enable the module: {}",
        "mdots module enable util".cyan()
    );
    println!("  3. Preview changes:   {}", "mdots sync --dry-run".cyan());
    println!();

    Ok(())
}

/// Generate the content for util.lua
fn generate_util_lua_content() -> String {
    r#"-- System Utilities Module for mdots
-- This module automatically detects system features and installs appropriate utilities
-- Generated by: mdots generate util

local util = {}

-- Get network utilities
function util.get_network_packages()
    local packages = {}

    -- WiFi tools
    if mdots.network.has_wifi() then
        table.insert(packages, "wireless_tools")
        table.insert(packages, "wpa_supplicant")
        table.insert(packages, "iwd")
    end

    -- Bluetooth tools
    if mdots.network.has_bluetooth() then
        table.insert(packages, "bluez")
        table.insert(packages, "bluez-utils")
    end

    -- Basic network tools
    table.insert(packages, "net-tools")
    table.insert(packages, "inetutils")
    table.insert(packages, "dnsutils")

    return packages
end

-- Get audio utilities
function util.get_audio_packages()
    local packages = {}
    local audio_server = mdots.audio.server()

    if audio_server == "pipewire" then
        table.insert(packages, "pipewire")
        table.insert(packages, "pipewire-pulse")
        table.insert(packages, "pipewire-alsa")
        table.insert(packages, "pipewire-jack")
        table.insert(packages, "wireplumber")
        table.insert(packages, "pavucontrol")  -- GUI for volume control
    elseif audio_server == "pulseaudio" then
        table.insert(packages, "pulseaudio")
        table.insert(packages, "pulseaudio-alsa")
        table.insert(packages, "pavucontrol")
    end

    return packages
end

-- Get desktop environment utilities
function util.get_desktop_packages()
    local packages = {}
    local de = mdots.desktop.environment()

    if mdots.desktop.is_wayland() then
        table.insert(packages, "wl-clipboard")
        table.insert(packages, "xdg-desktop-portal-wlr")
    elseif mdots.desktop.is_x11() then
        table.insert(packages, "xclip")
        table.insert(packages, "xdotool")
        table.insert(packages, "xorg-xrandr")
    end

    -- Add compositor if on X11
    if mdots.desktop.is_x11() and de ~= "kde" and de ~= "gnome" then
        local comp = mdots.desktop.compositor()
        if not comp or comp == "unknown" then
            table.insert(packages, "picom")  -- Default compositor
        end
    end

    return packages
end

-- Get boot utilities
function util.get_boot_packages()
    local packages = {}

    if mdots.boot.is_uefi() then
        table.insert(packages, "efibootmgr")
    end

    local bootloader = mdots.boot.bootloader()
    if bootloader == "grub" then
        table.insert(packages, "grub")
        table.insert(packages, "os-prober")
    elseif bootloader == "systemd-boot" then
        -- systemd-boot is included with systemd
        mdots.log.info("Using systemd-boot")
    end

    return packages
end

-- Get security utilities
function util.get_security_packages()
    local packages = {}

    -- Firewall
    local fw = mdots.security.firewall_type()
    if fw == "ufw" then
        table.insert(packages, "ufw")
    elseif fw == "firewalld" then
        table.insert(packages, "firewalld")
    end

    -- TPM tools
    local tpm = mdots.security.tpm_version()
    if tpm == "2.0" then
        table.insert(packages, "tpm2-tools")
        table.insert(packages, "tpm2-tss")
    end

    -- Encryption tools
    if mdots.security.has_luks() then
        table.insert(packages, "cryptsetup")
    end

    return packages
end

-- Get power management utilities
function util.get_power_packages()
    local packages = {}

    if mdots.hardware.is_laptop() then
        table.insert(packages, "acpi")
        table.insert(packages, "acpi_call")  -- For battery management

        if mdots.power.has_battery() then
            -- Already handled by hardware module typically
            mdots.log.info("Laptop with battery detected")
        end
    end

    return packages
end

-- Combine all packages
function util.get_all_packages()
    local packages = {}

    -- Add network packages
    for _, pkg in ipairs(util.get_network_packages()) do
        table.insert(packages, pkg)
    end

    -- Add audio packages
    for _, pkg in ipairs(util.get_audio_packages()) do
        table.insert(packages, pkg)
    end

    -- Add desktop packages
    for _, pkg in ipairs(util.get_desktop_packages()) do
        table.insert(packages, pkg)
    end

    -- Add boot packages
    for _, pkg in ipairs(util.get_boot_packages()) do
        table.insert(packages, pkg)
    end

    -- Add security packages
    for _, pkg in ipairs(util.get_security_packages()) do
        table.insert(packages, pkg)
    end

    -- Add power packages
    for _, pkg in ipairs(util.get_power_packages()) do
        table.insert(packages, pkg)
    end

    return packages
end

-- Get services
function util.get_services()
    local services = {
        enabled = {},
        disabled = {}
    }

    -- Bluetooth service
    if mdots.network.has_bluetooth() then
        table.insert(services.enabled, "bluetooth.service")
    end

    return services
end

-- Get system metadata
function util.get_metadata()
    return {
        hostname = mdots.system.hostname(),
        desktop = mdots.desktop.environment(),
        display_server = mdots.desktop.display_server(),
        audio_server = mdots.audio.server(),
        bootloader = mdots.boot.bootloader(),
        init_system = mdots.boot.init_system(),
        is_uefi = mdots.boot.is_uefi(),
        has_wifi = mdots.network.has_wifi(),
        has_bluetooth = mdots.network.has_bluetooth(),
    }
end

-- Export module configuration
return {
    description = "Auto-detected system utilities for " .. mdots.system.hostname(),
    packages = util.get_all_packages(),
    services = util.get_services(),
    metadata = util.get_metadata(),
}
"#
    .to_string()
}
