//! Game Mode orchestration.
//!
//! One toggle that, while engaged: drops compositor effects (animations / blur
//! / shadows, optional tearing) via a managed `conf.d/gamemode.conf` fragment
//! margo sources after `config.conf` so it wins; turns on Do Not Disturb; and
//! holds the idle inhibitor so the session stays awake. Turning it off clears
//! the fragment (restoring the original config values), restores DND, and
//! releases the inhibitor — back to whatever the user had before.
//!
//! Call [`apply`] from the GTK main thread (it reads no reactive state itself,
//! but the caller updates `config.game_mode.active` there, and the idle
//! inhibitor's async enable/disable is spawned on the glib main context).

use mshell_config::schema::config::GameMode;
use mshell_idle::inhibitor::IdleInhibitor;
use mshell_services::notification_service;
use std::path::PathBuf;
use std::sync::Mutex;

/// The idle-inhibitor state to restore when game mode turns off — captured when
/// it turns on, so we hand control back instead of clobbering a manual hold
/// (the keep-awake widget). Mirrors the audio-inhibit remember/restore pattern.
static IDLE_RESTORE: Mutex<Option<bool>> = Mutex::new(None);

fn margo_dir() -> PathBuf {
    let base = std::env::var_os("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .or_else(|| std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".config")))
        .unwrap_or_default();
    base.join("margo")
}

fn fragment_path() -> PathBuf {
    margo_dir().join("conf.d").join("gamemode.conf")
}

/// `true` if `config.conf` already `source`s our fragment (whitespace-tolerant).
fn config_sources_us(text: &str) -> bool {
    text.lines()
        .map(str::trim)
        .filter(|l| !l.starts_with('#'))
        .any(|l| {
            l.strip_prefix("source")
                .map(str::trim_start)
                .and_then(|r| r.strip_prefix('='))
                .map(|v| v.contains("gamemode.conf"))
                .unwrap_or(false)
        })
}

/// Write the effects fragment (overrides when `on`, header-only when off) and
/// make sure `config.conf` sources it once. `Err` with a message if any file
/// write fails.
fn write_fragment(cfg: &GameMode, on: bool) -> Result<(), String> {
    let dir = margo_dir();
    let frag = fragment_path();
    if let Some(parent) = frag.parent() {
        std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }

    let mut body = String::from(
        "# Generated by mshell — Game Mode (Settings → Game Mode / `mshellctl\n\
         # gamemode`). Sourced after config.conf so it overrides while game\n\
         # mode is on; cleared (no overrides below) when it's off.\n\n",
    );
    if on {
        if cfg.disable_animations {
            body.push_str("animations = 0\nlayer_animations = 0\n");
        }
        if cfg.disable_blur {
            body.push_str("blur = 0\n");
        }
        if cfg.disable_shadows {
            body.push_str("shadows = 0\nlayer_shadows = 0\n");
        }
        if cfg.allow_tearing {
            body.push_str("allow_tearing = 1\n");
        }
    }
    std::fs::write(&frag, body).map_err(|e| e.to_string())?;

    let config_conf = dir.join("config.conf");
    let current = std::fs::read_to_string(&config_conf).unwrap_or_default();
    if !config_sources_us(&current) {
        let mut updated = current;
        if !updated.ends_with('\n') && !updated.is_empty() {
            updated.push('\n');
        }
        updated.push_str(
            "\n# Game Mode effect overrides (managed by mshell).\nsource = conf.d/gamemode.conf\n",
        );
        std::fs::write(&config_conf, updated).map_err(|e| e.to_string())?;
    }
    Ok(())
}

fn reload() {
    if let Err(e) = std::process::Command::new("mctl").arg("reload").spawn() {
        tracing::warn!(error = %e, "game mode: `mctl reload` failed to spawn");
    }
}

fn spawn_idle(enable: bool) {
    relm4::gtk::glib::spawn_future_local(async move {
        if enable {
            if let Err(e) = IdleInhibitor::global().enable().await {
                tracing::warn!(error = %e, "game mode: enabling idle inhibitor failed");
            }
        } else {
            IdleInhibitor::global().disable().await;
        }
    });
}

/// Apply game mode on/off. Writes the effects fragment + reloads margo, toggles
/// DND, and holds/releases the idle inhibitor — each gated on its config
/// switch. Idempotent.
pub fn apply(cfg: &GameMode, on: bool) {
    match write_fragment(cfg, on) {
        Ok(()) => reload(),
        Err(e) => tracing::warn!(error = %e, "game mode: writing effects fragment failed"),
    }

    if cfg.enable_dnd {
        notification_service().set_dnd(on);
    }

    if cfg.inhibit_idle {
        if on {
            let restore = IdleInhibitor::global().get();
            if let Ok(mut g) = IDLE_RESTORE.lock() {
                *g = Some(restore);
            }
            // Only engage if it wasn't already held (by the user).
            if !restore {
                spawn_idle(true);
            }
        } else {
            // Restore the pre-game-mode state; default to releasing.
            let restore = IDLE_RESTORE
                .lock()
                .ok()
                .and_then(|mut g| g.take())
                .unwrap_or(false);
            if !restore {
                spawn_idle(false);
            }
        }
    }
}
