use anyhow::{bail, Result};

use super::SourceConfig;

/// Generate a PKGBUILD string from a SourceConfig
pub fn generate_pkgbuild(cfg: &SourceConfig) -> Result<String> {
    // Validate the fields that must be literal values, so a crafted source
    // config (e.g. from a downloaded module) cannot break out of the generated
    // PKGBUILD. NOTE: build_commands/package_commands are intentionally raw
    // shell — that is what they are for — and are deliberately NOT escaped.
    validate_pkgname(&cfg.name)?;
    if let Some(branch) = &cfg.branch {
        validate_git_ref(branch)?;
    }
    for dep in cfg
        .dependencies
        .iter()
        .chain(cfg.runtime_dependencies.iter())
    {
        if dep.contains('\n') || dep.contains('\r') {
            bail!("Invalid dependency {:?}: must not contain newlines", dep);
        }
    }

    // Derive srcdir name from the git repo (last path component without .git)
    let repo_raw = cfg
        .url
        .trim_end_matches('/')
        .trim_end_matches(".git")
        .rsplit('/')
        .next()
        .unwrap_or(&cfg.name);
    let repo_name = escape_double_quoted(repo_raw);
    let url = escape_double_quoted(&cfg.url);

    // Format source line (branch already validated to a safe charset)
    let source_fragment = if let Some(branch) = &cfg.branch {
        format!("\"git+{}#branch={}\"", url, branch)
    } else {
        format!("\"git+{}\"", url)
    };

    // Build commands indented inside build()
    let build_body = build_function_body(&repo_name, &cfg.build_commands);

    // Package commands indented inside package()
    let package_body = build_function_body(&repo_name, &cfg.package_commands);

    let makedepends_line = dep_array_line("makedepends", &cfg.dependencies);
    let depends_line = dep_array_line("depends", &cfg.runtime_dependencies);

    let mut pkgbuild = format!(
        r#"# Generated by dcli — do not edit manually
pkgname={name}
pkgver=0
pkgrel=1
pkgdesc="{desc}"
arch=('x86_64')
url="{url}"
{makedepends}{depends}source=({source})
sha256sums=('SKIP')

pkgver() {{
    cd "$srcdir/{repo}"
    git describe --long --tags --abbrev=7 2>/dev/null \
        | sed 's/\([^-]*-g\)/r\1/;s/-/./g' \
        || printf "r%s.g%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short=7 HEAD)"
}}

build() {{
{build_body}
}}

package() {{
{package_body}
}}
"#,
        name = cfg.name,
        desc = escape_double_quoted(&cfg.description),
        url = url,
        makedepends = makedepends_line,
        depends = depends_line,
        source = source_fragment,
        repo = repo_name,
        build_body = build_body,
        package_body = package_body,
    );

    pkgbuild = pkgbuild.trim_end().to_string();
    pkgbuild.push('\n');
    Ok(pkgbuild)
}

fn dep_array_line(field: &str, deps: &[String]) -> String {
    if deps.is_empty() {
        return String::new();
    }
    let items: Vec<String> = deps
        .iter()
        .map(|d| format!("'{}'", escape_single_quoted(d)))
        .collect();
    format!("{}=({})\n", field, items.join(" "))
}

fn build_function_body(repo_name: &str, commands: &[String]) -> String {
    let mut lines = format!("    cd \"$srcdir/{}\"", repo_name);
    for cmd in commands {
        lines.push('\n');
        lines.push_str("    ");
        lines.push_str(cmd);
    }
    lines
}

/// Validate an Arch package name. Allowed: alphanumerics and `@ . _ + -`,
/// and it must start with an alphanumeric. This keeps the (often unquoted)
/// `pkgname=` and dependency fields free of shell metacharacters.
fn validate_pkgname(name: &str) -> Result<()> {
    match name.chars().next() {
        Some(c) if c.is_ascii_alphanumeric() => {}
        _ => bail!(
            "Invalid package name {:?}: must start with an alphanumeric character",
            name
        ),
    }
    if let Some(bad) = name
        .chars()
        .find(|c| !(c.is_ascii_alphanumeric() || matches!(c, '@' | '.' | '_' | '+' | '-')))
    {
        bail!(
            "Invalid package name {:?}: character {:?} is not allowed (use [A-Za-z0-9@._+-])",
            name,
            bad
        );
    }
    Ok(())
}

/// Validate a git ref (branch / tag / commit). Allowed: alphanumerics and
/// `. _ / + -`, and it must not start with '-'. Keeps the `source=()` line
/// injection-free.
fn validate_git_ref(r: &str) -> Result<()> {
    if r.is_empty() || r.starts_with('-') {
        bail!("Invalid branch/ref {:?}", r);
    }
    if let Some(bad) = r
        .chars()
        .find(|c| !(c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '/' | '+' | '-')))
    {
        bail!(
            "Invalid branch/ref {:?}: character {:?} is not allowed",
            r,
            bad
        );
    }
    Ok(())
}

/// Escape a string for a double-quoted bash context (pkgdesc, url, paths).
fn escape_double_quoted(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '$' => out.push_str("\\$"),
            '`' => out.push_str("\\`"),
            '\n' | '\r' => {} // drop newlines so values stay on a single line
            _ => out.push(c),
        }
    }
    out
}

/// Escape a string for a single-quoted bash context (`'...'`), used for deps.
fn escape_single_quoted(s: &str) -> String {
    s.replace('\'', "'\\''")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cfg(name: &str) -> SourceConfig {
        SourceConfig {
            name: name.to_string(),
            description: String::new(),
            url: "https://example.com/repo.git".to_string(),
            branch: None,
            dependencies: vec![],
            runtime_dependencies: vec![],
            build_commands: vec![],
            package_commands: vec![],
            custom_pkgbuild: None,
            cache_builds: false,
        }
    }

    #[test]
    fn test_valid_config_generates_pkgbuild() {
        let out = generate_pkgbuild(&cfg("mypkg")).expect("valid config should generate");
        assert!(out.contains("pkgname=mypkg"));
    }

    #[test]
    fn test_rejects_pkgname_with_shell_metacharacters() {
        // An unquoted `pkgname=...` must never accept shell metacharacters.
        assert!(generate_pkgbuild(&cfg("evil; rm -rf ~")).is_err());
        assert!(generate_pkgbuild(&cfg("pkg$(whoami)")).is_err());
        assert!(generate_pkgbuild(&cfg("")).is_err());
    }

    #[test]
    fn test_rejects_branch_injection() {
        let mut c = cfg("mypkg");
        c.branch = Some("v1\"; echo pwned #".to_string());
        assert!(generate_pkgbuild(&c).is_err());
    }

    #[test]
    fn test_escapes_description_shell_chars() {
        let mut c = cfg("mypkg");
        c.description = "owns $(whoami) and `id`".to_string();
        let out = generate_pkgbuild(&c).expect("should generate");
        // The dangerous expansions must be neutralised inside the double-quoted pkgdesc.
        assert!(out.contains("\\$(whoami)"), "dollar must be escaped: {out}");
        assert!(out.contains("\\`id\\`"), "backticks must be escaped: {out}");
    }

    #[test]
    fn test_escapes_dependency_single_quote() {
        let mut c = cfg("mypkg");
        c.dependencies = vec!["evil'; rm -rf ~ #".to_string()];
        let out = generate_pkgbuild(&c).expect("should generate");
        // Single quotes in a '...'-wrapped dep must be escaped as '\'' so they
        // cannot break out of the quoting.
        assert!(out.contains("'\\''"), "single quote must be escaped: {out}");
    }

    #[test]
    fn test_build_commands_passed_verbatim() {
        // build_commands ARE user-authored shell by design and must NOT be escaped.
        let mut c = cfg("mypkg");
        c.build_commands = vec!["make && make DESTDIR=\"$pkgdir\" install".to_string()];
        let out = generate_pkgbuild(&c).expect("should generate");
        assert!(out.contains("make && make DESTDIR=\"$pkgdir\" install"));
    }
}
