pub mod style_manager;
pub mod user_css;

/// The compiled CSS (generated by build.rs into OUT_DIR).
pub fn compiled_css() -> &'static str {
    include_str!(concat!(env!("OUT_DIR"), "/mshell-style.css"))
}
