[preferred]
default=gtk
org.freedesktop.impl.portal.FileChooser=gtk
org.freedesktop.impl.portal.OpenURI=gtk
org.freedesktop.impl.portal.AppChooser=gtk
org.freedesktop.impl.portal.Notification=gtk
org.freedesktop.impl.portal.Settings=gtk
org.freedesktop.impl.portal.Secret=gnome-keyring
org.freedesktop.impl.portal.GlobalShortcuts=none
org.freedesktop.impl.portal.Inhibit=gtk
org.freedesktop.impl.portal.ScreenCast=none
org.freedesktop.impl.portal.Screenshot=none
org.freedesktop.impl.portal.RemoteDesktop=none
