//! Settings → On-Screen Keyboard.
//!
//! Edits `~/.config/margo/mkeys.toml`, the config the standalone `mkeys`
//! binary re-reads every time it is shown. The file is a flat 6-key TOML, so
//! it is hand-read/written here (mirroring `mkeys::config::Config`) rather than
//! pulling the whole mkeys crate — with its wayland/virtual-keyboard graph —
//! into the settings crate.

use crate::row::Row;
use relm4::gtk::prelude::*;
use relm4::{Component, ComponentParts, ComponentSender, gtk};
use std::path::PathBuf;

#[derive(Debug, Clone)]
struct KbConfig {
    layout: String,
    scale: f32,
    position: String,
    opacity: f32,
    margin: i32,
    show_pill: bool,
}

impl Default for KbConfig {
    fn default() -> Self {
        Self {
            layout: "en".into(),
            scale: 1.0,
            position: "bottom".into(),
            opacity: 0.95,
            margin: 8,
            show_pill: true,
        }
    }
}

fn config_path() -> PathBuf {
    let base = std::env::var_os("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            let mut home = PathBuf::from(std::env::var_os("HOME").unwrap_or_default());
            home.push(".config");
            home
        });
    base.join("margo").join("mkeys.toml")
}

impl KbConfig {
    fn load() -> Self {
        let mut cfg = KbConfig::default();
        let Ok(text) = std::fs::read_to_string(config_path()) else {
            return cfg;
        };
        for line in text.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let Some((key, val)) = line.split_once('=') else {
                continue;
            };
            let key = key.trim();
            let val = val.trim().trim_matches(|c| c == '"' || c == '\'');
            match key {
                "layout" => cfg.layout = val.to_string(),
                "position" => cfg.position = val.to_string(),
                "scale" => {
                    if let Ok(v) = val.parse() {
                        cfg.scale = v;
                    }
                }
                "opacity" => {
                    if let Ok(v) = val.parse() {
                        cfg.opacity = v;
                    }
                }
                "margin" => {
                    if let Ok(v) = val.parse() {
                        cfg.margin = v;
                    }
                }
                "show_pill" => cfg.show_pill = val == "true",
                _ => {}
            }
        }
        cfg
    }

    fn save(&self) {
        let path = config_path();
        if let Some(dir) = path.parent() {
            let _ = std::fs::create_dir_all(dir);
        }
        let body = format!(
            "# Generated by margo Settings → On-Screen Keyboard.\n\
             layout = \"{}\"\n\
             scale = {}\n\
             position = \"{}\"\n\
             opacity = {}\n\
             margin = {}\n\
             show_pill = {}\n",
            self.layout, self.scale, self.position, self.opacity, self.margin, self.show_pill
        );
        if let Err(e) = std::fs::write(&path, body) {
            tracing::warn!(error = %e, "mkeys settings: failed to write mkeys.toml");
        }
    }
}

#[derive(Debug)]
pub(crate) struct KeyboardSettingsModel {
    cfg: KbConfig,
    layouts: gtk::StringList,
    positions: gtk::StringList,
    layout_index: u32,
    position_index: u32,
}

#[derive(Debug)]
pub(crate) enum KeyboardSettingsInput {
    SetLayout(u32),
    SetPosition(u32),
    SetScale(f64),
    SetOpacity(f64),
    SetMargin(f64),
    SetShowPill(bool),
}

#[derive(Debug)]
pub(crate) enum KeyboardSettingsOutput {}

pub(crate) struct KeyboardSettingsInit {}

#[derive(Debug)]
pub(crate) enum KeyboardSettingsCommandOutput {}

#[relm4::component(pub)]
impl Component for KeyboardSettingsModel {
    type CommandOutput = KeyboardSettingsCommandOutput;
    type Input = KeyboardSettingsInput;
    type Output = KeyboardSettingsOutput;
    type Init = KeyboardSettingsInit;

    view! {
        #[root]
        gtk::ScrolledWindow {
            set_vscrollbar_policy: gtk::PolicyType::Automatic,
            set_hscrollbar_policy: gtk::PolicyType::Never,
            set_hexpand: true,
            set_vexpand: true,

            gtk::Box {
                add_css_class: "settings-page",
                set_orientation: gtk::Orientation::Vertical,
                set_hexpand: true,
                set_spacing: 16,

                gtk::Box {
                    add_css_class: "settings-hero",
                    set_orientation: gtk::Orientation::Horizontal,
                    set_halign: gtk::Align::Start,
                    set_spacing: 16,
                    gtk::Image {
                        add_css_class: "settings-hero-icon",
                        set_icon_name: Some("input-keyboard-symbolic"),
                        set_valign: gtk::Align::Center,
                    },
                    gtk::Box {
                        set_orientation: gtk::Orientation::Vertical,
                        set_valign: gtk::Align::Center,
                        gtk::Label {
                            add_css_class: "settings-hero-title",
                            set_label: "On-Screen Keyboard",
                            set_halign: gtk::Align::Start,
                        },
                        gtk::Label {
                            add_css_class: "settings-hero-subtitle",
                            set_label: "mkeys — a tap keyboard that types into the focused window. Toggle it with the keyboard bar pill or `mkeys toggle`.",
                            set_halign: gtk::Align::Start,
                            set_xalign: 0.0,
                            set_wrap: true,
                        },
                    },
                },

                gtk::Label {
                    add_css_class: "label-large-bold",
                    set_label: "Layout & placement",
                    set_halign: gtk::Align::Start,
                },

                #[template]
                Row {
                    #[template_child] title { set_label: "Keyboard layout" },
                    #[template_child] desc { set_label: "Turkish-Q needs margo's xkb layout set to tr." },
                    gtk::DropDown {
                        set_valign: gtk::Align::Center,
                        set_width_request: 180,
                        set_model: Some(&model.layouts),
                        #[block_signal(layout_handler)]
                        set_selected: model.layout_index,
                        connect_selected_notify[sender] => move |d| {
                            sender.input(KeyboardSettingsInput::SetLayout(d.selected()));
                        } @layout_handler,
                    },
                },

                #[template]
                Row {
                    #[template_child] title { set_label: "Position" },
                    #[template_child] desc { set_label: "Which screen edge the keyboard docks to." },
                    gtk::DropDown {
                        set_valign: gtk::Align::Center,
                        set_width_request: 180,
                        set_model: Some(&model.positions),
                        #[block_signal(position_handler)]
                        set_selected: model.position_index,
                        connect_selected_notify[sender] => move |d| {
                            sender.input(KeyboardSettingsInput::SetPosition(d.selected()));
                        } @position_handler,
                    },
                },

                #[template]
                Row {
                    #[template_child] title { set_label: "Key size" },
                    #[template_child] desc { set_label: "Scale of each key (1.0 = default)." },
                    gtk::SpinButton {
                        set_valign: gtk::Align::Center,
                        set_digits: 2,
                        set_adjustment: &gtk::Adjustment::new(model.cfg.scale as f64, 0.5, 2.0, 0.1, 0.1, 0.0),
                        connect_value_changed[sender] => move |s| {
                            sender.input(KeyboardSettingsInput::SetScale(s.value()));
                        },
                    },
                },

                #[template]
                Row {
                    #[template_child] title { set_label: "Opacity" },
                    #[template_child] desc { set_label: "Keyboard transparency (1.0 = opaque)." },
                    gtk::SpinButton {
                        set_valign: gtk::Align::Center,
                        set_digits: 2,
                        set_adjustment: &gtk::Adjustment::new(model.cfg.opacity as f64, 0.5, 1.0, 0.05, 0.05, 0.0),
                        connect_value_changed[sender] => move |s| {
                            sender.input(KeyboardSettingsInput::SetOpacity(s.value()));
                        },
                    },
                },

                #[template]
                Row {
                    #[template_child] title { set_label: "Edge margin" },
                    #[template_child] desc { set_label: "Gap from the screen edge, in pixels." },
                    gtk::SpinButton {
                        set_valign: gtk::Align::Center,
                        set_digits: 0,
                        set_adjustment: &gtk::Adjustment::new(model.cfg.margin as f64, 0.0, 64.0, 1.0, 4.0, 0.0),
                        connect_value_changed[sender] => move |s| {
                            sender.input(KeyboardSettingsInput::SetMargin(s.value()));
                        },
                    },
                },

                #[template]
                Row {
                    #[template_child] title { set_label: "Show bar pill" },
                    #[template_child] desc { set_label: "Hint for the keyboard bar pill (add it to a bar slot in Bar settings)." },
                    gtk::Switch {
                        set_valign: gtk::Align::Center,
                        #[block_signal(pill_handler)]
                        set_active: model.cfg.show_pill,
                        connect_active_notify[sender] => move |s| {
                            sender.input(KeyboardSettingsInput::SetShowPill(s.is_active()));
                        } @pill_handler,
                    },
                },
            }
        }
    }

    fn init(
        _params: Self::Init,
        root: Self::Root,
        sender: ComponentSender<Self>,
    ) -> ComponentParts<Self> {
        let _ = &sender;
        let cfg = KbConfig::load();
        let layouts = gtk::StringList::new(&["en", "tr"]);
        let positions = gtk::StringList::new(&["bottom", "top"]);
        let layout_index = if cfg.layout == "tr" { 1 } else { 0 };
        let position_index = if cfg.position == "top" { 1 } else { 0 };
        let model = KeyboardSettingsModel {
            cfg,
            layouts,
            positions,
            layout_index,
            position_index,
        };
        let widgets = view_output!();
        let _ = root;
        ComponentParts { model, widgets }
    }

    fn update(&mut self, message: Self::Input, _sender: ComponentSender<Self>, _root: &Self::Root) {
        match message {
            KeyboardSettingsInput::SetLayout(idx) => {
                self.layout_index = idx;
                self.cfg.layout = if idx == 1 { "tr" } else { "en" }.to_string();
            }
            KeyboardSettingsInput::SetPosition(idx) => {
                self.position_index = idx;
                self.cfg.position = if idx == 1 { "top" } else { "bottom" }.to_string();
            }
            KeyboardSettingsInput::SetScale(v) => self.cfg.scale = v as f32,
            KeyboardSettingsInput::SetOpacity(v) => self.cfg.opacity = v as f32,
            KeyboardSettingsInput::SetMargin(v) => self.cfg.margin = v.round() as i32,
            KeyboardSettingsInput::SetShowPill(v) => self.cfg.show_pill = v,
        }
        self.cfg.save();
    }
}
