//! Display → Tiling Layout sub-page — assign a default tiling layout to each
//! tag.
//!
//! Unlike the sibling `layout_settings` page (which drives `mlayout`, the
//! *monitor* arrangement tool), this edits the compositor's per-tag *tiling*
//! layout. mshell owns a managed `~/.config/margo/taglayouts.conf` of
//! `taglayout = <tag>, <name>` lines plus a `taglayout_force` flag, ensures the
//! user's `config.conf` `source`s it, and asks margo to reload. margo seeds
//! each tag's layout from these on startup (and re-applies them every start
//! when "force" is on — otherwise the session's live layouts win).

use relm4::gtk::prelude::{BoxExt, ButtonExt, OrientableExt, WidgetExt};
use relm4::gtk::glib;
use relm4::{Component, ComponentParts, ComponentSender, gtk};
use std::path::PathBuf;

/// The 14 tiling layouts, in `LayoutId` order. Index 0 of the dropdown is a
/// synthetic "(default)" that writes no line (the tag inherits `default_layout`).
const LAYOUTS: &[&str] = &[
    "tile",
    "scroller",
    "grid",
    "monocle",
    "deck",
    "center_tile",
    "right_tile",
    "vertical_tile",
    "vertical_scroller",
    "vertical_grid",
    "vertical_deck",
    "tgmix",
    "canvas",
    "dwindle",
];

const TAGS: usize = 9;

pub(crate) struct TagLayoutSettingsModel {
    /// Per-tag dropdown selection: 0 = "(default)", else `LAYOUTS[sel-1]`.
    selections: [usize; TAGS],
    force: bool,
    status: String,
}

#[derive(Debug)]
pub(crate) enum TagLayoutSettingsInput {
    TagChanged(usize, usize), // (tag index 0-based, dropdown selection)
    ForceChanged(bool),
    Apply,
}

#[derive(Debug)]
pub(crate) enum TagLayoutSettingsOutput {}

pub(crate) struct TagLayoutSettingsInit {}

#[derive(Debug)]
pub(crate) enum TagLayoutSettingsCommandOutput {}

// ── config paths + I/O ──────────────────────────────────────────────────────

fn margo_dir() -> PathBuf {
    dirs::config_dir()
        .unwrap_or_else(|| PathBuf::from(std::env::var("HOME").unwrap_or_default()).join(".config"))
        .join("margo")
}

fn taglayouts_path() -> PathBuf {
    margo_dir().join("taglayouts.conf")
}

/// Read the managed file back into (selections, force).
fn read_state() -> ([usize; TAGS], bool) {
    let mut selections = [0usize; TAGS];
    let mut force = false;
    let Ok(text) = std::fs::read_to_string(taglayouts_path()) else {
        return (selections, force);
    };
    for line in text.lines() {
        let line = line.trim();
        if line.starts_with('#') {
            continue;
        }
        if let Some(rest) = line.strip_prefix("taglayout_force") {
            if let Some(v) = rest.trim_start().strip_prefix('=') {
                force = matches!(v.trim(), "true" | "1" | "yes" | "on");
            }
        } else if let Some(rest) = line.strip_prefix("taglayout") {
            // `taglayout = <tag>, <name>`
            if let Some(v) = rest.trim_start().strip_prefix('=') {
                if let Some((t, name)) = v.split_once(',') {
                    if let Ok(tag) = t.trim().parse::<usize>() {
                        let name = name.trim();
                        if (1..=TAGS).contains(&tag) {
                            if let Some(idx) = LAYOUTS.iter().position(|l| *l == name) {
                                selections[tag - 1] = idx + 1;
                            }
                        }
                    }
                }
            }
        }
    }
    (selections, force)
}

/// `true` if `config.conf` already `source`s our file (whitespace-tolerant).
fn config_sources_us(text: &str) -> bool {
    text.lines()
        .map(str::trim)
        .filter(|l| !l.starts_with('#'))
        .any(|l| {
            l.strip_prefix("source")
                .map(str::trim_start)
                .and_then(|r| r.strip_prefix('='))
                .map(|v| v.contains("taglayouts.conf"))
                .unwrap_or(false)
        })
}

fn write_and_reload(selections: &[usize; TAGS], force: bool) -> Result<(), String> {
    let dir = margo_dir();
    std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;

    let mut body = String::from(
        "# Generated by mshell — Settings → Display → Tiling Layout.\n\
         # Per-tag default tiling layout. `taglayout_force = true` re-applies\n\
         # these on every margo start; false only seeds them (your live\n\
         # layout changes are then kept by the session).\n\n",
    );
    for (i, sel) in selections.iter().enumerate() {
        if *sel >= 1 {
            body.push_str(&format!("taglayout = {}, {}\n", i + 1, LAYOUTS[*sel - 1]));
        }
    }
    body.push_str(&format!("\ntaglayout_force = {force}\n"));
    std::fs::write(taglayouts_path(), body).map_err(|e| e.to_string())?;

    // Make sure config.conf pulls it in (append once).
    let config_conf = dir.join("config.conf");
    let current = std::fs::read_to_string(&config_conf).unwrap_or_default();
    if !config_sources_us(&current) {
        let mut updated = current;
        if !updated.ends_with('\n') && !updated.is_empty() {
            updated.push('\n');
        }
        updated.push_str("\n# Per-tag tiling layouts (managed by mshell).\nsource = taglayouts.conf\n");
        std::fs::write(&config_conf, updated).map_err(|e| e.to_string())?;
    }

    // Ask margo to reload.
    let out = std::process::Command::new("mctl")
        .arg("reload")
        .output()
        .map_err(|e| format!("mctl reload: {e}"))?;
    if !out.status.success() {
        return Err(format!(
            "mctl reload failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        ));
    }
    Ok(())
}

// ── Component ────────────────────────────────────────────────────────────────

#[relm4::component(pub)]
impl Component for TagLayoutSettingsModel {
    type CommandOutput = TagLayoutSettingsCommandOutput;
    type Input = TagLayoutSettingsInput;
    type Output = TagLayoutSettingsOutput;
    type Init = TagLayoutSettingsInit;

    view! {
        #[root]
        gtk::ScrolledWindow {
            set_vscrollbar_policy: gtk::PolicyType::Automatic,
            set_hscrollbar_policy: gtk::PolicyType::Never,
            set_hexpand: true,
            set_vexpand: true,

            gtk::Box {
                add_css_class: "settings-page",
                set_orientation: gtk::Orientation::Vertical,
                set_hexpand: true,
                set_spacing: 16,

                gtk::Box {
                    add_css_class: "settings-hero",
                    set_orientation: gtk::Orientation::Horizontal,
                    set_halign: gtk::Align::Start,
                    set_spacing: 16,
                    gtk::Image {
                        add_css_class: "settings-hero-icon",
                        set_icon_name: Some("view-grid-symbolic"),
                        set_valign: gtk::Align::Center,
                    },
                    gtk::Box {
                        set_orientation: gtk::Orientation::Vertical,
                        set_valign: gtk::Align::Center,
                        gtk::Label {
                            add_css_class: "settings-hero-title",
                            set_label: "Tiling Layout",
                            set_halign: gtk::Align::Start,
                        },
                        gtk::Label {
                            add_css_class: "settings-hero-subtitle",
                            set_label: "Give each tag its own default tiling layout.",
                            set_halign: gtk::Align::Start,
                            set_xalign: 0.0,
                            set_wrap: true,
                        },
                    },
                },

                gtk::Label {
                    add_css_class: "label-small",
                    set_label: "“(default)” leaves a tag on the global default_layout. Changes apply when margo (re)starts; with “Force on startup” off, any layout you switch to live is kept by the session instead.",
                    set_halign: gtk::Align::Start,
                    set_xalign: 0.0,
                    set_wrap: true,
                    set_natural_wrap_mode: gtk::NaturalWrapMode::None,
                },

                // Per-tag rows are built in init().
                #[name = "tags_box"]
                gtk::Box {
                    set_orientation: gtk::Orientation::Vertical,
                    set_spacing: 8,
                },

                gtk::Box {
                    set_orientation: gtk::Orientation::Horizontal,
                    set_spacing: 20,
                    gtk::Box {
                        set_orientation: gtk::Orientation::Vertical,
                        set_hexpand: true,
                        gtk::Label {
                            add_css_class: "label-medium-bold",
                            set_halign: gtk::Align::Start,
                            set_label: "Force on startup",
                        },
                        gtk::Label {
                            add_css_class: "label-small",
                            set_halign: gtk::Align::Start,
                            set_label: "Re-apply these layouts on every start, overriding live changes.",
                            set_xalign: 0.0,
                            set_wrap: true,
                        },
                    },
                    gtk::Switch {
                        set_valign: gtk::Align::Center,
                        #[watch]
                        #[block_signal(force_handler)]
                        set_active: model.force,
                        connect_state_set[sender] => move |_, v| {
                            sender.input(TagLayoutSettingsInput::ForceChanged(v));
                            glib::Propagation::Proceed
                        } @force_handler,
                    },
                },

                gtk::Button {
                    add_css_class: "ok-button-primary",
                    set_halign: gtk::Align::Start,
                    set_label: "Apply",
                    connect_clicked => TagLayoutSettingsInput::Apply,
                },

                gtk::Label {
                    add_css_class: "label-small",
                    set_halign: gtk::Align::Start,
                    set_xalign: 0.0,
                    set_wrap: true,
                    #[watch]
                    set_label: &model.status,
                    #[watch]
                    set_visible: !model.status.is_empty(),
                },
            }
        }
    }

    fn init(
        _params: Self::Init,
        root: Self::Root,
        sender: ComponentSender<Self>,
    ) -> ComponentParts<Self> {
        let (selections, force) = read_state();
        let model = TagLayoutSettingsModel {
            selections,
            force,
            status: String::new(),
        };

        let widgets = view_output!();

        // Build a row per tag: "Tag N" + a layout dropdown.
        let mut options: Vec<&str> = Vec::with_capacity(LAYOUTS.len() + 1);
        options.push("(default)");
        options.extend_from_slice(LAYOUTS);
        for tag in 0..TAGS {
            let row = gtk::Box::new(gtk::Orientation::Horizontal, 20);
            let label = gtk::Label::new(Some(&format!("Tag {}", tag + 1)));
            label.add_css_class("label-medium-bold");
            label.set_halign(gtk::Align::Start);
            label.set_hexpand(true);
            row.append(&label);

            let dd = gtk::DropDown::from_strings(&options);
            dd.set_valign(gtk::Align::Center);
            dd.set_selected(model.selections[tag] as u32);
            let s = sender.clone();
            dd.connect_selected_notify(move |d| {
                s.input(TagLayoutSettingsInput::TagChanged(tag, d.selected() as usize));
            });
            row.append(&dd);
            widgets.tags_box.append(&row);
        }

        ComponentParts { model, widgets }
    }

    fn update_with_view(
        &mut self,
        widgets: &mut Self::Widgets,
        message: Self::Input,
        sender: ComponentSender<Self>,
        _root: &Self::Root,
    ) {
        match message {
            TagLayoutSettingsInput::TagChanged(tag, sel) => {
                if tag < TAGS {
                    self.selections[tag] = sel;
                }
            }
            TagLayoutSettingsInput::ForceChanged(v) => self.force = v,
            TagLayoutSettingsInput::Apply => {
                self.status = match write_and_reload(&self.selections, self.force) {
                    Ok(()) => "Applied — your tags switch to these layouts now. With Force on startup off, a layout you later change live is kept by the session.".to_string(),
                    Err(e) => format!("Couldn't apply: {e}"),
                };
            }
        }
        self.update_view(widgets, sender);
    }
}
