use crate::json_struct::MatugenTheme;

/// Emit the colour roles `mlogind` (margo's TUI login manager) reads as
/// `$`-variables in its `variables.toml`. Maps the Material palette onto
/// the greeter's theming slots so the login screen matches the wallpaper.
/// Must stay in sync with `mlogind/extra/config.toml`'s `$`-names.
pub fn to_mlogind_variables(theme: &MatugenTheme) -> String {
    let c = &theme.colors;
    let mode = &theme.mode;
    macro_rules! col {
        ($field:expr) => {
            match mode.as_str() {
                "dark" => &$field.dark.color,
                "light" => &$field.light.color,
                _ => &$field.default.color,
            }
        };
    }
    format!(
        "# Generated by margo's matugen — mlogind colour variables.\n\
         # Overwritten on every wallpaper/theme change; `mlogind sync-theme`\n\
         # copies this into /etc/mlogind/variables.toml for the greeter.\n\
         bg           = \"{bg}\"\n\
         panel_border = \"{panel_border}\"\n\
         field_border = \"{field_border}\"\n\
         text         = \"{text}\"\n\
         subtext      = \"{subtext}\"\n\
         muted        = \"{muted}\"\n\
         accent       = \"{accent}\"\n\
         accent_soft  = \"{accent_soft}\"\n\
         danger       = \"{danger}\"\n\
         login_title    = \"User\"\n\
         password_title = \"Password\"\n",
        bg = col!(c.surface),
        panel_border = col!(c.surface_variant),
        field_border = col!(c.outline),
        text = col!(c.on_surface),
        subtext = col!(c.on_surface_variant),
        muted = col!(c.on_surface_variant),
        accent = col!(c.primary),
        accent_soft = col!(c.tertiary),
        danger = col!(c.error),
    )
}

pub fn to_css(theme: &MatugenTheme) -> String {
    let c = &theme.colors;
    let mode = &theme.mode;

    macro_rules! col {
        ($field:expr) => {
            match mode.as_str() {
                "dark" => &$field.dark.color,
                "light" => &$field.light.color,
                _ => &$field.default.color,
            }
        };
    }

    format!(
        r#":root {{
    --surface: {surface};
    --on-surface: {on_surface};
    --surface-variant: {surface_variant};
    --on-surface-variant: {on_surface_variant};
    --surface-container-highest: {surface_container_highest};
    --surface-container-high: {surface_container_high};
    --surface-container: {surface_container};
    --surface-container-low: {surface_container_low};
    --surface-container-lowest: {surface_container_lowest};
    --inverse-surface: {inverse_surface};
    --inverse-on-surface: {inverse_on_surface};
    --surface-tint: {surface_tint};
    --surface-tint-color: {surface_tint};
    --primary: {primary};
    --on-primary: {on_primary};
    --primary-container: {primary_container};
    --on-primary-container: {on_primary_container};
    --secondary: {secondary};
    --on-secondary: {on_secondary};
    --secondary-container: {secondary_container};
    --on-secondary-container: {on_secondary_container};
    --tertiary: {tertiary};
    --on-tertiary: {on_tertiary};
    --tertiary-container: {tertiary_container};
    --on-tertiary-container: {on_tertiary_container};
    --error: {error};
    --on-error: {on_error};
    --error-container: {error_container};
    --on-error-container: {on_error_container};
    --outline: {outline};
    --outline-variant: {outline_variant};
}}"#,
        surface = col!(c.surface),
        on_surface = col!(c.on_surface),
        surface_variant = col!(c.surface_variant),
        on_surface_variant = col!(c.on_surface_variant),
        surface_container_highest = col!(c.surface_container_highest),
        surface_container_high = col!(c.surface_container_high),
        surface_container = col!(c.surface_container),
        surface_container_low = col!(c.surface_container_low),
        surface_container_lowest = col!(c.surface_container_lowest),
        inverse_surface = col!(c.inverse_surface),
        inverse_on_surface = col!(c.inverse_on_surface),
        surface_tint = col!(c.surface_tint),
        primary = col!(c.primary),
        on_primary = col!(c.on_primary),
        primary_container = col!(c.primary_container),
        on_primary_container = col!(c.on_primary_container),
        secondary = col!(c.secondary),
        on_secondary = col!(c.on_secondary),
        secondary_container = col!(c.secondary_container),
        on_secondary_container = col!(c.on_secondary_container),
        tertiary = col!(c.tertiary),
        on_tertiary = col!(c.on_tertiary),
        tertiary_container = col!(c.tertiary_container),
        on_tertiary_container = col!(c.on_tertiary_container),
        error = col!(c.error),
        on_error = col!(c.on_error),
        error_container = col!(c.error_container),
        on_error_container = col!(c.on_error_container),
        outline = col!(c.outline),
        outline_variant = col!(c.outline_variant),
    )
}

/// Build the `~/.cache/margo/mshell-colors.toml` sidecar that external,
/// out-of-process panels read so they stay in step with the shell's
/// wallpaper scheme without linking to mshell. Today's consumer is the
/// standalone `mvpn menu` panel; the schema mirrors what its theme loader
/// expects (`[appearance]` with `background_color`/`primary_color` tables,
/// `#rrggbb` hex). Without this the file went stale and panels rendered a
/// month-old palette (the "why is mvpn brown" bug).
pub fn to_mshell_colors(theme: &MatugenTheme) -> String {
    let c = &theme.colors;
    let mode = &theme.mode;

    macro_rules! col {
        ($field:expr) => {
            match mode.as_str() {
                "dark" => $field.dark.color.trim(),
                "light" => $field.light.color.trim(),
                _ => $field.default.color.trim(),
            }
        };
    }

    format!(
        "# Auto-generated by mshell from the matugen palette — do not edit.\n\
         # Read by external panels (e.g. `mvpn menu`) to match the shell.\n\
         \n\
         [appearance]\n\
         background_color = {{ base = \"{base}\", weak = \"{weak}\", neutral = \"{neutral}\", text = \"{text}\" }}\n\
         primary_color    = {{ base = \"{primary}\", text = \"{on_primary}\" }}\n\
         danger_color     = \"{danger}\"\n\
         text_color       = \"{text}\"\n",
        base = col!(c.surface),
        weak = col!(c.surface_container),
        neutral = col!(c.surface_container_high),
        text = col!(c.on_surface),
        primary = col!(c.primary),
        on_primary = col!(c.on_primary),
        danger = col!(c.error),
    )
}

/// Build margo `.conf` window-border colour overrides from the same
/// palette. Maps Material roles → margo's border colour keys so the
/// compositor's window borders track the wallpaper scheme alongside the
/// shell UI. `rootcolor` is intentionally left to the user's static
/// config. Emitted as `0xRRGGBBAA` (margo's `parse_color` accepts that).
pub fn to_margo_colors(theme: &MatugenTheme) -> String {
    let c = &theme.colors;
    let mode = &theme.mode;

    macro_rules! col {
        ($field:expr) => {
            match mode.as_str() {
                "dark" => &$field.dark.color,
                "light" => &$field.light.color,
                _ => &$field.default.color,
            }
        };
    }

    // matugen `--json hex` yields `#rrggbb`; margo wants `0xrrggbbAA`.
    fn margo(hex: &str, alpha: &str) -> String {
        let rgb: String = hex
            .trim()
            .trim_start_matches('#')
            .trim_start_matches("0x")
            .chars()
            .take(6)
            .collect();
        format!("0x{rgb}{alpha}")
    }

    format!(
        "# Auto-generated by mshell from the matugen palette — do not edit.\n\
         # `source`d from config.conf; overrides the static border colours.\n\
         focuscolor      = {focus}\n\
         bordercolor     = {border}\n\
         urgentcolor     = {urgent}\n\
         scratchpadcolor = {scratch}\n\
         globalcolor     = {global}\n\
         overlaycolor    = {overlay}\n\
         shadowscolor    = {shadow}\n",
        focus = margo(col!(c.primary), "ff"),
        border = margo(col!(c.outline), "ff"),
        urgent = margo(col!(c.error), "ff"),
        scratch = margo(col!(c.tertiary), "ff"),
        global = margo(col!(c.secondary), "ff"),
        overlay = margo(col!(c.primary_container), "ff"),
        // Window glow: a SUBTLE ambient lift, not a frame. Muted
        // `primary_container` (desaturated, distinct from the bright
        // `primary` border) at ~8% alpha — low enough that the glow stays
        // below the content in the visual hierarchy (Material/GNOME feel
        // the halo at ~5–10% of the surface). Paired with a moderate,
        // tight blur in config.conf so it hugs the window instead of
        // sprawling. (Was 0x26/~15%, which competed with the content; the
        // even older default was the dark `shadow` role at 0x99.)
        shadow = margo(col!(c.primary_container), "14"),
    )
}
