# Print an optspec for argparse to handle cmd's options that are independent of any subcommand.
function __fish_mdots_global_optspecs
	string join \n j/json h/help V/version
end

function __fish_mdots_needs_command
	# Figure out if the current invocation already has a command.
	set -l cmd (commandline -opc)
	set -e cmd[1]
	argparse -s (__fish_mdots_global_optspecs) -- $cmd 2>/dev/null
	or return
	if set -q argv[1]
		# Also print the command, so this can be used to figure out what it is.
		echo $argv[1]
		return 1
	end
	return 0
end

function __fish_mdots_using_subcommand
	set -l cmd (__fish_mdots_needs_command)
	test -z "$cmd"
	and return 1
	contains -- $cmd[1] $argv
end

complete -c mdots -n "__fish_mdots_needs_command" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_needs_command" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_needs_command" -s V -l version -d 'Print version'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "init" -d 'Initialize mdots configuration directory structure'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "install" -d 'Install a package and add to mdots management'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "remove" -d 'Remove a package and untrack from mdots'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "status" -d 'Show current configuration and sync status'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "sync" -d 'Sync packages to match configuration'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "module" -d 'Module management commands'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "service" -d 'Service profile management commands'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "secrets" -d 'SOPS/age secrets management commands'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "update" -d 'Update system (respects version constraints)'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "merge" -d 'Add unmanaged installed packages to system-packages.yaml'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "migrate" -d 'Migrate from old structure (packages/) to new structure (hosts/, modules/)'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "find" -d 'Find where a package is defined in your mdots config'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "forget" -d 'Remove a package from mdots tracking without uninstalling it'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "validate" -d 'Validate mdots config structure and modules'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "save-config" -d 'Save current configuration as a backup'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "restore-config" -d 'Restore configuration from a backup'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "hooks" -d 'Post-install hook management'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "repo" -d 'Git repository management'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "backup" -d 'Backup/snapshot management'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "restore" -d 'Restore from backup snapshot'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "self-update" -d 'Update mdots from git repository'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "nix" -d 'Nix package manager and Home Manager integration'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "search" -d 'Search for packages with interactive TUI'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "edit" -d 'Edit configuration files with interactive TUI selector'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "tui" -d 'Launch interactive TUI'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "generate" -d 'Generate configuration files'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "source" -d 'Build packages from source using makepkg'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "completion" -d 'Generate a shell completion script (bash, zsh, fish, …)'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "man" -d 'Print the man page (roff) to stdout'
complete -c mdots -n "__fish_mdots_needs_command" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c mdots -n "__fish_mdots_using_subcommand init" -s b -l bd -d 'Bootstrap from BlackDon\'s config'
complete -c mdots -n "__fish_mdots_using_subcommand init" -s a -l adv -l lua -d 'Advanced setup with Lua configuration files'
complete -c mdots -n "__fish_mdots_using_subcommand init" -l nix -d 'Initialize with Nix configuration files'
complete -c mdots -n "__fish_mdots_using_subcommand init" -l nix-init -d 'Install Nix and set up Home Manager integration'
complete -c mdots -n "__fish_mdots_using_subcommand init" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand init" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand install" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand install" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand remove" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand remove" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand status" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand status" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand sync" -s d -l dry-run -d 'Preview changes without applying'
complete -c mdots -n "__fish_mdots_using_subcommand sync" -l prune -d 'Remove packages not in configuration'
complete -c mdots -n "__fish_mdots_using_subcommand sync" -l force -d 'Skip confirmation prompts'
complete -c mdots -n "__fish_mdots_using_subcommand sync" -l no-backup -d 'Skip automatic backup'
complete -c mdots -n "__fish_mdots_using_subcommand sync" -l no-hooks -d 'Skip post-install hooks'
complete -c mdots -n "__fish_mdots_using_subcommand sync" -l force-dotfiles -d 'Force re-sync dotfiles even if already synced'
complete -c mdots -n "__fish_mdots_using_subcommand sync" -l auto-commit -d 'Automatically commit changes to git after successful sync'
complete -c mdots -n "__fish_mdots_using_subcommand sync" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand sync" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand module; and not __fish_seen_subcommand_from list enable disable run-hook create help" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand module; and not __fish_seen_subcommand_from list enable disable run-hook create help" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand module; and not __fish_seen_subcommand_from list enable disable run-hook create help" -f -a "list" -d 'List all available modules'
complete -c mdots -n "__fish_mdots_using_subcommand module; and not __fish_seen_subcommand_from list enable disable run-hook create help" -f -a "enable" -d 'Enable a module'
complete -c mdots -n "__fish_mdots_using_subcommand module; and not __fish_seen_subcommand_from list enable disable run-hook create help" -f -a "disable" -d 'Disable a module'
complete -c mdots -n "__fish_mdots_using_subcommand module; and not __fish_seen_subcommand_from list enable disable run-hook create help" -f -a "run-hook" -d 'Run a module\'s post-install hook'
complete -c mdots -n "__fish_mdots_using_subcommand module; and not __fish_seen_subcommand_from list enable disable run-hook create help" -f -a "create" -d 'Create a new module with template'
complete -c mdots -n "__fish_mdots_using_subcommand module; and not __fish_seen_subcommand_from list enable disable run-hook create help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c mdots -n "__fish_mdots_using_subcommand module; and __fish_seen_subcommand_from list" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand module; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand module; and __fish_seen_subcommand_from enable" -l skip-sync -d 'Enable modules without prompting to run sync afterward'
complete -c mdots -n "__fish_mdots_using_subcommand module; and __fish_seen_subcommand_from enable" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand module; and __fish_seen_subcommand_from enable" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand module; and __fish_seen_subcommand_from disable" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand module; and __fish_seen_subcommand_from disable" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand module; and __fish_seen_subcommand_from run-hook" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand module; and __fish_seen_subcommand_from run-hook" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand module; and __fish_seen_subcommand_from create" -l lua -d 'Force Lua format even if using YAML config'
complete -c mdots -n "__fish_mdots_using_subcommand module; and __fish_seen_subcommand_from create" -l nix -d 'Force Nix format even if using YAML config'
complete -c mdots -n "__fish_mdots_using_subcommand module; and __fish_seen_subcommand_from create" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand module; and __fish_seen_subcommand_from create" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand module; and __fish_seen_subcommand_from help" -f -a "list" -d 'List all available modules'
complete -c mdots -n "__fish_mdots_using_subcommand module; and __fish_seen_subcommand_from help" -f -a "enable" -d 'Enable a module'
complete -c mdots -n "__fish_mdots_using_subcommand module; and __fish_seen_subcommand_from help" -f -a "disable" -d 'Disable a module'
complete -c mdots -n "__fish_mdots_using_subcommand module; and __fish_seen_subcommand_from help" -f -a "run-hook" -d 'Run a module\'s post-install hook'
complete -c mdots -n "__fish_mdots_using_subcommand module; and __fish_seen_subcommand_from help" -f -a "create" -d 'Create a new module with template'
complete -c mdots -n "__fish_mdots_using_subcommand module; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c mdots -n "__fish_mdots_using_subcommand service; and not __fish_seen_subcommand_from list enable disable show help" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand service; and not __fish_seen_subcommand_from list enable disable show help" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand service; and not __fish_seen_subcommand_from list enable disable show help" -f -a "list" -d 'List all available service profiles'
complete -c mdots -n "__fish_mdots_using_subcommand service; and not __fish_seen_subcommand_from list enable disable show help" -f -a "enable" -d 'Enable a service profile'
complete -c mdots -n "__fish_mdots_using_subcommand service; and not __fish_seen_subcommand_from list enable disable show help" -f -a "disable" -d 'Disable a service profile'
complete -c mdots -n "__fish_mdots_using_subcommand service; and not __fish_seen_subcommand_from list enable disable show help" -f -a "show" -d 'Show details of a service profile'
complete -c mdots -n "__fish_mdots_using_subcommand service; and not __fish_seen_subcommand_from list enable disable show help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c mdots -n "__fish_mdots_using_subcommand service; and __fish_seen_subcommand_from list" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand service; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand service; and __fish_seen_subcommand_from enable" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand service; and __fish_seen_subcommand_from enable" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand service; and __fish_seen_subcommand_from disable" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand service; and __fish_seen_subcommand_from disable" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand service; and __fish_seen_subcommand_from show" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand service; and __fish_seen_subcommand_from show" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand service; and __fish_seen_subcommand_from help" -f -a "list" -d 'List all available service profiles'
complete -c mdots -n "__fish_mdots_using_subcommand service; and __fish_seen_subcommand_from help" -f -a "enable" -d 'Enable a service profile'
complete -c mdots -n "__fish_mdots_using_subcommand service; and __fish_seen_subcommand_from help" -f -a "disable" -d 'Disable a service profile'
complete -c mdots -n "__fish_mdots_using_subcommand service; and __fish_seen_subcommand_from help" -f -a "show" -d 'Show details of a service profile'
complete -c mdots -n "__fish_mdots_using_subcommand service; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c mdots -n "__fish_mdots_using_subcommand secrets; and not __fish_seen_subcommand_from status sync list edit keygen help" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand secrets; and not __fish_seen_subcommand_from status sync list edit keygen help" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand secrets; and not __fish_seen_subcommand_from status sync list edit keygen help" -f -a "status" -d 'Show the status of declared secrets (read-only)'
complete -c mdots -n "__fish_mdots_using_subcommand secrets; and not __fish_seen_subcommand_from status sync list edit keygen help" -f -a "sync" -d 'Decrypt declared secrets into place (without a full sync)'
complete -c mdots -n "__fish_mdots_using_subcommand secrets; and not __fish_seen_subcommand_from status sync list edit keygen help" -f -a "list" -d 'List declared secrets (from config, no filesystem access)'
complete -c mdots -n "__fish_mdots_using_subcommand secrets; and not __fish_seen_subcommand_from status sync list edit keygen help" -f -a "edit" -d 'Edit an encrypted secret with `sops`'
complete -c mdots -n "__fish_mdots_using_subcommand secrets; and not __fish_seen_subcommand_from status sync list edit keygen help" -f -a "keygen" -d 'Generate an age key if one does not already exist'
complete -c mdots -n "__fish_mdots_using_subcommand secrets; and not __fish_seen_subcommand_from status sync list edit keygen help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c mdots -n "__fish_mdots_using_subcommand secrets; and __fish_seen_subcommand_from status" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand secrets; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand secrets; and __fish_seen_subcommand_from sync" -l dry-run -d 'Show what would change without writing anything'
complete -c mdots -n "__fish_mdots_using_subcommand secrets; and __fish_seen_subcommand_from sync" -l prune -d 'Remove plaintext targets of secrets that are no longer declared'
complete -c mdots -n "__fish_mdots_using_subcommand secrets; and __fish_seen_subcommand_from sync" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand secrets; and __fish_seen_subcommand_from sync" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand secrets; and __fish_seen_subcommand_from list" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand secrets; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand secrets; and __fish_seen_subcommand_from edit" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand secrets; and __fish_seen_subcommand_from edit" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand secrets; and __fish_seen_subcommand_from keygen" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand secrets; and __fish_seen_subcommand_from keygen" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand secrets; and __fish_seen_subcommand_from help" -f -a "status" -d 'Show the status of declared secrets (read-only)'
complete -c mdots -n "__fish_mdots_using_subcommand secrets; and __fish_seen_subcommand_from help" -f -a "sync" -d 'Decrypt declared secrets into place (without a full sync)'
complete -c mdots -n "__fish_mdots_using_subcommand secrets; and __fish_seen_subcommand_from help" -f -a "list" -d 'List declared secrets (from config, no filesystem access)'
complete -c mdots -n "__fish_mdots_using_subcommand secrets; and __fish_seen_subcommand_from help" -f -a "edit" -d 'Edit an encrypted secret with `sops`'
complete -c mdots -n "__fish_mdots_using_subcommand secrets; and __fish_seen_subcommand_from help" -f -a "keygen" -d 'Generate an age key if one does not already exist'
complete -c mdots -n "__fish_mdots_using_subcommand secrets; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c mdots -n "__fish_mdots_using_subcommand update" -l no-backup -d 'Skip automatic backup'
complete -c mdots -n "__fish_mdots_using_subcommand update" -l no-hooks -d 'Skip update hooks'
complete -c mdots -n "__fish_mdots_using_subcommand update" -l devel -d 'Update VCS packages (e.g., -git packages) by passing --devel to AUR helper'
complete -c mdots -n "__fish_mdots_using_subcommand update" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand update" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand merge" -s d -l dry-run -d 'Preview packages that would be added'
complete -c mdots -n "__fish_mdots_using_subcommand merge" -l services -d 'Merge currently enabled services instead of packages'
complete -c mdots -n "__fish_mdots_using_subcommand merge" -l user -d 'Merge user-scope services (systemctl --user) instead of system services'
complete -c mdots -n "__fish_mdots_using_subcommand merge" -l defaults -d 'Merge current default applications'
complete -c mdots -n "__fish_mdots_using_subcommand merge" -l include-deps -d 'Include all installed packages (including dependencies) in a separate module'
complete -c mdots -n "__fish_mdots_using_subcommand merge" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand merge" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand migrate" -s d -l dry-run -d 'Preview migration without applying changes'
complete -c mdots -n "__fish_mdots_using_subcommand migrate" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand migrate" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand find" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand find" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand forget" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand forget" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand validate" -l check-packages -d 'Also check if packages exist in repos (slower)'
complete -c mdots -n "__fish_mdots_using_subcommand validate" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand validate" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand save-config" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand save-config" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand restore-config" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand restore-config" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand hooks; and not __fish_seen_subcommand_from list reset skip run help" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand hooks; and not __fish_seen_subcommand_from list reset skip run help" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand hooks; and not __fish_seen_subcommand_from list reset skip run help" -f -a "list" -d 'List all hooks and their execution status'
complete -c mdots -n "__fish_mdots_using_subcommand hooks; and not __fish_seen_subcommand_from list reset skip run help" -f -a "reset" -d 'Reset a hook to "not run" state (will run on next sync)'
complete -c mdots -n "__fish_mdots_using_subcommand hooks; and not __fish_seen_subcommand_from list reset skip run help" -f -a "skip" -d 'Skip a hook permanently (mark as "don\'t run")'
complete -c mdots -n "__fish_mdots_using_subcommand hooks; and not __fish_seen_subcommand_from list reset skip run help" -f -a "run" -d 'Manually run a module\'s hook'
complete -c mdots -n "__fish_mdots_using_subcommand hooks; and not __fish_seen_subcommand_from list reset skip run help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c mdots -n "__fish_mdots_using_subcommand hooks; and __fish_seen_subcommand_from list" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand hooks; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand hooks; and __fish_seen_subcommand_from reset" -l pre -d 'Reset the pre-install hook instead of post-install'
complete -c mdots -n "__fish_mdots_using_subcommand hooks; and __fish_seen_subcommand_from reset" -l disable -d 'Reset the disable hook instead of post-install'
complete -c mdots -n "__fish_mdots_using_subcommand hooks; and __fish_seen_subcommand_from reset" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand hooks; and __fish_seen_subcommand_from reset" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand hooks; and __fish_seen_subcommand_from skip" -l pre -d 'Skip the pre-install hook instead of post-install'
complete -c mdots -n "__fish_mdots_using_subcommand hooks; and __fish_seen_subcommand_from skip" -l disable -d 'Skip the disable hook instead of post-install'
complete -c mdots -n "__fish_mdots_using_subcommand hooks; and __fish_seen_subcommand_from skip" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand hooks; and __fish_seen_subcommand_from skip" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand hooks; and __fish_seen_subcommand_from run" -l pre -d 'Run the pre-install hook instead of post-install'
complete -c mdots -n "__fish_mdots_using_subcommand hooks; and __fish_seen_subcommand_from run" -l disable -d 'Run the disable hook instead of post-install'
complete -c mdots -n "__fish_mdots_using_subcommand hooks; and __fish_seen_subcommand_from run" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand hooks; and __fish_seen_subcommand_from run" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand hooks; and __fish_seen_subcommand_from help" -f -a "list" -d 'List all hooks and their execution status'
complete -c mdots -n "__fish_mdots_using_subcommand hooks; and __fish_seen_subcommand_from help" -f -a "reset" -d 'Reset a hook to "not run" state (will run on next sync)'
complete -c mdots -n "__fish_mdots_using_subcommand hooks; and __fish_seen_subcommand_from help" -f -a "skip" -d 'Skip a hook permanently (mark as "don\'t run")'
complete -c mdots -n "__fish_mdots_using_subcommand hooks; and __fish_seen_subcommand_from help" -f -a "run" -d 'Manually run a module\'s hook'
complete -c mdots -n "__fish_mdots_using_subcommand hooks; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c mdots -n "__fish_mdots_using_subcommand repo; and not __fish_seen_subcommand_from init clone push pull status help" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand repo; and not __fish_seen_subcommand_from init clone push pull status help" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand repo; and not __fish_seen_subcommand_from init clone push pull status help" -f -a "init" -d 'Initialize git repository for mdots config'
complete -c mdots -n "__fish_mdots_using_subcommand repo; and not __fish_seen_subcommand_from init clone push pull status help" -f -a "clone" -d 'Clone existing mdots config repository'
complete -c mdots -n "__fish_mdots_using_subcommand repo; and not __fish_seen_subcommand_from init clone push pull status help" -f -a "push" -d 'Commit and push changes'
complete -c mdots -n "__fish_mdots_using_subcommand repo; and not __fish_seen_subcommand_from init clone push pull status help" -f -a "pull" -d 'Pull updates from remote'
complete -c mdots -n "__fish_mdots_using_subcommand repo; and not __fish_seen_subcommand_from init clone push pull status help" -f -a "status" -d 'Show repository status'
complete -c mdots -n "__fish_mdots_using_subcommand repo; and not __fish_seen_subcommand_from init clone push pull status help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c mdots -n "__fish_mdots_using_subcommand repo; and __fish_seen_subcommand_from init" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand repo; and __fish_seen_subcommand_from init" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand repo; and __fish_seen_subcommand_from clone" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand repo; and __fish_seen_subcommand_from clone" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand repo; and __fish_seen_subcommand_from push" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand repo; and __fish_seen_subcommand_from push" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand repo; and __fish_seen_subcommand_from pull" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand repo; and __fish_seen_subcommand_from pull" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand repo; and __fish_seen_subcommand_from status" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand repo; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand repo; and __fish_seen_subcommand_from help" -f -a "init" -d 'Initialize git repository for mdots config'
complete -c mdots -n "__fish_mdots_using_subcommand repo; and __fish_seen_subcommand_from help" -f -a "clone" -d 'Clone existing mdots config repository'
complete -c mdots -n "__fish_mdots_using_subcommand repo; and __fish_seen_subcommand_from help" -f -a "push" -d 'Commit and push changes'
complete -c mdots -n "__fish_mdots_using_subcommand repo; and __fish_seen_subcommand_from help" -f -a "pull" -d 'Pull updates from remote'
complete -c mdots -n "__fish_mdots_using_subcommand repo; and __fish_seen_subcommand_from help" -f -a "status" -d 'Show repository status'
complete -c mdots -n "__fish_mdots_using_subcommand repo; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c mdots -n "__fish_mdots_using_subcommand backup; and not __fish_seen_subcommand_from list delete check help" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand backup; and not __fish_seen_subcommand_from list delete check help" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand backup; and not __fish_seen_subcommand_from list delete check help" -f -a "list" -d 'List backup snapshots'
complete -c mdots -n "__fish_mdots_using_subcommand backup; and not __fish_seen_subcommand_from list delete check help" -f -a "delete" -d 'Delete a snapshot'
complete -c mdots -n "__fish_mdots_using_subcommand backup; and not __fish_seen_subcommand_from list delete check help" -f -a "check" -d 'Check backup configuration'
complete -c mdots -n "__fish_mdots_using_subcommand backup; and not __fish_seen_subcommand_from list delete check help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c mdots -n "__fish_mdots_using_subcommand backup; and __fish_seen_subcommand_from list" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand backup; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand backup; and __fish_seen_subcommand_from delete" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand backup; and __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand backup; and __fish_seen_subcommand_from check" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand backup; and __fish_seen_subcommand_from check" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand backup; and __fish_seen_subcommand_from help" -f -a "list" -d 'List backup snapshots'
complete -c mdots -n "__fish_mdots_using_subcommand backup; and __fish_seen_subcommand_from help" -f -a "delete" -d 'Delete a snapshot'
complete -c mdots -n "__fish_mdots_using_subcommand backup; and __fish_seen_subcommand_from help" -f -a "check" -d 'Check backup configuration'
complete -c mdots -n "__fish_mdots_using_subcommand backup; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c mdots -n "__fish_mdots_using_subcommand restore" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand restore" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand self-update" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand self-update" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand nix; and not __fish_seen_subcommand_from install switch update search status help" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand nix; and not __fish_seen_subcommand_from install switch update search status help" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand nix; and not __fish_seen_subcommand_from install switch update search status help" -f -a "install" -d 'Install Nix and Home Manager'
complete -c mdots -n "__fish_mdots_using_subcommand nix; and not __fish_seen_subcommand_from install switch update search status help" -f -a "switch" -d 'Run Home Manager switch'
complete -c mdots -n "__fish_mdots_using_subcommand nix; and not __fish_seen_subcommand_from install switch update search status help" -f -a "update" -d 'Update Nix channels and run Home Manager switch'
complete -c mdots -n "__fish_mdots_using_subcommand nix; and not __fish_seen_subcommand_from install switch update search status help" -f -a "search" -d 'Search Nixpkgs for packages'
complete -c mdots -n "__fish_mdots_using_subcommand nix; and not __fish_seen_subcommand_from install switch update search status help" -f -a "status" -d 'Show Nix and Home Manager status'
complete -c mdots -n "__fish_mdots_using_subcommand nix; and not __fish_seen_subcommand_from install switch update search status help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c mdots -n "__fish_mdots_using_subcommand nix; and __fish_seen_subcommand_from install" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand nix; and __fish_seen_subcommand_from install" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand nix; and __fish_seen_subcommand_from switch" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand nix; and __fish_seen_subcommand_from switch" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand nix; and __fish_seen_subcommand_from update" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand nix; and __fish_seen_subcommand_from update" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand nix; and __fish_seen_subcommand_from search" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand nix; and __fish_seen_subcommand_from search" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand nix; and __fish_seen_subcommand_from status" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand nix; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand nix; and __fish_seen_subcommand_from help" -f -a "install" -d 'Install Nix and Home Manager'
complete -c mdots -n "__fish_mdots_using_subcommand nix; and __fish_seen_subcommand_from help" -f -a "switch" -d 'Run Home Manager switch'
complete -c mdots -n "__fish_mdots_using_subcommand nix; and __fish_seen_subcommand_from help" -f -a "update" -d 'Update Nix channels and run Home Manager switch'
complete -c mdots -n "__fish_mdots_using_subcommand nix; and __fish_seen_subcommand_from help" -f -a "search" -d 'Search Nixpkgs for packages'
complete -c mdots -n "__fish_mdots_using_subcommand nix; and __fish_seen_subcommand_from help" -f -a "status" -d 'Show Nix and Home Manager status'
complete -c mdots -n "__fish_mdots_using_subcommand nix; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c mdots -n "__fish_mdots_using_subcommand search" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand search" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand edit" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand edit" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand tui" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand tui" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand generate; and not __fish_seen_subcommand_from hardware service storage util help" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand generate; and not __fish_seen_subcommand_from hardware service storage util help" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand generate; and not __fish_seen_subcommand_from hardware service storage util help" -f -a "hardware" -d 'Generate hardware.lua module with auto-detection'
complete -c mdots -n "__fish_mdots_using_subcommand generate; and not __fish_seen_subcommand_from hardware service storage util help" -f -a "service" -d 'Generate service.lua module with detected services'
complete -c mdots -n "__fish_mdots_using_subcommand generate; and not __fish_seen_subcommand_from hardware service storage util help" -f -a "storage" -d 'Generate storage.lua module with detected storage configuration'
complete -c mdots -n "__fish_mdots_using_subcommand generate; and not __fish_seen_subcommand_from hardware service storage util help" -f -a "util" -d 'Generate util.lua module with system utilities'
complete -c mdots -n "__fish_mdots_using_subcommand generate; and not __fish_seen_subcommand_from hardware service storage util help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c mdots -n "__fish_mdots_using_subcommand generate; and __fish_seen_subcommand_from hardware" -s f -l force -d 'Overwrite existing hardware.lua if it exists'
complete -c mdots -n "__fish_mdots_using_subcommand generate; and __fish_seen_subcommand_from hardware" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand generate; and __fish_seen_subcommand_from hardware" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand generate; and __fish_seen_subcommand_from service" -s f -l force -d 'Overwrite existing service.lua if it exists'
complete -c mdots -n "__fish_mdots_using_subcommand generate; and __fish_seen_subcommand_from service" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand generate; and __fish_seen_subcommand_from service" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand generate; and __fish_seen_subcommand_from storage" -s f -l force -d 'Overwrite existing storage.lua if it exists'
complete -c mdots -n "__fish_mdots_using_subcommand generate; and __fish_seen_subcommand_from storage" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand generate; and __fish_seen_subcommand_from storage" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand generate; and __fish_seen_subcommand_from util" -s f -l force -d 'Overwrite existing util.lua if it exists'
complete -c mdots -n "__fish_mdots_using_subcommand generate; and __fish_seen_subcommand_from util" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand generate; and __fish_seen_subcommand_from util" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand generate; and __fish_seen_subcommand_from help" -f -a "hardware" -d 'Generate hardware.lua module with auto-detection'
complete -c mdots -n "__fish_mdots_using_subcommand generate; and __fish_seen_subcommand_from help" -f -a "service" -d 'Generate service.lua module with detected services'
complete -c mdots -n "__fish_mdots_using_subcommand generate; and __fish_seen_subcommand_from help" -f -a "storage" -d 'Generate storage.lua module with detected storage configuration'
complete -c mdots -n "__fish_mdots_using_subcommand generate; and __fish_seen_subcommand_from help" -f -a "util" -d 'Generate util.lua module with system utilities'
complete -c mdots -n "__fish_mdots_using_subcommand generate; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c mdots -n "__fish_mdots_using_subcommand source; and not __fish_seen_subcommand_from list build rebuild remove status help" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand source; and not __fish_seen_subcommand_from list build rebuild remove status help" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand source; and not __fish_seen_subcommand_from list build rebuild remove status help" -f -a "list" -d 'List all declared sources and their install status'
complete -c mdots -n "__fish_mdots_using_subcommand source; and not __fish_seen_subcommand_from list build rebuild remove status help" -f -a "build" -d 'Build and install sources (all by default, or a specific one by name)'
complete -c mdots -n "__fish_mdots_using_subcommand source; and not __fish_seen_subcommand_from list build rebuild remove status help" -f -a "rebuild" -d 'Force clean rebuild of sources (all by default, or a specific one by name)'
complete -c mdots -n "__fish_mdots_using_subcommand source; and not __fish_seen_subcommand_from list build rebuild remove status help" -f -a "remove" -d 'Uninstall a source-built package via pacman'
complete -c mdots -n "__fish_mdots_using_subcommand source; and not __fish_seen_subcommand_from list build rebuild remove status help" -f -a "status" -d 'Show install status of all sources'
complete -c mdots -n "__fish_mdots_using_subcommand source; and not __fish_seen_subcommand_from list build rebuild remove status help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c mdots -n "__fish_mdots_using_subcommand source; and __fish_seen_subcommand_from list" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand source; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand source; and __fish_seen_subcommand_from build" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand source; and __fish_seen_subcommand_from build" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand source; and __fish_seen_subcommand_from rebuild" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand source; and __fish_seen_subcommand_from rebuild" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand source; and __fish_seen_subcommand_from remove" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand source; and __fish_seen_subcommand_from remove" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand source; and __fish_seen_subcommand_from status" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand source; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand source; and __fish_seen_subcommand_from help" -f -a "list" -d 'List all declared sources and their install status'
complete -c mdots -n "__fish_mdots_using_subcommand source; and __fish_seen_subcommand_from help" -f -a "build" -d 'Build and install sources (all by default, or a specific one by name)'
complete -c mdots -n "__fish_mdots_using_subcommand source; and __fish_seen_subcommand_from help" -f -a "rebuild" -d 'Force clean rebuild of sources (all by default, or a specific one by name)'
complete -c mdots -n "__fish_mdots_using_subcommand source; and __fish_seen_subcommand_from help" -f -a "remove" -d 'Uninstall a source-built package via pacman'
complete -c mdots -n "__fish_mdots_using_subcommand source; and __fish_seen_subcommand_from help" -f -a "status" -d 'Show install status of all sources'
complete -c mdots -n "__fish_mdots_using_subcommand source; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c mdots -n "__fish_mdots_using_subcommand completion" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand completion" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand man" -s j -l json -d 'Output in JSON format (for programmatic use)'
complete -c mdots -n "__fish_mdots_using_subcommand man" -s h -l help -d 'Print help'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "init" -d 'Initialize mdots configuration directory structure'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "install" -d 'Install a package and add to mdots management'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "remove" -d 'Remove a package and untrack from mdots'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "status" -d 'Show current configuration and sync status'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "sync" -d 'Sync packages to match configuration'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "module" -d 'Module management commands'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "service" -d 'Service profile management commands'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "secrets" -d 'SOPS/age secrets management commands'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "update" -d 'Update system (respects version constraints)'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "merge" -d 'Add unmanaged installed packages to system-packages.yaml'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "migrate" -d 'Migrate from old structure (packages/) to new structure (hosts/, modules/)'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "find" -d 'Find where a package is defined in your mdots config'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "forget" -d 'Remove a package from mdots tracking without uninstalling it'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "validate" -d 'Validate mdots config structure and modules'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "save-config" -d 'Save current configuration as a backup'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "restore-config" -d 'Restore configuration from a backup'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "hooks" -d 'Post-install hook management'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "repo" -d 'Git repository management'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "backup" -d 'Backup/snapshot management'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "restore" -d 'Restore from backup snapshot'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "self-update" -d 'Update mdots from git repository'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "nix" -d 'Nix package manager and Home Manager integration'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "search" -d 'Search for packages with interactive TUI'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "edit" -d 'Edit configuration files with interactive TUI selector'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "tui" -d 'Launch interactive TUI'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "generate" -d 'Generate configuration files'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "source" -d 'Build packages from source using makepkg'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "completion" -d 'Generate a shell completion script (bash, zsh, fish, …)'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "man" -d 'Print the man page (roff) to stdout'
complete -c mdots -n "__fish_mdots_using_subcommand help; and not __fish_seen_subcommand_from init install remove status sync module service secrets update merge migrate find forget validate save-config restore-config hooks repo backup restore self-update nix search edit tui generate source completion man help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from module" -f -a "list" -d 'List all available modules'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from module" -f -a "enable" -d 'Enable a module'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from module" -f -a "disable" -d 'Disable a module'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from module" -f -a "run-hook" -d 'Run a module\'s post-install hook'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from module" -f -a "create" -d 'Create a new module with template'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from service" -f -a "list" -d 'List all available service profiles'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from service" -f -a "enable" -d 'Enable a service profile'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from service" -f -a "disable" -d 'Disable a service profile'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from service" -f -a "show" -d 'Show details of a service profile'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from secrets" -f -a "status" -d 'Show the status of declared secrets (read-only)'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from secrets" -f -a "sync" -d 'Decrypt declared secrets into place (without a full sync)'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from secrets" -f -a "list" -d 'List declared secrets (from config, no filesystem access)'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from secrets" -f -a "edit" -d 'Edit an encrypted secret with `sops`'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from secrets" -f -a "keygen" -d 'Generate an age key if one does not already exist'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from hooks" -f -a "list" -d 'List all hooks and their execution status'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from hooks" -f -a "reset" -d 'Reset a hook to "not run" state (will run on next sync)'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from hooks" -f -a "skip" -d 'Skip a hook permanently (mark as "don\'t run")'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from hooks" -f -a "run" -d 'Manually run a module\'s hook'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from repo" -f -a "init" -d 'Initialize git repository for mdots config'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from repo" -f -a "clone" -d 'Clone existing mdots config repository'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from repo" -f -a "push" -d 'Commit and push changes'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from repo" -f -a "pull" -d 'Pull updates from remote'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from repo" -f -a "status" -d 'Show repository status'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from backup" -f -a "list" -d 'List backup snapshots'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from backup" -f -a "delete" -d 'Delete a snapshot'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from backup" -f -a "check" -d 'Check backup configuration'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from nix" -f -a "install" -d 'Install Nix and Home Manager'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from nix" -f -a "switch" -d 'Run Home Manager switch'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from nix" -f -a "update" -d 'Update Nix channels and run Home Manager switch'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from nix" -f -a "search" -d 'Search Nixpkgs for packages'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from nix" -f -a "status" -d 'Show Nix and Home Manager status'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from generate" -f -a "hardware" -d 'Generate hardware.lua module with auto-detection'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from generate" -f -a "service" -d 'Generate service.lua module with detected services'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from generate" -f -a "storage" -d 'Generate storage.lua module with detected storage configuration'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from generate" -f -a "util" -d 'Generate util.lua module with system utilities'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from source" -f -a "list" -d 'List all declared sources and their install status'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from source" -f -a "build" -d 'Build and install sources (all by default, or a specific one by name)'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from source" -f -a "rebuild" -d 'Force clean rebuild of sources (all by default, or a specific one by name)'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from source" -f -a "remove" -d 'Uninstall a source-built package via pacman'
complete -c mdots -n "__fish_mdots_using_subcommand help; and __fish_seen_subcommand_from source" -f -a "status" -d 'Show install status of all sources'
